### ISSUE TITLE
播放flv绿屏

### ISSUE THREAD

**Issue by charmfocus** [langhuihui/H5RtmpClient#100]
![image](https://user-images.githubusercontent.com/209699/145163493-d345f974-80fa-43e8-a56c-f35997cb156d.png)

**Comment by bosscheng** [comment]
@charmfocus 条件允许 提供个地址给我，我调试看下。

**Comment by charmfocus** [comment]
> @charmfocus 条件允许 提供个地址给我，我调试看下。

已经发到您的邮箱了，感觉好像是视频编码问题

**Comment by bosscheng** [comment]
@charmfocus 好的，我看下

**Comment by bosscheng** [comment]
@charmfocus 找到问题了，我尝试修复看看

**Comment by bosscheng** [comment]
@charmfocus webgl解析的时候有问题，因为视频的尺寸的原因导致绿屏，另外视频编码也是存在问题的。导致没法后续播放下去，换个正常点的视频看看呢。
