### ISSUE TITLE
推流比播放晚，一直处于“加载中”

### ISSUE THREAD

**Issue by ruixiu** [langhuihui/H5RtmpClient#101]
使用ffmpeg动态推流到monibuca服务：
1.有播放的请求时才调用ffmpeg开始推流
2.播放器一直处于“加载中”

这种情况应该如何处理？

**Comment by bosscheng** [comment]
@ruixiu 有没网络报错情况，播放器是用的什么协议播放的，另外播放器也是有超时时间的，长时间没有流数据，会timeout 错误。

**Comment by ruixiu** [comment]
使用的ws-raw协议（经过一晚上的运行，只有这个协议最稳定），在超时时间到之前查看流媒体服务monibuca的流列表显示流已准备好，重新播放就正常了。。。
目前使用的方案是：执行play后，每隔5s检查是否正在播放，如果没有则再次调用play

**Comment by bosscheng** [comment]
@ruixiu 你可以通过设置timeout 参数为5s，然后监听timeout事件，也是可以了。
