### ISSUE TITLE
音频卡顿

### ISSUE THREAD

**Issue by Smallkserver** [langhuihui/H5RtmpClient#103]
音频会出现断层卡顿，但是MP4封装的视频流在video标签里是正常的，请问下有没有解决办法

**Comment by bosscheng** [comment]
@Smallkserver 通过什么方式播放的，MSE?

**Comment by Smallkserver** [comment]
地址临时贴出来，大佬帮忙看看
https://video.dcyun.com:10000/rtp/gb_play_33078200002000001077_33078253581314000009.flv
https://video.dcyun.com:10000/rtp/gb_play_33078200002000001077_33078253581314000009.live.mp4

**Comment by bosscheng** [comment]
@Smallkserver ok
