### ISSUE TITLE
开启useMSE切换选项卡导致播放器画面卡住

### ISSUE THREAD

**Issue by ruixiu** [langhuihui/H5RtmpClient#105]
@bosscheng 追帧情况正常了。不过又出现了另外的情况（使用chrome浏览器），步骤为：
1.使用官方播放器ws-raw，可以正常播放
2.切换浏览器选项卡再切换回来播放器界面卡住
3.等待一会儿（时间不固定）由花屏慢慢恢复正常

另：不开启硬解码和开启useWCS均无上述情况

**Comment by bosscheng** [comment]
@ruixiu 我操作看下。

**Comment by ruixiu** [comment]
![image](https://user-images.githubusercontent.com/9940354/146317345-b88227e2-3bda-4913-8460-1e9c8687005c.png)
播放一段时间出现这个问题

**Comment by bosscheng** [comment]
@ruixiu ok，我一起看下。

**Comment by ruixiu** [comment]
@bosscheng 这个issue是没有解决方案吗？

**Comment by bosscheng** [comment]
@ruixiu 在努力中。

**Comment by bosscheng** [comment]
@ruixiu 再看下呢。
