### ISSUE TITLE
MSE

### ISSUE THREAD

**Issue by ouyuan666** [langhuihui/H5RtmpClient#108]
1.Edge浏览器(版本：96.0.1054.62)
   出现问题：MSE解码全屏后画面卡住不动，谷歌、手机浏览器不会（这个影响不大，可以要客户用谷歌浏览器）
2.MSE解码失败希望能够向上层抛出异常，然后上层自己再切换软解码
3.希望能够支持HLS的直播功能（因为你说这个播放器定位是直播，但是我这里可能之后如果需要回放的功能，我可以参照改一下）

**Comment by bosscheng** [comment]
@ouyuan666 
问题一我看下，能必先的，我看看能否修复。
问题二我试着修复看下。
问题三你可以先看下hls.js 应该可以解决你的问题。

**Comment by ouyuan666** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月20日(星期一) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] MSE (Issue #108)





 
@ouyuan666
 问题一我看下，能必先的，我看看能否修复。
 问题二我试着修复看下。
 问题三你可以先看下hls.js 应该可以解决你的问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bosscheng** [comment]
@ouyuan666 问题二已经修复了，如果MSE 和webcodecs 解码失败，就直接抛出异常。然后关闭播放。
