### ISSUE TITLE
是否可支持倍速播放

### ISSUE THREAD

**Issue by dawn2zhang** [langhuihui/H5RtmpClient#109]
推流直播中，流推送加速后，播放器播放依然是原速，是否可支持倍速播放（flv）

**Comment by bosscheng** [comment]
@dawn2zhang 暂不支持，你可以自己定制开发，视频那块通过动态设置播放速率，音频那块可以看看soundtouchjs来实现倍数播放音频。我在业务中也实现过倍数播放。
