### ISSUE TITLE
v3.0.2 在useMSE=true 的时候，无法播放h265视频

### ISSUE THREAD

**Issue by zhangyangyang3** [langhuihui/H5RtmpClient#110]
在播放h265视频的时候，如果开启了useMSE，则无法插入h265
建议: 在无法播放h265的时候，自动关闭useMSE

**Comment by bosscheng** [comment]
@zhangyangyang3 现在解决方案就是，直接抛出错误异常，然后关闭播放。

**Comment by zhangyangyang3** [comment]
在3.0.3中实现的吗
