### ISSUE TITLE
Uncaught DOMException: Failed to execute 'transferToImageBitmap' on 'OffscreenCanvas': ImageBitmap construction failed

### ISSUE THREAD

**Issue by hello-lls** [langhuihui/H5RtmpClient#113]
--------------------------------------------------------------console output start--------------------------------------------------------------
hasAudio  false            
on load init
load 播放
sample_rate = 48000
[h264 @ 0x61fe50] Warning: not compiled with thread support, using thread emulation
videoInfo {w: 2560, h: 1440}
start
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

Uncaught DOMException: Failed to execute 'transferToImageBitmap' on 'OffscreenCanvas': ImageBitmap construction failed
    at Object.draw (http://localhost:8080/static/js/jessibuca/index.js:3:666252)
    at methodCaller_void_$unsigned$int_unsigned$int_unsigned$int_unsigned$int$ (eval at uI (http://localhost:8080/static/js/jessibuca/index.js:3:602796), <anonymous>:8:26)
    at II (http://localhost:8080/static/js/jessibuca/index.js:3:610340)
    at http://localhost:8080/static/js/jessibuca/ff.wasm:wasm-function[1460]:0x919b6
    at http://localhost:8080/static/js/jessibuca/ff.wasm:wasm-function[575]:0x3f2d4
    at http://localhost:8080/static/js/jessibuca/ff.wasm:wasm-function[1467]:0x9b910
    at http://localhost:8080/static/js/jessibuca/ff.wasm:wasm-function[706]:0x511fa
    at VideoDecoder$decode [as decode] (eval at uI (http://localhost:8080/static/js/jessibuca/index.js:3:602796), <anonymous>:9:10)
    at http://localhost:8080/static/js/jessibuca/index.js:3:663834

关闭视频
----------------------------------------------------------------console output end--------------------------------------------------------------

![微信截图_20211224093224](https://user-images.githubusercontent.com/40052198/147304990-7cf81fe4-74d3-4951-89b0-b886aa03e42f.png)

**Comment by bosscheng** [comment]
@hello-lls 确认下 你是用的offscreen 模式播放的嘛？
