### ISSUE TITLE
使用wasm播放摄像头的视频流，延时很明显，且调整缓冲时间无太大感知

### ISSUE THREAD

**Issue by ourfor-pp** [langhuihui/H5RtmpClient#118]
使用官网播放器和monibuca2的流做测试

monibuca2自带的jesscibuca播放器延迟为毫秒级，相同的流用官网的播放器播放，延迟大概在4秒左右，调整缓冲时间无效

**Comment by bosscheng** [comment]
@ourfor-pp 能给我个流，我来看下嘛。

**Comment by ourfor-pp** [comment]
@bosscheng 目前使用的都是内网的流，没有公网的，内网环境下测试延迟差异挺大的，公网还没测过

**Comment by ourfor-pp** [comment]
@bosscheng 我本地跑monibucaV2，使用电脑摄像头webrtc推流，monibuca自带的jessica基本无延迟，然后用官网的jessibuca播放有两三秒的延迟，也能复现这个高延迟

**Comment by bosscheng** [comment]
@ourfor-pp 我试下看看

**Comment by bosscheng** [comment]
@ourfor-pp 再试下看看嗯。

**Comment by ourfor-pp** [comment]
@bosscheng 官网是已经更新了吗 ,延迟还是高于monibuca2自带的jessica,调整缓冲时间感知不大，而且好像延迟会持续增大
测试环境：
本地开启monibuca2，使用monibuca2自带的webrtc推流电脑摄像头，对比minibuca自带的jessica播放和jessibuca官网播放
