### ISSUE TITLE
wasm file will download twice time

### ISSUE THREAD

**Issue by thunderyan** [langhuihui/H5RtmpClient#119]
when i deploy and open the demo page v3 which download from github release, the wasm file of the video decoder will download twice time. that will waste the bandwidth to the users.
![iShot2021-12-28 16 03 24](https://user-images.githubusercontent.com/22948357/147558160-a6c7993a-ed6a-4082-bb2b-904fa3d26042.png)

**Comment by bosscheng** [comment]
@thunderyan 再试试看呢。
