### ISSUE TITLE
创建4个以上播放实例会非常卡顿，还会导致页面黑屏。

### ISSUE THREAD

**Issue by qinyifei** [langhuihui/H5RtmpClient#124]

**Comment by bosscheng** [comment]
@qinyifei 用的是什么视频编码格式(h264,h265)，什么分辨率，什么解码格式(wasm,webcodecs,mse)。

**Comment by qinyifei** [comment]
你好，分别是h265,1280*720，wasm

**Comment by bosscheng** [comment]
@qinyifei h265 这么高的分辨率，肯定软解不过来，建议降低分辨率。
