### ISSUE TITLE
使用播放器出现画面渲染区域计算错误解决方法

### ISSUE THREAD

**Issue by xasydxczj** [langhuihui/H5RtmpClient#125]
如果给定div容器添加一些旋转缩放样式就会出现canvas区域计算错误例如下面的代码：
` <div id="video1" style="background-color: rgb(223, 140, 140);width: 960px;height: 540px;position: relative;left: -55.36px;top: -174.037px;transform: matrix(0.77685, 0, 0, 0.77685, 637.778, 249.456);transform-origin: 222.36px 174.037px;display: block;"></div>`

修改方法：
src\player\property.js

export default (player)=>{
    Object.defineProperty(player, 'rect', {
        get: () => {
            var element=player.$container;
            var obj=element.getBoundingClientRect();
            obj.width=element.clientWidth;
            obj.height=element.clientHeight;
            return obj;
        },
    });

    ['bottom', 'height', 'left', 'right', 'top', 'width'].forEach(key => {
        Object.defineProperty(player, key, {
            get: () => {
                return player.rect[key];
            },
        });
    });
}

**Comment by bosscheng** [comment]
@muye-xx 我看下。

**Comment by bosscheng** [comment]
@muye-xx 已经修复上去了。TKS.
