### ISSUE TITLE
将录制的视频保存在安卓手机相册中，显示的时长为0，并且无法播放。

### ISSUE THREAD

**Issue by dengjiali0925** [langhuihui/H5RtmpClient#126]
将录制的视频保存在安卓手机相册中，显示的时长为0，并且无法播放。但是在对应的文件路径中找到源文件是能播放的，但是依然不显示时长。请问这个问题怎么解决呢？

**Comment by bosscheng** [comment]
后续支持录制MP4格式(MPEG-4)的视频录制就可以解决这个问题了。

**Comment by wangdacui2** [comment]
大佬，怎么把录制的视频存进手机相册啊？

**Comment by WangMingHua111** [comment]
webview 不支持 blob协议下载文件，所以，我也想问一下怎么样不通过服务端中转的情况下下载到手机中

**Comment by langhuihui** [comment]
可以先问一下chatgpt
