### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Smallkserver** [langhuihui/H5RtmpClient#127]
请教一下能获取pts值吗

**Comment by bosscheng** [comment]
可以的，http://jessibuca.monibuca.com/api.html#stats   监听 stats ,一秒回调一次， 

buf: 当前缓冲区时长，单位毫秒,
fps: 当前视频帧率,
abps: 当前音频码率，单位bit,
vbps: 当前视频码率，单位bit，
ts:当前视频帧pts，单位毫秒
