### ISSUE TITLE
录制功能

### ISSUE THREAD

**Issue by ycc0207** [langhuihui/H5RtmpClient#128]
最新的dist录制功能无法使用，开启录制按钮，点击无任何反应
1、无音频视频录制不成功，文件大小为0
2、静音视频录制不成功，文件大小为0

**Comment by bosscheng** [comment]
@ycc0207 我在官网测试了下，录制没有发现你说的问题。方便提供一个测试demo 我定位下。

**Comment by ycc0207** [comment]
demo已发，请帮忙看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月26日(星期三) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 录制功能 (Issue #128)





 
@ycc0207 我在官网测试了下，录制没有发现你说的问题。方便提供一个测试demo 我定位下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bosscheng** [comment]
@ycc0207 发哪了？没找到

**Comment by ycc0207** [comment]
@bosscheng 发你邮箱了，我直接在这发你吧
[dist (2).zip](https://github.com/langhuihui/jessibuca/files/7955537/dist.2.zip)

**Comment by bosscheng** [comment]
@ycc0207 定位出问题了，正在修复。

**Comment by bosscheng** [comment]
@ycc0207 修复了

**Comment by ycc0207** [comment]
@bosscheng 但是开启useMSE为true的时候还是录制不成功

**Comment by bosscheng** [comment]
@ycc0207 我看下。

**Comment by bosscheng** [comment]
@ycc0207 试试看呢
