### ISSUE TITLE
找不到decoder.js路径

### ISSUE THREAD

**Issue by Axaxin** [langhuihui/H5RtmpClient#129]
demo的html也没有要引入decoder.js
如果decoder.js放在jessibuca.js同级目录下无法找到的话。。。 那应该要放哪里

<img width="279" alt="Snipaste_2022-01-31_08-54-25" src="https://user-images.githubusercontent.com/24554498/151725798-190468f3-6014-41ca-b253-ea344f748649.png">

<img width="442" alt="Snipaste_2022-01-31_08-52-01" src="https://user-images.githubusercontent.com/24554498/151725909-314e4cd6-2243-40b3-b8e6-d67cffe36533.png">

**Comment by bosscheng** [comment]
@Axaxin http://jessibuca.monibuca.com/api.html#decoder 看下api 文档就知道了。
