### ISSUE TITLE
H264的 CIF分辨率会出现花屏

### ISSUE THREAD

**Issue by Yordroid** [langhuihui/H5RtmpClient#13]
标准的cif分辨率是352X288，海思编码库cif分辨率是360X288,不知道是不是跟这个有关,但用其它播放器是正常的，目前只有这个分辨率出现花屏，d1,720P都正常播放，打印了解码接口的返回值也没有报错，花屏现象如下图
![QQ图片20201203231859](https://user-images.githubusercontent.com/23250077/101049094-296d0100-35be-11eb-9483-8a1e94203fe0.jpg)

**Comment by dwdcth** [comment]
我也是这个问题，分辨率是竖屏的就会出现

**Comment by langhuihui** [comment]
这个问题是ffmpeg解码有字节对齐的问题，正在解决

**Comment by langhuihui** [comment]
应该已经解决了
