### ISSUE TITLE
创建1个实例时候，偶尔出现黑屏现象；创建2个实例及以上，频繁出现黑屏现象

### ISSUE THREAD

**Issue by nanazheng** [langhuihui/H5RtmpClient#130]
视频编码格式：h264
分辨率：2304*1296
解码格式：不知道
请问是否也是需要降低视频的分辨率

**Comment by bosscheng** [comment]
试着增大缓冲区看看，因为分辨率太大了。https://jessibuca.com/api.html#videobuffer  看下设置。

或者通过降低分辨率。

**Comment by nanazheng** [comment]
好的，谢谢，我先试一下~
