### ISSUE TITLE
9宫格视频，播着播着，会有1~2个视频卡住，网速显示0kb/s，控制台报错Failed to execute 'appendBuffer' on 'SourceBuffer'

### ISSUE THREAD

**Issue by yaochen85** [langhuihui/H5RtmpClient#131]
![image](https://user-images.githubusercontent.com/16999717/152953981-20ccc3bf-1ead-4e80-a394-2c709875ad38.png)

**Comment by bosscheng** [comment]
如果是谷歌浏览器：设置->系统->使用硬件加速模式（如果可用）-->将其打开或者关闭后点击重新启动按钮

**Comment by yaochen85** [comment]
> 如果是谷歌浏览器：设置->系统->使用硬件加速模式（如果可用）-->将其打开或者关闭后点击重新启动按钮

试过了，没效果

**Comment by yaochen85** [comment]
> 如果是谷歌浏览器：设置->系统->使用硬件加速模式（如果可用）-->将其打开或者关闭后点击重新启动按钮

视频流是H264编码格式

**Comment by bosscheng** [comment]
@yaochen85 视频分辨率情况是多少的？

**Comment by yaochen85** [comment]
> @yaochen85 视频分辨率情况是多少的？

1080P

**Comment by bosscheng** [comment]
@yaochen85 1080p的九宫格，感觉带宽和解码性能跟不上，建议降低分辨率试试。

**Comment by yaochen85** [comment]
> @yaochen85 1080p的九宫格，感觉带宽和解码性能跟不上，建议降低分辨率试试。

我之前用liveplayer这个库，9宫格没这个现象。只是这个库不是开源的

**Comment by bosscheng** [comment]
@yaochen85 咨询下，你使用的什么协议播放的？ws?

**Comment by yaochen85** [comment]
> @yaochen85 咨询下，你使用的什么协议播放的？ws?

对ws-flv协议播放

**Comment by bosscheng** [comment]
@yaochen85 把你的写法发给我看下呢。我看看可能出现的问题。

**Comment by yaochen85** [comment]
> @yaochen85 把你的写法发给我看下呢。我看看可能出现的问题。

![image](https://user-images.githubusercontent.com/16999717/155461258-2c7d591f-f516-4863-bd3e-71705eb91cc9.png)
![image](https://user-images.githubusercontent.com/16999717/155461341-eefc6eeb-b2e8-4eb9-a39e-3004554ac404.png)
![image](https://user-images.githubusercontent.com/16999717/155461364-091c17d6-933e-4f58-966e-bdcb3b55bce9.png)

**Comment by bosscheng** [comment]
@yaochen85 我看写法没啥问题，试下软解码看看。就是软解码对于机器的硬件配置要求比较高。比较吃cpu。

**Comment by yaochen85** [comment]
> @yaochen85 我看写法没啥问题，试下软解码看看。就是软解码对于机器的硬件配置要求比较高。比较吃cpu。

useMSE和useWCS都设为false试过，也会卡

**Comment by bosscheng** [comment]
@yaochen85 卡的话  把videoBuffer 设置大些看看。

**Comment by yaochen85** [comment]
> @yaochen85 卡的话 把videoBuffer 设置大些看看。

设置成多大呢？

**Comment by bosscheng** [comment]
@yaochen85 尝试先看下1s, 如果还是卡顿的话，尝试2s。慢慢增加。看卡顿效果。
