### ISSUE TITLE
不同解析度的直播播放延时不同

### ISSUE THREAD

**Issue by BlackTeaLeaf** [langhuihui/H5RtmpClient#132]
直播内容、时长相同
但解析度不同
以下是视频的资料
H264 flv 

1280X720 30fps 900-1500kbps 播放延时3~5秒
720x480 20fps 40-300kbps 播放延时1秒左右

videoBuffer 均設為 0
useWCS 或 useMSE 打開 或都不開，表現都相同

资料量较大处理比较耗时可以理解
不过还是想问看看有没有方法可以处理这种问题

譬如手动增加可调整播放偏差
若资料缓冲够多的话，可以选择直接延后解码1~5秒后的资料
(最理想是两者延时都一样，同时还可以选择延后秒数解码)

**Comment by bosscheng** [comment]
@BlackTeaLeaf 方便提供测试连接给我测试看下嘛，我来看下时间消耗在哪里。

**Comment by BlackTeaLeaf** [comment]
不好意思，我们自己的连结不方便提供

取而代之
我是有再网上自行找到一个直播连结
含有GMT时间，方便对时用
wss://line1.abgvideo.net:2050/live/21tc1b0d320.flv

不过这问题是不是已经在最新的 3.0.12 解决了?
看起来耗时比之前少得多了
commit 看起来也有针对 buffer opt 做修改

**Comment by bosscheng** [comment]
@BlackTeaLeaf 确实做了些优化，我再根据你的链接定位看下。条件允许，帮忙找两个 1280X720 30fps 900-1500kbps 播放延时3~5秒
720x480 20fps 40-300kbps 播放延时1秒左右 这样的视频，我定位看下时间都消耗在哪边。
