### ISSUE TITLE
提示两个异常不影响功能，强迫症患者提一个两个错误提示

### ISSUE THREAD

**Issue by xasydxczj** [langhuihui/H5RtmpClient#134]
错误提示1：
jessibuca.js:1          GET https://aegis.qq.com/collect/whitelist?id=3ogWGfLmpllRGka9pY&uin=&version=1.35.20&aid=b1099af0-1f23-457f-8aa7-e4b15e2e46fa&env=production&platform=3&netType=4&vp=1013%20*%20969&sr=1920%20*%201080&sessionId=session-1645087969521&from=http%3A%2F%2F192.168.1.153%3A8080%2Fflvplayer%2Fflvplayer.html&referer= 403
M.window.XMLHttpRequest.window.XMLHttpRequest.send @ jessibuca.js:1

错误提示2：
VM642:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at self.onmessage (decoder.js:1:82188)
self.onmessage @ decoder.js:1

**Comment by bosscheng** [comment]
@muye-xx 已修复，谢谢。
