### ISSUE TITLE
destroy方法无法完全释放内存

### ISSUE THREAD

**Issue by baoer-coder** [langhuihui/H5RtmpClient#135]
因为业务需求是轮询查看多组视频，一开始使用play(url)和close()组合来切换视频流，可以正常切换，但是时间长了以后就内存溢出了。后来就改为每轮询一次就创建销毁一次播放器，但是时间久了以后还是会内存溢出，请问怎么完全释放播放器内存或是这种需求如何最优化配置来达到轮询不崩溃？

**Comment by bosscheng** [comment]
@xujianjie12138 方便帮忙定位下内存是哪块增加吗。chrome 浏览器，https://segmentfault.com/a/1190000039886452  然后把前后的 内存文件发给我我分析看下。

**Comment by baoer-coder** [comment]
> @xujianjie12138 方便帮忙定位下内存是哪块增加吗。chrome 浏览器，https://segmentfault.com/a/1190000039886452 然后把前后的 内存文件发给我我分析看下。

您好！已发送到您的邮箱，一个是播放中的快照，一个是关闭播放的快照。

**Comment by bosscheng** [comment]
@baoer-coder 你先试着设置hasAudio 为false 看看有没有内存溢出的问题。

**Comment by baoer-coder** [comment]
> @baoer-coder 你先试着设置hasAudio 为false 看看有没有内存溢出的问题。

好像也没用

**Comment by bosscheng** [comment]
@baoer-coder 我看代码没有发现哪边可能出现内存溢出的情况，方便的话，把写的代码发给我，我看下你咋写的。是否有优化的可能。

**Comment by baoer-coder** [comment]
> @baoer-coder 我看代码没有发现哪边可能出现内存溢出的情况，方便的话，把写的代码发给我，我看下你咋写的。是否有优化的可能。

已经发到您邮箱了

**Comment by baoer-coder** [comment]
> @baoer-coder 我看代码没有发现哪边可能出现内存溢出的情况，方便的话，把写的代码发给我，我看下你咋写的。是否有优化的可能。

发现一个很诡异的问题，使用tomcat作为容器浏览器内存会涨，node开发环境下不会涨...

**Comment by baoer-coder** [comment]
> @baoer-coder 我看代码没有发现哪边可能出现内存溢出的情况，方便的话，把写的代码发给我，我看下你咋写的。是否有优化的可能。

经测试，放到node+express服务中，16画面轮询跑了14个小时没有崩溃，chrome浏览器内存达到2G左右，destroy优化的效果还是很明显的，感谢大佬！

**Comment by messkkang** [comment]
你好，我这使用vue 一次性创建三个cavans用来播放，页面切换时使用vue生命周期beforedestroy进行销毁，同样的另外一个页面也是，来回切换以后浏览器就出现卡顿，应该是资源满了，请问这样如何销毁
