### ISSUE TITLE
关于截图的问题

### ISSUE THREAD

**Issue by nanazheng** [langhuihui/H5RtmpClient#136]
demo 代码用了 https://github.com/bosscheng/jessibuca-react-demo
使用 screenshot 方法，type 无论是 download 或者 base64 或者 blob，都是截图后下载文件。

**Comment by bosscheng** [comment]
@nanazheng 看了下，应该是引入的jessibuca版本太低导致的。最新的jessibuca 版本我已经更新上去了。
