### ISSUE TITLE
多个iframe一起播放视频，如果有一个视频地址播放不了会导致其他地址也无法播放

### ISSUE THREAD

**Issue by dreamlandfeeling** [langhuihui/H5RtmpClient#141]
多个iframe一起播放视频，如果有一个视频地址播放不了会导致其他地址也无法播放。
试过如果不同时开始播放倒还可以播放其他的视频

**Comment by bosscheng** [comment]
@dreamlandfeeling 貌似是的，m7s ui 里面 我也是settimeout 0去渲染的。或者建议你用Promise.resolve的形式去播放。
