### ISSUE TITLE
OffscreenCanvas这个特性需要特殊的环境和硬件支持吗

### ISSUE THREAD

**Issue by Haoxw** [langhuihui/H5RtmpClient#142]
OffscreenCanvas这个特性需要特殊的环境和硬件支持吗？默认就是开发的吗？需要配置什么参数吗？
谢谢！

**Comment by bosscheng** [comment]
默认是关闭的. 如果开启需要设置 forceNoOffscreen 为 false 就可以了。
各个浏览器对于OffscreenCanvas支持程度。
<img width="1349" alt="WX20220305-204855@2x" src="https://user-images.githubusercontent.com/2195154/156883818-a4f6bc74-1799-4f39-a505-aa08932d7f7e.png">

可以看下api情况
http://jessibuca.monibuca.com/api.html#forcenooffscreen
