### ISSUE TITLE
Jessibuca need container option

### ISSUE THREAD

**Issue by chenparty** [langhuihui/H5RtmpClient#144]
我初始化播放器时，container传的div的id字符串，但是报错了，提示：Jessibuca need container option

**Comment by bosscheng** [comment]
@chenparty 代码如何写的，贴下呢

**Comment by chenparty** [comment]
![image](https://user-images.githubusercontent.com/16755257/157410869-b38df180-dd9b-4739-a136-6fcf65712fc4.png)
@bosscheng 您看看呢

**Comment by bosscheng** [comment]
@chenparty 在 onMounted(() => {
      console.log('mounted!')
    })  方法里面初始化jessibuca。

**Comment by chenparty** [comment]
![image](https://user-images.githubusercontent.com/16755257/157604839-97f51ad0-1fd4-46b6-9881-cbd3f107d94d.png)
按照您说的加了，从新编译刷新后，但是产生一样的错误。

**Comment by bosscheng** [comment]
@chenparty 看下https://github.com/bosscheng/jessibuca-vue-demo/tree/v3 吧。

**Comment by chenparty** [comment]
@bosscheng 感谢，其实这个已经看过了，但是不是vue3.0+ts的，如果大佬有时间，能出一个vue3.0+ts版本的demo是最令人激动
的。

**Comment by bosscheng** [comment]
@chenparty https://github.com/bosscheng/jessibuca-vue-ts-demo
