### ISSUE TITLE
引用的最新版本dist内文件，我这么import的，会报错

### ISSUE THREAD

**Issue by chenparty** [langhuihui/H5RtmpClient#145]
![image](https://user-images.githubusercontent.com/16755257/157808645-987c7a75-6529-4711-adab-ecf3cfffd72d.png)

![image](https://user-images.githubusercontent.com/16755257/157808624-abec7b5b-c2c4-45e0-aaad-4488494993bf.png)

_Originally posted by @chenparty in https://github.com/langhuihui/jessibuca/issues/137#issuecomment-1064789482_

**Comment by bosscheng** [comment]
@chenparty https://jessibuca.com/demo.html#h5-mobile
