### ISSUE TITLE
webcodecs在Chrome上播放h264出现跳帧

### ISSUE THREAD

**Issue by Se7enQ** [langhuihui/H5RtmpClient#146]
VideoDecoder的output在同一时间点会同时输出5帧左右的videoFrame，会导致视频每一秒都会跳5帧左右，请问有没有办法解决？

**Comment by bosscheng** [comment]
@Se7enQ 有测试地址嘛 我看下。

**Comment by kubbo** [comment]
> VideoDecoder的output在同一时间点会同时输出5帧左右的videoFrame，会导致视频每一秒都会跳5帧左右，请问有没有办法解决？

遇到同样问题，请问解决没？

**Comment by bosscheng** [comment]
给个测试地址，我好复现下啥问题
