### ISSUE TITLE
实时流会停掉

### ISSUE THREAD

**Issue by syf2634179** [langhuihui/H5RtmpClient#147]
流地址: https://media.traefik.99rongle.com/hdl/200001125.flv

网址: https://player.traefik.99rongle.com/#/pass/realjessPreview

大佬 我用最新的做的 发现画面一秒 然后就定在那了,  获取流过几秒就会停止获取了

**Comment by syf2634179** [comment]
http://jessibuca.monibuca.com/player.html 我在这个网址上测 也是一样 会停住,多试几次 偶尔出现一次 正常播放的

**Comment by syf2634179** [comment]
https://media.traefik.99rongle.com/hdl/200004928.flv 流地址

**Comment by syf2634179** [comment]
https://player.traefik.99rongle.com/#/pass/realpreview  这个是  用的 flv.js  没出现这种问题

**Comment by bosscheng** [comment]
@syf2634179 流地址不通。

**Comment by syf2634179** [comment]
@bosscheng   https://player.traefik.99rongle.com/#/pass/realjessPreview 可以在这里拿流 , 会出现前几秒正常,  然后流就停止了, 现在做了4秒没流会重新获取, 第二次后就没问题 流正常获取了

**Comment by syf2634179** [comment]
@bosscheng  我使用的是谷歌浏览器

**Comment by bosscheng** [comment]
@syf2634179 
<img width="632" alt="image" src="https://user-images.githubusercontent.com/2195154/158923351-0751db8e-2ae6-47df-ab08-849944ee9332.png">
我测试了下，发现在设置videoBuffer为0.2s的时候流获取会出现间断。导致视频出现卡主的情况。改成2s 之后，会有所好转。

还有一个问题，
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/2195154/158923752-417a2d81-8713-4812-aad4-74cbf34785e5.png">
这个你得修复下
<img width="414" alt="image" src="https://user-images.githubusercontent.com/2195154/158923824-f5d60e62-88b6-417e-95a9-50d8944713e6.png">
这个是你服务器返回的。
<img width="444" alt="image" src="https://user-images.githubusercontent.com/2195154/158923872-b7415476-011a-4994-a8f7-7f2228d58e6c.png">
要改成这样的。

**Comment by syf2634179** [comment]
@bosscheng  好的 大佬  我试试

**Comment by syf2634179** [comment]
大佬,
1. 文档里的   heartTimeout 这个是不是写错了  ,  http://jessibuca.monibuca.com/api.html#debug
![图片](https://user-images.githubusercontent.com/32382657/158936765-2187f012-4026-428f-bd04-d0e5b6198db7.png)


3.我看到 去拿流 好像是4秒获取一次的吗?  这个时间能改吗 比如0.5秒 ,1秒.
![图片](https://user-images.githubusercontent.com/32382657/158936798-205e1c19-7d98-48d8-bec1-c08cb0939f9a.png)

**Comment by bosscheng** [comment]
@syf2634179 3.我看到 去拿流 好像是4秒获取一次的吗? 这个时间能改吗 比如0.5秒 ,1秒. 这句话没看懂。

**Comment by syf2634179** [comment]
@bosscheng   获取流地址后  调play   先loading 有个转圈ui  转圈消失后  还会有一段时间黑屏   我现在设置缓存5秒  不会出现卡住现象了  但 开始有段时间黑屏

**Comment by bosscheng** [comment]
@syf2634179 理论上不会出现黑屏情况，我是先拿到i帧去解码，然后就播放了。然后后面的数据进行缓存。这段时间内是不播放解码出来的视频数据的。你试下监听http://jessibuca.monibuca.com/api.html#playtorendertimes 看下首屏消耗的时间呢。

**Comment by syf2634179** [comment]
@bosscheng 
![图片](https://user-images.githubusercontent.com/32382657/158976143-7e975d32-e9d0-4d6b-b13c-12d6497e0f19.png)
监听出来了,但画面 是这个log出来后 等了4秒左右  画面 才出来的

**Comment by bosscheng** [comment]
@syf2634179 方便给我个测试连接嘛，我本地联调看下。

**Comment by syf2634179** [comment]
@bosscheng  是 flv 地址吗

**Comment by syf2634179** [comment]
@bosscheng  https://player.traefik.99rongle.com/#/pass/realjessPreview 这是 测试地址

**Comment by syf2634179** [comment]
@bosscheng  设置2秒缓存 就是2秒的黑屏, 3秒就会有3秒黑屏

**Comment by bosscheng** [comment]
@syf2634179 我知道了 useMSE 和useWCS 下面会有黑屏，软解的话就不会黑屏。

**Comment by syf2634179** [comment]
@bosscheng  
![图片](https://user-images.githubusercontent.com/32382657/158990110-ea289458-68e0-4273-9e8b-860005ceb8e0.png)
是指这2个吗

**Comment by bosscheng** [comment]
@syf2634179 是的 你可以看下https://jessibuca.com/api.html#usemse api 的说明

**Comment by syf2634179** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 晚上9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 实时流会停掉 (Issue #147)





 
@syf2634179 是的 你可以看下https://jessibuca.com/api.html#usemse api 的说明
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by syf2634179** [comment]
大佬,
1. 文档里的&nbsp; &nbsp;heartTimeout 这个是不是写错了&nbsp; ,&nbsp; http://jessibuca.monibuca.com/api.html#debug


2.我看到 去拿流 好像是4秒获取一次的吗?&nbsp; 这个时间能改吗 比如0.5秒 ,1秒.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 实时流会停掉 (Issue #147)





 
@syf2634179
 
 我测试了下，发现在设置videoBuffer为0.2s的时候流获取会出现间断。导致视频出现卡主的情况。改成2s 之后，会有所好转。
 
还有一个问题，
 
 这个你得修复下
 
 这个是你服务器返回的。
 
 要改成这样的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bosscheng** [comment]
@syf2634179 没理解你的意思
