### ISSUE TITLE
浏览器 切换回来 会出现花屏

### ISSUE THREAD

**Issue by syf2634179** [langhuihui/H5RtmpClient#148]
![图片](https://user-images.githubusercontent.com/32382657/159239945-52a4224a-68ed-451a-9f38-1e80ffb0dd68.png)

大佬 请看下, 我用flv.js  不会出现

**Comment by syf2634179** [comment]
@bosscheng   切换几次 屏幕画面 还会停止, 有时时间错乱显示 过几秒 才能正常

**Comment by syf2634179** [comment]
@bosscheng  
this.flvPlayer.player.video.$videoElement.currentTime = this.flvPlayer.player.video.$videoElement.buffered.end(0) - 0.01;  我用这种方式  发现不行, 不知道 video 方式 播放 是怎么加载数据的 
![图片](https://user-images.githubusercontent.com/32382657/159243761-7ab3dfde-d7e5-427c-a037-adb269f1e3df.png)

**Comment by bosscheng** [comment]
@syf2634179 可以试下wasm 模式下面，暂不会出现花屏情况。MSE模式我也复现了，我修复好了和你讲。

**Comment by bosscheng** [comment]
@syf2634179 试下最新版本看下。问题应该已经修复了。

**Comment by syf2634179** [comment]
好的～　　感谢　大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 浏览器 切换回来 会出现花屏 (Issue #148)





 
Closed #148.

**Comment by syf2634179** [comment]
大佬&nbsp; 发现20分钟以上&nbsp; 再切换过去的话,流量小的&nbsp; 还会绿屏一下 时间很短比以前好很多了, 短时间 切换没问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 晚上11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 浏览器 切换回来 会出现花屏 (Issue #148)





 
Closed #148.

**Comment by bosscheng** [comment]
@syf2634179 好的，我持续再关注优化吧，等后续再优化了和你讲。
