### ISSUE TITLE
vue上使用四分屏卡死浏览器，cpu和内存也都还有空

### ISSUE THREAD

**Issue by zhangshengqi** [langhuihui/H5RtmpClient#150]
![Uploading 1648267136(1).png…]()

**Comment by zhangshengqi** [comment]
- 
![1648267136(1)](https://user-images.githubusercontent.com/31626773/160224037-6b2c0d3b-3cd0-4e3b-8778-1ef4aa860782.png)

**Comment by bosscheng** [comment]
@zhangshengqi http://jessibuca.monibuca.com/document.html#%E5%88%9B%E5%BB%BA%E5%A4%9A%E4%B8%AA%E4%BB%A5%E4%B8%8A%E6%92%AD%E6%94%BE%E5%AE%9E%E4%BE%8B%E4%BC%9A%E9%9D%9E%E5%B8%B8%E5%8D%A1%E9%A1%BF%EF%BC%8C%E8%BF%98%E4%BC%9A%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E9%BB%91%E5%B1%8F

**Comment by zhangshengqi** [comment]
同样的参数配置，html版本就可以，vue版本就不行

**Comment by bosscheng** [comment]
@zhangshengqi 代码贴下呢

**Comment by zhangshengqi** [comment]
![1648442653(1)](https://user-images.githubusercontent.com/31626773/160327973-bc93b51c-04c8-4be6-9399-0ddee880f30e.jpg)

**Comment by bosscheng** [comment]
@zhangshengqi 试下把jessibuca不要绑定在this 上面，绑定在this.$options.jessibuca 这样。
