### ISSUE TITLE
搜狗浏览器报错

### ISSUE THREAD

**Issue by 1914k** [langhuihui/H5RtmpClient#151]
有的版本的搜狗浏览器会报下面的错误，是浏览器版本问题吗？
Cannot read property 'createShader' of null

**Comment by bosscheng** [comment]
@1914k 应该是搜狗浏览器webgl 有问题，建议换成chrome 浏览器。

**Comment by 1914k** [comment]
谢谢，更换浏览器后问题解决了，播放 16 路视频时，我本地播放时不会卡和黑屏，但是别的电脑播放会卡或者黑屏。我本地是win10 /  16G，会卡的是 win7 / 8G，请教一下是我代码的问题还是硬件问题？
[index.txt](https://github.com/langhuihui/jessibuca/files/8387283/index.txt)

**Comment by bosscheng** [comment]
硬件问题。8G 播放16路 还是吃不消的。要不然就降低分辨率。要不然就提升下硬件配置。

**Comment by bosscheng** [comment]
@1914k

**Comment by 1914k** [comment]
ok，谢谢你了
