### ISSUE TITLE
How to build project on Windows

### ISSUE THREAD

**Issue by pubpy2015** [langhuihui/H5RtmpClient#153]
Hi,

I am clone your project by using command:

// clone jessibuca
git clone https://github.com/langhuihui/jessibuca.git
// clone ffmpeg
cd jessibuca
git submodule update --init

and clone Emscripten

git clone https://github.com/emscripten-core/emsdk.git
cd emsdk
git pull
emsdk install latest
emsdk activate latest

and build:

npm run build => ok
![ảnh](https://user-images.githubusercontent.com/59004953/161250181-db9cc970-5991-43e8-b5d8-f847a7f528c5.png)

**npm run build:wasm => failed!**

![ảnh](https://user-images.githubusercontent.com/59004953/161250510-1af7f8b6-2749-49d8-a450-ec84d9047703.png)

Please help me to solve this problem.

**Comment by bosscheng** [comment]
Hi, you can  cd  ./wasm dir and then exec  'python wasm/make.py --wasm'
