### ISSUE TITLE
我的开源项目目前使用您的播放器作为28181的WEB播放器，想邀请您一起参与。

### ISSUE THREAD

**Issue by 648540858** [langhuihui/H5RtmpClient#155]
这是我的项目[https://github.com/648540858/wvp-GB28181-pro](https://github.com/648540858/wvp-GB28181-pro),您有兴趣一起接收这些bug反馈的话，麻烦给我个联系方式。这是我的邮箱648540858@qq.com, 也是我的qq号。因为遇到的比较多，小白也比较多不知道来这里反馈，所以想邀请您一起参与进来。

**Comment by langhuihui** [comment]
👌🏻，我的微信：yigehui

**Comment by 648540858** [comment]
我加您
