### ISSUE TITLE
在播放过程中更改缓冲时间无效

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#156]
![image](https://user-images.githubusercontent.com/23475171/163123709-d08e94e3-15b9-4714-af3e-9701890668a2.png)
![image](https://user-images.githubusercontent.com/23475171/163124630-1861f2ea-8544-4625-a4a3-5e8bce073a20.png)
![image](https://user-images.githubusercontent.com/23475171/163124721-f5d970ab-5ef4-43e4-b7a3-a02814662a38.png)

**Comment by bosscheng** [comment]
@DaikonX 我看下。

**Comment by bosscheng** [comment]
@DaikonX 已经修复了。
