### ISSUE TITLE
修改播放器控制条，类似于video标签控制条悬浮，个人修改给出方法望参考

### ISSUE THREAD

**Issue by xasydxczj** [langhuihui/H5RtmpClient#158]
1.外部调用方法不变
 player = new Jessibuca({
                            decoder: 'decoder.js',
                            container: VideoElement,
                            loadingText: "loading...",
                            timeout: 5,
                            supportDblclickFullscreen: true,
                            showBandwidth: true,
                            operateBtns: {
                                audio: true,
                                fullscreen: true,
                                play: true
                            }
                        });

2.默认不显示工具条
修改文件src\control\style.scss    在181行开始修改control样式
给jessibuca-controls-show添加display: none默认不显示，opacity: 0.8 半透明

   &.jessibuca-controls-show {
        .jessibuca-controls {
            opacity: 0.8;
            visibility: visible;
            display: none;
        }
    }

3.修改文件src\control\events.js  在33行开始添加鼠标消息， 让控制条鼠标滑入播放器显示，滑出隐藏，注意全屏时隐藏控制条

 proxy(player.$container, 'mouseover', () => { 
        if(!player.fullscreen){
            setStyle(control.$controls, 'display', 'block');
        }
    })

    proxy(player.$container, 'mouseout', () => {
        setStyle(control.$controls, 'display', 'none');
    })

    proxy(player.$container, 'dblclick', () => {
        if(player.fullscreen){
            setStyle(control.$controls, 'display', 'block');
        }
        else{ 
            setStyle(control.$controls, 'display', 'none');
        }
    })

4.工具条应该是悬浮在视频画面之上，工具条不能影响视屏画面的区域。

修改文件src\video\canvasLoader.js 中的 resize() 函数184行，删除掉//height -= CONTROL_HEIGHT;
 resize() {
        this.player.debug.log('canvasVideo', 'resize');
        const option = this.player._opt;
        const width = this.player.width;
        let height = this.player.height;
        if (option.hasControl) {
            //height -= CONTROL_HEIGHT;
        }
        let resizeWidth = this.$videoElement.width;
        let resizeHeight = this.$videoElement.height;

修改文件src\video\videoLoader.js，中的 resize() 函数104行，修改为this.$videoElement.height = this.player.height;
 resize() {
        this.$videoElement.width = this.player.width;
        this.$videoElement.height = this.player.height;//this.player._opt.hasControl ? this.player.height - CONTROL_HEIGHT : this.player.height;
        const option = this.player._opt;
        let objectFill = 'contain';
        const rotate = option.rotate;

做过以上的修改之后播放器的控制条，在鼠标滑入播放器区域时悬浮显示。

**Comment by DaikonX** [comment]
控制条我都是用自己写的  每个人用的控制条内容不一样吧

**Comment by bosscheng** [comment]
@muye-xx 挺好的，可以考虑添加一个配置项。

**Comment by bosscheng** [comment]
@DaikonX 是的，基本业务上面都会用自己的控制条。
