### ISSUE TITLE
录像下载 mp4 后发现不能拖动 时间,快速播放,不像是正常的mp4文件

### ISSUE THREAD

**Issue by syf2634179** [langhuihui/H5RtmpClient#159]

**Comment by syf2634179** [comment]
@bosscheng  大佬 请看下 
![图片](https://user-images.githubusercontent.com/32382657/163748711-33b586ea-f79c-4c6d-8b74-03f8fa78edaa.png)
浏览器播放不出来

**Comment by bosscheng** [comment]
@syf2634179 
支持录制MP4和WebM格式(video/webm;codecs=h264)的视频录制。(基于MediaRecorder),(MP4格式支持在IOS VLC播放器显示时长播放，Android VLC播放器无法显示时长播放，PC VLC播放器可以播放)。 

支持视频录制 - 开发中
- 支持录制MP4格式(MPEG-4)的视频录制。

**Comment by bosscheng** [comment]
@syf2634179  https://github.com/langhuihui/jessibuca/issues/126 可以再看下这个issue。

或者看下这个 https://jessibuca.com/document.html#%E5%B0%86%E5%BD%95%E5%88%B6%E7%9A%84%E8%A7%86%E9%A2%91%E4%BF%9D%E5%AD%98%E5%9C%A8%E5%AE%89%E5%8D%93%E6%89%8B%E6%9C%BA%E7%9B%B8%E5%86%8C%E4%B8%AD%EF%BC%8C%E6%98%BE%E7%A4%BA%E7%9A%84%E6%97%B6%E9%95%BF%E4%B8%BA0%EF%BC%8C%E5%B9%B6%E4%B8%94%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE%E3%80%82
