### ISSUE TITLE
播放器使用了useMSE后isFullResize在小框显示时无法缩放图像

### ISSUE THREAD

**Issue by CJA123** [langhuihui/H5RtmpClient#161]

**Comment by CJA123** [comment]
![image](https://user-images.githubusercontent.com/24954402/164202459-b1e4baf0-3b00-4833-96db-9d219339bcc4.png)

**Comment by CJA123** [comment]
![image](https://user-images.githubusercontent.com/24954402/164202610-91d8bb63-c806-4003-9765-a5d536650724.png)

**Comment by bosscheng** [comment]
@CJA123  当为true的时候：视频画面做等比缩放后,完全填充canvas区域,画面不被拉伸,没有黑边,但画面显示不全。等同于 setScaleMode(2)  

可以看下：http://jessibuca.monibuca.com/api.html#isresize

这个参数是历史遗留参数，建议使用 http://jessibuca.monibuca.com/api.html#setscalemode-mode 这个来设置显示效果。

**Comment by CJA123** [comment]
但是当我useMSE不为true的时候缩放的比例会正常许多，但是就是调式器一直抛警告
![image](https://user-images.githubusercontent.com/24954402/164361278-d7c95c15-fca5-41a1-8166-df5d97f79e74.png)
![image](https://user-images.githubusercontent.com/24954402/164361367-943110dc-2a98-4299-97a5-093425f1faa5.png)

**Comment by bosscheng** [comment]
@CJA123 这个不需要管，只是日志而已。
