### ISSUE TITLE
用v2版本的，怎么阻止截图下载，并把截图传给后端？

### ISSUE THREAD

**Issue by jiaoluolidexingxing** [langhuihui/H5RtmpClient#162]

**Comment by bosscheng** [comment]
@jiaoluolidexingxing  http://jessibuca.monibuca.com/api.html#screenshot-filename-format-quality-type 看下  

type: 可选参数, 可选download或者base64或者blob，默认download


ps: v2 和v3 没啥区别，api 都支持的，建议升级到v3上面。因为v2 已经不维护了。
