### ISSUE TITLE
265的flv流 缓冲

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#163]
265的流设置缓冲时长后 发现缓冲时长好像没成功。  用监听事件回调出来的缓冲时间也不是目标值的范围  一会大一会小 。播着播着 和RTSP相比就晚了一些时间

**Comment by bosscheng** [comment]
@DaikonX 代码贴下呢

**Comment by DaikonX** [comment]
![image](https://user-images.githubusercontent.com/23475171/164439534-111bd978-92c1-4cc9-8d22-aabafc1967ca.png)
![image](https://user-images.githubusercontent.com/23475171/164439568-d334e9a8-8f31-41a6-a662-694ba1222b52.png)
![image](https://user-images.githubusercontent.com/23475171/164439827-ebf65ff7-09d8-41d9-a3cb-81c71afa35a1.png)
![image](https://user-images.githubusercontent.com/23475171/164439974-4219d233-408a-491d-83b7-96b80ac8b4a8.png)
 就简单的使用一下  就刚一开始 和RTSP是同步的  然后慢慢就延迟越来越多 设置缓冲时间没用  在265的流有问题

**Comment by bosscheng** [comment]
@DaikonX 确认下，是最新版本的嘛。之前setBufferTime方法确实是有问题的。

**Comment by DaikonX** [comment]
是的  我用了最新的 264是正常的

**Comment by bosscheng** [comment]
@DaikonX 给我一个h265的源测试看下呢

**Comment by DaikonX** [comment]
估计是流的问题  先关了
