### ISSUE TITLE
使用硬解码后可以播放9路但是出现卡屏问题

### ISSUE THREAD

**Issue by liumingxin798** [langhuihui/H5RtmpClient#164]
再播放9路直播时， 段时间后，其中会有几个视频卡住，但是流量一直再走，部分也无法重新播放，查看cpu和gpu 都还可以

**Comment by liumingxin798** [comment]
![image](https://user-images.githubusercontent.com/18522173/164421112-1507c39b-5a32-43fd-9f5e-cd9db1ced95a.png)

作者你好这是我的配置，请问有什么问题吗

**Comment by bosscheng** [comment]
@liumingxin798 视频的分辨率是多少、

**Comment by liumingxin798** [comment]
> @liumingxin798 视频的分辨率是多少、

有720p 和1080p

**Comment by liumingxin798** [comment]
> @liumingxin798 视频的分辨率是多少、

如果用软解最多可以播放5路，不卡，  超过浏览器会崩溃，我按照文档，仔细查看了配置，将配置调整成图中情况，可以播放9路不卡，但是放置一段时间后就会出现上述情况

**Comment by bosscheng** [comment]
@liumingxin798 你试下webcodecs 看看呢，有没有问题。

**Comment by liumingxin798** [comment]
> webcodecs
作者你好，我这边使用了useWCS = true  应该已经开启了webcodecs吧

我看到文档中是这么说的

useWCS
类型：boolean
默认值：false
用法： 是否开启Webcodecs硬解码

**Comment by bosscheng** [comment]
@liumingxin798 是的。试下这个硬解码有没有问题。

**Comment by liumingxin798** [comment]
> @liumingxin798 是的。试下这个硬解码有没有问题。

😓我一直都是开着的，你看我的配置文件，上面是true

**Comment by liumingxin798** [comment]
> @liumingxin798 是的。试下这个硬解码有没有问题。

😓我一直都是开着的，你看我的配置文件，上面是true

**Comment by bosscheng** [comment]
@liumingxin798 哈哈，你用的是useMSE:true  改成 useWCS:true 试试。

**Comment by bosscheng** [comment]
@liumingxin798 试下最新版本看下。

**Comment by liumingxin798** [comment]
> @liumingxin798 哈哈，你用的是useMSE:true 改成 useWCS:true 试试。

尴尬，是我看错了，我先去尝试一下useWCS 硬解试一试，还不行再去试试最新版，这边是VUE2，都尝试过再前来反馈，感谢作者

**Comment by liumingxin798** [comment]
> @liumingxin798 试下最新版本看下。
试验后发现  （使用谷歌浏览器-任务管理器查看）
使用useMSE: true   开启9路cpu 在100%内（当前使用版本）
使用useWCS:true   开启9路cpu 在300%多，视频发生卡顿。

目前使用的播放器版本-应该也是从vue2demo中取出的
<img width="332" alt="image" src="https://user-images.githubusercontent.com/18522173/164576735-c264feeb-f423-4b37-8557-21fe0061cc99.png">
请问最新版指的是图中的VUE2连接中的吗
<img width="667" alt="image" src="https://user-images.githubusercontent.com/18522173/164576761-7f048318-8c94-4881-9525-2c2b21702b18.png">

**Comment by bosscheng** [comment]
@liumingxin798 不是，这个版本太老了。最新版本就是项目组中的 dist 目录下面。或者直接下载 [2022-4-21 v3.0.23](https://github.com/langhuihui/jessibuca/releases/tag/v3.0.23) 里面、

**Comment by liumingxin798** [comment]
> @liumingxin798 不是，这个版本太老了。最新版本就是项目组中的 dist 目录下面。或者直接下载 [2022-4-21 v3.0.23](https://github.com/langhuihui/jessibuca/releases/tag/v3.0.23) 里面、

好的十分感谢，我去尝试

**Comment by liumingxin798** [comment]
-对于该问题的最后一次上报结果，目前使用最新版，当播放9路无问题， 
-段时间后，其中几路会暂停，目前排查可能是网速问题，应该与播放器无关
-点击播放按钮没有相应，判断应为没有调起拉流，这可能跟点播接口有关
-理论上实验成功，播放器成功播放9路。

**Comment by bosscheng** [comment]
@liumingxin798 nice
