### ISSUE TITLE
H265 flv流播放卡顿

### ISSUE THREAD

**Issue by aidansn** [langhuihui/H5RtmpClient#167]
播放1080P@30fps H265，解码很吃力，但是看到电脑的CPU的占用率只有20%左右。解码对性能做了限制吗？

**Comment by bosscheng** [comment]
增加 videobuffer  http://jessibuca.monibuca.com/api.html#videobuffer 大小看看。

**Comment by aidansn** [comment]
增加 videobuffer 会增大视频延时，而且效果也没有改善。我用360P@30FPS的H265流，就非常流畅，每秒能解30fps。不能理解的是360P和1080P的流，CPU占用率相同

**Comment by bosscheng** [comment]
@aidansn 分析了下，大概率是因为单线程解码的缘故，一个cpu核已经跑满了。后面尝试用ffmpeg编译成多线程的wasm 来解码提升性能。

**Comment by iwestlin** [comment]
有进展吗🥺

**Comment by bosscheng** [comment]
@iwestlin 可以看下 https://jessibuca.com/player-pro.html， 目前已经支持了 265的软解码/硬解码了。
