### ISSUE TITLE
GPL3.0协议开源，所以用了你的这个播放器的整个平台都必须开源，是吗？

### ISSUE THREAD

**Issue by worldflyingct** [langhuihui/H5RtmpClient#168]
GPL3.0是说只要用了你的播放器，我们整个安防平台都必须开源，否则就违法了是吗？？？只使用，不修改源码也不行对吧。

**Comment by langhuihui** [comment]
GPL3.0的话是如果你在本软件基础上二次开发的软件也必须开源，并不是说你用了的话其他东西也都要开源啊。

**Comment by worldflyingct** [comment]
> GPL3.0的话是如果你在本软件基础上二次开发的软件也必须开源，并不是说你用了的话其他东西也都要开源啊。

你说的这个在网上描述是有争议的，只用不改能不开源最好是lgpl协议，这样就没有争议了，目前真心不敢用gpl3.0的软件。

**Comment by langhuihui** [comment]
以前是闭源的，开源的时候考虑的不是很全面，后面准备修改一下开源协议，多谢你的建议。

**Comment by worldflyingct** [comment]
> 以前是闭源的，开源的时候考虑的不是很全面，后面准备修改一下开源协议，多谢你的建议。

感谢您的回复，等哪一天改了开源协议告知一声，那是直播界大喜事啊。

**Comment by langhuihui** [comment]
有那么夸张吗？
