### ISSUE TITLE
vue-cli2 报错 SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by wangzhe11** [langhuihui/H5RtmpClient#172]
请问，我把vue-cli3中放在public下面的jessibuca.js、decoder.js、decoder.wasm放在vue-cli2中static目录下面，页面上出现 SyntaxError: Unexpected token u in JSON at position 0这个报错。是不支持vue-cli2吗？请问有demo吗？

**Comment by bosscheng** [comment]
https://jessibuca.com/demo.html @wangzhe11
