### ISSUE TITLE
录制视频后，如何获取到Blob，进行过保存到本地，是否提供了类似的方法？

### ISSUE THREAD

**Issue by whliuzhengyi** [langhuihui/H5RtmpClient#173]
类似于截图：      
const fileBlob = this.jessibuca.screenshot("test", 'blob')

视频录制结束后，是否可以获取到视频的二进制文件

**Comment by bosscheng** [comment]
@whliuzhengyi  http://jessibuca.monibuca.com/api.html#stoprecordandsave  看下这个方法
