### ISSUE TITLE
h265 的 mkv 和 mp4 无法播放

### ISSUE THREAD

**Issue by aelvet** [langhuihui/H5RtmpClient#174]
测试链接为：

https://vkceyugu.cdn.bspapp.com/VKCEYUGU-340a36ac-463c-401b-8025-1094936d66f9/0915f23a-dfc7-4a8b-8a5c-be9e685dabbb.mp4

https://vkceyugu.cdn.bspapp.com/VKCEYUGU-340a36ac-463c-401b-8025-1094936d66f9/93ceb18d-0829-4192-bdad-5e36f0f291ab.mkv

这个链接地址，我用 potplayer 可以正常播放

**Comment by bosscheng** [comment]
jessibuca是直播播放器，暂不支持点播。
