### ISSUE TITLE
more than 6 flvs' play; can you write a demo?

### ISSUE THREAD

**Issue by lik3yoo** [langhuihui/H5RtmpClient#175]
as you say, the method 2. is ok to play more than 6 flvs, but  h2 is not universal; can you given a websocket accomplish  method? thanks.

**Comment by lik3yoo** [comment]
能否给一个websocket实现凡是的demo

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/demo.html#wasm-worker-9%E7%94%BB%E9%9D%A2 @iixm

**Comment by lik3yoo** [comment]
这个demo可以同事播放6个以上同源的flv吗？

**Comment by bosscheng** [comment]
ws协议可以。http 不支持。

**Comment by bosscheng** [comment]
@iixm
