### ISSUE TITLE
如果网速很慢  画面 过一段时间后就会卡住不动了 

### ISSUE THREAD

**Issue by syf2634179** [langhuihui/H5RtmpClient#176]
![图片](https://user-images.githubusercontent.com/32382657/168477553-3d740608-a419-4f08-8a4a-9e751e8a947a.png)

**Comment by syf2634179** [comment]
@bosscheng  大佬 我又来提问题了

**Comment by bosscheng** [comment]
@syf2634179 看下控制台，有没有报错信息。看下是不是触发了http://jessibuca.monibuca.com/api.html#hearttimeout 超时。

**Comment by syf2634179** [comment]
![图片](https://user-images.githubusercontent.com/32382657/168509085-e2f26d39-f409-4913-b193-e7cb54b5a78c.png)
@bosscheng

**Comment by syf2634179** [comment]
![图片](https://user-images.githubusercontent.com/32382657/168509894-a52eafc6-20e2-4341-9f24-1ce45b6a367a.png)
@bosscheng   就一直这样 了 画面,也没什么报错

**Comment by syf2634179** [comment]
http://ddns.99rongle.com:9011/hdl/200003278.flv 这个是流地址

**Comment by bosscheng** [comment]
> http://ddns.99rongle.com:9011/hdl/200003278.flv 这个是流地址

@syf2634179 地址播放不起来。

**Comment by syf2634179** [comment]
http://ddns.99rongle.com:9011/hdl/200004956.flv  地址变了哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





  
http://ddns.99rongle.com:9011/hdl/200003278.flv 这个是流地址
  
@syf2634179 地址播放不起来。

**Comment by bosscheng** [comment]
<img width="621" alt="WX20220516-221256@2@syf2634179 " src="https://user-images.githubusercontent.com/2195154/168612754-5f8e6e5e-97f9-41c9-9d45-13f0d6b96aa3.png">
@syf2634179  我播放着看没问题嘛，确认下，你的总带宽都不够。

**Comment by syf2634179** [comment]
就是画面会卡住, 你那边没有卡住不动吗?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 

 @syf2634179  我播放着看没问题嘛，确认下，你的总带宽都不够。

**Comment by bosscheng** [comment]
@syf2634179 你看下stats 里面的fps 是多少？如果卡住了，那就是fps为0 了。

**Comment by syf2634179** [comment]
好的&nbsp; 我看看 如果是0了 重新播放下吗?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 上午9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 
@syf2634179 你看下stats 里面的fps 是多少？如果卡住了，那就是fps为0 了。

**Comment by bosscheng** [comment]
@syf2634179 你可以看下 http://jessibuca.monibuca.com/api.html#hearttimeoutreplay  这个api。

**Comment by syf2634179** [comment]
大佬&nbsp; fps不为0, 数据都正常的,&nbsp; 发现 画面其实是动的 只是 时分秒 那里&nbsp; 分 秒 没有覆盖掉上一秒的,重新播放下 就好了.


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 上午9:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 
@syf2634179 你看下stats 里面的fps 是多少？如果卡住了，那就是fps为0 了。

**Comment by syf2634179** [comment]
好的&nbsp; 我加下 试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月17日(星期二) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 
@syf2634179 你可以看下 http://jessibuca.monibuca.com/api.html#hearttimeoutreplay  这个api。

**Comment by bosscheng** [comment]
那就神奇了，播放器接收到的流数据就是那样的。那就是服务器端的问题了。

**Comment by syf2634179** [comment]
嗯,住要还是这个流的网速不稳定&nbsp; 时长低于5KB/S ,另一路 大于100KB/S的就没什么问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 
那就神奇了，播放器接收到的流数据就是那样的。那就是服务器端的问题了。

**Comment by bosscheng** [comment]
把问题甩给服务器端。哈哈

**Comment by syf2634179** [comment]
那个是摄像头的带宽&nbsp; 服务端 也没办法






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 
把问题甩给服务器端。哈哈

**Comment by syf2634179** [comment]
大佬 有没有设置 缓存多少数据&nbsp; 超过了就会清除掉之前的内存之类的, 我现在实时播放&nbsp; 半天&nbsp; 大概有好几个G的缓存,&nbsp; 浏览器 就卡住不播放了.&nbsp;

目前只是6个摄像头, 后面会有20个以上同时播放的情况&nbsp; &nbsp;估计内存很快会 被撑满








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 如果网速很慢  画面 过一段时间后就会卡住不动了  (Issue #176)





 
把问题甩给服务器端。哈哈

**Comment by bosscheng** [comment]
@syf2634179 把你的调用播放器的配置信息贴出来看下呢。你用的什么版本的播放器.
