### ISSUE TITLE
开了4路 cpu 占用率很高

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#179]
![image](https://user-images.githubusercontent.com/23475171/169738299-9d895b8e-c027-4b9e-82dd-71a9a1c00d50.png)
开了4路 CPU就占了很多了useMSE和useWCS 是false的

**Comment by bosscheng** [comment]
@DaikonX 软解码是比较暂用CPU的，如果是h264的，就用硬解码，如果是h265 就只能想办法降低分辨率了。
