### ISSUE TITLE
ios safari报错

### ISSUE THREAD

**Issue by SuperChrisliu** [langhuihui/H5RtmpClient#180]
在ios 14  safari 上https://jessibuca.com/player.html控制台报错，无法播放
mobile demo本地运行，pc上没问题，ios上报错（引用的js是最新release包里的）：
[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	（匿名函数） (jessibuca.js:1)
[Error] TypeError: undefined is not a constructor (evaluating 'new window.Jessibuca')
	全局代码 (index.html:29)

**Comment by SuperChrisliu** [comment]
经过测试 只有3.0.28版本有问题

**Comment by bosscheng** [comment]
@SuperChrisliu 应该修复了，最新版本看下。
