### ISSUE TITLE
升级版本后莫名多了一些false 在dom里

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#181]
![image](https://user-images.githubusercontent.com/23475171/169778777-82b70499-3a44-43ef-b570-aca7759926ca.png)
![image](https://user-images.githubusercontent.com/23475171/169778970-fc05db21-bfed-4eec-a3ac-3ab945a9d626.png)

**Comment by bosscheng** [comment]
@DaikonX 有必先流程嘛

**Comment by DaikonX** [comment]
@bosscheng 

![image](https://user-images.githubusercontent.com/23475171/169780460-f93c54cc-da01-4fe4-8a76-9cb83c5fc5d9.png)
切换这个 在播放就会

**Comment by bosscheng** [comment]
@DaikonX 修复了，最新版本看下
