### ISSUE TITLE
播放器有获取直播流的时间api么

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#182]
像海康播放器有获取OSD时间的api
![image](https://user-images.githubusercontent.com/23475171/170395171-ffb040a5-9cca-44b5-9d20-bb9f7f45a2e9.png)

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/api.html#stats  看下这个api，当前视频帧pts ，应该够满足你的需求了。
