### ISSUE TITLE
Uncaught DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer'

### ISSUE THREAD

**Issue by nine-small** [langhuihui/H5RtmpClient#183]
Just turn off chrome hardware acceleration！Is there another solution？

**Comment by nine-small** [comment]
目前得操作方式是关闭chrome的硬件加速，是否有别的方法，不关闭硬件加速也能解决的办法楠

**Comment by nine-small** [comment]
-
![image](https://user-images.githubusercontent.com/95270791/170613592-299295de-8ec1-4b10-896a-6c5e9e28d89a.png)

**Comment by bosscheng** [comment]
@nine-small 是不是开启了离屏渲染？

**Comment by nine-small** [comment]
是的，目前先关闭，再试试。谢谢了

**Comment by nine-small** [comment]
关闭后没有报错了，但是视频好像变慢了。类似于0.5倍数播放一样

**Comment by bosscheng** [comment]
看下fps是多少。

**Comment by nine-small** [comment]
![image](https://user-images.githubusercontent.com/95270791/170621102-f639044a-3243-49f2-8926-7f18c3d9b06d.png)
目前开启了useWCS: true,useMSE: false,  变正常了，我再看看效果

**Comment by nine-small** [comment]
![image](https://user-images.githubusercontent.com/95270791/170624855-c37379bd-8359-4c0d-afdc-f3ab9f52183f.png)
之前那个错误解决了，出现了新的报错

**Comment by bosscheng** [comment]
有播放地址嘛。我测试看下。

**Comment by nine-small** [comment]
视频带入侵功能的话，是不是也会影响数据流的解码，导致最开始那个报错。

**Comment by nine-small** [comment]
目前资源在内网中

**Comment by nine-small** [comment]
目前先把入侵检测关了，看看是否还有报错。入侵主要就是人体检测那些

**Comment by nine-small** [comment]
wss://117.174.121.41:40004/rtp/51010000491180100001_51010000491320100001.live.flv
配置了一个外网可以访问的资源，帮忙看看呢

**Comment by nine-small** [comment]
那个报错信息我可以捕获到吗。
![image](https://user-images.githubusercontent.com/95270791/170944181-75402908-8f6f-416b-bfa7-1e7427bec0c5.png)

**Comment by bosscheng** [comment]
@nine-small 地址不通了。
