### ISSUE TITLE
开启MediaSource硬解码后， clearView() 清理画布为黑色背景 的方法则不生效了。

### ISSUE THREAD

**Issue by 1095788063** [langhuihui/H5RtmpClient#184]
开启MediaSource硬解码后， clearView() 清理画布为黑色背景 的方法则不生效了。
导致画面是最后一帧的图片。

    MediaSource硬解码 的类，clearView() 没有清空的代码。
      class VideoLoader extends CommonLoader$1 {

      clearView() { }
      
      }

**Comment by bosscheng** [comment]
@1095788063 简单看了下，video 标签确实没有清屏方法。可以用destroy() 方法，会直接销毁video 标签的。

**Comment by 1095788063** [comment]
我尝试确实可以，就是不知道频繁的 destroy() 方法，会不会有性能的影响。

**Comment by bosscheng** [comment]
不会有啥影响，这点影响忽略不计。

**Comment by 1095788063** [comment]
好的，谢谢。
