### ISSUE TITLE
什么时候可以支持一下fmp4格式？

### ISSUE THREAD

**Issue by QiaoMaiMian** [langhuihui/H5RtmpClient#185]

**Comment by bosscheng** [comment]
@QiaoMaiMian pro 版本可以支持。http://jessibuca.monibuca.com/pro.html#%E6%94%AF%E6%8C%81fmp4%E7%9B%B4%E6%92%AD%E5%8D%8F%E8%AE%AE

**Comment by QiaoMaiMian** [comment]
> @QiaoMaiMian pro 版本可以支持。http://jessibuca.monibuca.com/pro.html#%E6%94%AF%E6%8C%81fmp4%E7%9B%B4%E6%92%AD%E5%8D%8F%E8%AE%AE

pro版本在哪里？

**Comment by QiaoMaiMian** [comment]
> @QiaoMaiMian pro 版本可以支持。http://jessibuca.monibuca.com/pro.html#%E6%94%AF%E6%8C%81fmp4%E7%9B%B4%E6%92%AD%E5%8D%8F%E8%AE%AE

pro版本如何获取？
