### ISSUE TITLE
什么情况下会触发画面旋转 

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#187]
同一份代码下
部分电脑偶然会出现画面颠倒 rtsp流里是正的。
![image](https://user-images.githubusercontent.com/23475171/171568398-72ede133-b326-4380-a9f8-8f3f08654d8d.png)
![image](https://user-images.githubusercontent.com/23475171/171568466-0c99e6a7-ba15-42dd-9dee-2a7e8f11bf07.png)

**Comment by bosscheng** [comment]
可能和服务器端的流有关系。播放器不会做啥特殊处理的。

**Comment by MetSystem** [comment]
我也碰到这个问题，谷歌浏览器106.0.5249.119播放是倒立的，换个firefox就正常。

**Comment by MetSystem** [comment]
谷歌浏览器106.0.5249.119播放是倒立的，用官方网上播放却又是正常的。

**Comment by bosscheng** [comment]
@MetSystem http://jessibuca.monibuca.com/document.html#%E5%AF%B9%E4%BA%8E%E5%87%BA%E7%8E%B0%E6%B8%B2%E6%9F%93%E9%A1%B5%E9%9D%A2%E7%9B%B4%E6%8E%A5%E5%80%92%E8%BF%87%E6%9D%A5180%E5%BA%A6%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88

看下这个解释。

**Comment by MetSystem** [comment]
@bosscheng 非常感谢
