### ISSUE TITLE
can not play on iphone

### ISSUE THREAD

**Issue by pubpy2015** [langhuihui/H5RtmpClient#188]
Hi,

With latest version, can not play sample "mobile-demo.html" on iphone.
Previous version is ok.

**Comment by bosscheng** [comment]
try this version [2022-5-27 v3.0.31](https://github.com/langhuihui/jessibuca/releases/tag/v3.0.31)

**Comment by pubpy2015** [comment]
Yes,

This version works fine.
Are there any changes in the latest version?
![image](https://user-images.githubusercontent.com/59004953/172869377-6bb15d55-905a-4e9a-9e9c-aaab6b9f85c2.png)

**Comment by bosscheng** [comment]
try latest version
