### ISSUE TITLE
不支持360及其他国产浏览器

### ISSUE THREAD

**Issue by lanwilliam** [langhuihui/H5RtmpClient#189]
3.1.0版本后，好像均不支持360级其他浏览器使用急速模式。
直接加载不上。
但是谷歌浏览器下正常。

**Comment by DaikonX** [comment]
+1

**Comment by bosscheng** [comment]
我来测试看下。

**Comment by tangyi-ty** [comment]
+1

**Comment by bosscheng** [comment]
@lanwilliam 报错信息贴下呢。

**Comment by lanwilliam** [comment]
decoder.js:1 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): invalid value type 'Simd128', enable with --experimental-wasm-simd @+583)
    at abort (https://jessibuca.com/decoder.js:758:14)
    at https://jessibuca.com/decoder.js:883:10

**Comment by lanwilliam** [comment]
https://jessibuca.com/player.html
咱在线演示页面就不行，可以直接试一下

**Comment by bosscheng** [comment]
@lanwilliam 先回滚到  [2022-5-27 v3.0.31](https://github.com/langhuihui/jessibuca/releases/tag/v3.0.31)  这个版本把。

**Comment by bosscheng** [comment]
@lanwilliam @DaikonX @tangyi-ty 可以试下最新版本了，问题修复了。
