### ISSUE TITLE
全屏播放问题

### ISSUE THREAD

**Issue by hu2014** [langhuihui/H5RtmpClient#190]
页面创建了多个播放器实例，进行多视频播放，点击某一个进行全屏时，所有的视频组件内部都会触发全屏事件，而不是我点击的那个组件

**Comment by bosscheng** [comment]
@hu2014 代码贴下呢。

**Comment by hu2014** [comment]
![image](https://user-images.githubusercontent.com/36222808/172747362-f3933f08-fa4e-403e-97db-637765a53e95.png)

**Comment by hu2014** [comment]
![image](https://user-images.githubusercontent.com/36222808/172747596-b462ca46-88e7-473c-8edc-b120b7bad68e.png)

**Comment by hu2014** [comment]
![image](https://user-images.githubusercontent.com/36222808/172747635-16207c13-ad7b-4331-9a06-eb015e44289b.png)

**Comment by hu2014** [comment]
另外现在docker.js 会一直打印日志，配置项中关闭了日志打印也没用 
![image](https://user-images.githubusercontent.com/36222808/172748285-3e8b3a63-e9fe-4b48-b127-32f5dc862d02.png)

**Comment by bosscheng** [comment]
@hu2014 检查下this.$refs.container 对象，是不是每个jessibuca实例都绑定到一个dom上面去了。

**Comment by bosscheng** [comment]
docker.js日志的报错，说明功能有问题。你这个解码都报错了。播放的没问题？
