### ISSUE TITLE
设置 useWCS: true。 控制台报错

### ISSUE THREAD

**Issue by hehuasa** [langhuihui/H5RtmpClient#192]
1. 初始化 Jessibuca。 在https环境下，设置`useWCS: true`：控制台会报错 `Uncaught DOMException: Failed to execute 'decode' on 'VideoDecoder': A key frame is required after configure() or flush().`，但拉流与播放不影响。
2. 设置`useWCS: true`后， `wcsUseVideoRender: true`、 `forceNoOffscreen: false` 两个选项是不能共存的，建议可以在文档里面补充描述。

**Comment by bosscheng** [comment]
@hehuasa 问题已经修复，文档也补充了下。TKS。
