### ISSUE TITLE
w is not a function 是什么原因呢

### ISSUE THREAD

**Issue by huofucheng** [langhuihui/H5RtmpClient#193]

**Comment by bosscheng** [comment]
@huofucheng 截图看下。

**Comment by huofucheng** [comment]
应该是跟terseplugin   drop_console属性有冲突

![87a9963d5acdfd81d549f94143ebe31](https://user-images.githubusercontent.com/24930962/172543298-4a3efed1-92ce-439d-890e-10be30e04972.png)

**Comment by huofucheng** [comment]
![1654668284771](https://user-images.githubusercontent.com/24930962/172543465-a2e39c38-fec5-4c85-b241-f1d162724220.png)
改成false就好了

**Comment by bosscheng** [comment]
@huofucheng 这个版本太老了，可以试着更新版本。

**Comment by huofucheng** [comment]
@bosscheng OK多谢
