### ISSUE TITLE
Centos系统的图形界面火狐浏览器此插件不支持播放视频FLV

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#194]

**Comment by bosscheng** [comment]
@yu1183688986 报错截图看下呢

**Comment by yu1183688986** [comment]
> @yu1183688986 报错截图看下呢
![微信图片_20220610222649](https://user-images.githubusercontent.com/39176130/173089156-c8e1921a-dfa8-4568-9284-f595598efefb.jpg)

Response has unsupported MIME type "" expected 'application/wasm'

**Comment by bosscheng** [comment]
这个是你服务器返回的文件格式不正确，这个得服务器开启支持。看下这个 http://jessibuca.monibuca.com/document.html#iis%E4%B8%8Bwasm%E8%BF%94%E5%9B%9E404%E9%94%99%E8%AF%AF
