### ISSUE TITLE
最新的版本 decoder.js 有问题，在手机端无法播放视频。 RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #230 failed: invalid simd opcode @+133060)

### ISSUE THREAD

**Issue by 1095788063** [langhuihui/H5RtmpClient#196]
![image](https://user-images.githubusercontent.com/29217820/173170506-2b7f92af-9249-43a4-9a0a-f06af2ec97fd.png)

RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #230 failed: invalid simd opcode @+133060)

**Comment by bosscheng** [comment]
@1095788063 用 2022-5-27 v3.0.31 这个版本试下。目前只有chrome和firefix支持这个特性。

**Comment by 1095788063** [comment]
我试了 Jessibuca_v3.1.0 版本是可以的，并且尝试用  v3.1.2 的 jessibuca.js 和 v3.1.0 decoder.js 搭配在一起是正常的 。

**Comment by bosscheng** [comment]
@1095788063 可以试下最新版本了，问题修复了。

**Comment by 1095788063** [comment]
@bosscheng 还是不行
![image](https://user-images.githubusercontent.com/29217820/174016059-0452b230-a6f3-42d3-9847-960dea7d8a4f.png)

**Comment by 1095788063** [comment]
v3.1.0 decoder.js 版本是正常的

**Comment by bosscheng** [comment]
你试下官网是否可行了。

**Comment by 1095788063** [comment]
![image](https://user-images.githubusercontent.com/29217820/174049539-9fab0e99-1830-4d70-8ebc-a21a48628d2a.png)
官网的是不是出错了，我的都不能播放了 @bosscheng

**Comment by 1095788063** [comment]
![image](https://user-images.githubusercontent.com/29217820/174050144-2532c47e-c95c-4580-a64a-f6eb99d86bfb.png)
打开就直接报错了，用微信公众号开发工具测试。

**Comment by bosscheng** [comment]
好的，我看下

**Comment by bosscheng** [comment]
@1095788063 问题修复了
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/2195154/174638804-841e2402-f40d-49a5-8812-1ab3eba45ca4.png">

**Comment by 1095788063** [comment]
可以正常的运行，点赞。
@bosscheng 提几个小优化的f地方。每次发布版本我自己都要改一下。 
![image](https://user-images.githubusercontent.com/29217820/174700209-85251620-a19d-4786-a250-55d9ba559017.png)
![image](https://user-images.githubusercontent.com/29217820/174700225-6577f244-715c-4b36-a391-da33cb871e7a.png)
![image](https://user-images.githubusercontent.com/29217820/174700242-f9046898-a954-4269-a46f-3dabe48762e7.png)
![image](https://user-images.githubusercontent.com/29217820/174700250-c6f2d526-6d7d-4be5-b480-dc8c16e56f2c.png)
![image](https://user-images.githubusercontent.com/29217820/174700262-f44a0d15-ce3b-47fc-8355-c8363a2771de.png)
		  //视频信息，多次返回，也没有关系的了，主要是每次第二次换新的播放地址，不会返回了。
		  if(EVENTS.videoInfo!=null){
			  this.player.emit(EVENTS.videoInfo, this.videoInfo);
		  }


			//有时候这里会报错，最好加个判断避免报错
			if(this.sourceBuffer.appendBuffer!=null){
				this.sourceBuffer.appendBuffer(buffer);
			}



	  set recording(value) {
		  if (value) {
			  if (this.playing) {
				  //加个判断避免报错
				  if(this.recorder!=null&&this.recorder.startRecord!=null){
					  this.recorder.startRecord();
				  }
			  }
		  } else {
			  //加个判断避免报错
			  if(this.recorder!=null&&this.recorder.stopRecordAndSave!=null) {
				  this.recorder.stopRecordAndSave();
			  }
		  }
	  }



			  //加个判断避免报错
			  if(this.video!=null&&this.video.clearView!=null){
				  this.video.clearView();
			  }



		  //加个判断避免报错
		  if(this.player==null){
			  return false;
		  }
		  if(this.player.playing==null){
			  return false;
		  }

**Comment by bosscheng** [comment]
@1095788063 ok 谢谢。
