### ISSUE TITLE
同时打开多个jessibuca播放器时，突然黑屏且不能播放

### ISSUE THREAD

**Issue by jiaojiren** [langhuihui/H5RtmpClient#197]
![image](https://user-images.githubusercontent.com/48167118/173265578-386fb669-03d7-4803-b0f8-51d562b905ca.png)
打开多个视频时，大概8、9个，突然内存飙升，然后黑屏

**Comment by jiaojiren** [comment]
发现原因了，是vue的响应式造成的负荷太大

**Comment by choi2k** [comment]
> ![image](https://user-images.githubusercontent.com/48167118/173265578-386fb669-03d7-4803-b0f8-51d562b905ca.png) 打开多个视频时，大概8、9个，突然内存飙升，然后黑屏

我這測試的時候, 第二個就已經是空白屏了. 可以同時打開 7,8 個視頻 ? :(

**Comment by bosscheng** [comment]
先别用离屏渲染呢，多屏情况如果是h264的，试着用硬解。

**Comment by bosscheng** [comment]
离屏渲染可能会有问题。

**Comment by jiaojiren** [comment]
请问离屏渲染在哪里关掉呢？

> 离屏渲染可能会有问题。

**Comment by jiaojiren** [comment]
> 离屏渲染可能会有问题。

好像就是这个原因，关掉了就不会黑屏了

**Comment by jiaojiren** [comment]
> 我這測試的時候, 第二個就已經是空白屏了. 可以同時打開 7,8 個視頻 ? :(
可以的

**Comment by jiaojiren** [comment]
> > ![image](https://user-images.githubusercontent.com/48167118/173265578-386fb669-03d7-4803-b0f8-51d562b905ca.png) 打开多个视频时，大概8、9个，突然内存飙升，然后黑屏
> 
> 我這測試的時候, 第二個就已經是空白屏了. 可以同時打開 7,8 個視頻 ? :(

可以的

**Comment by bosscheng** [comment]
嗯，看来离屏渲染问题比较多。
