### ISSUE TITLE
chrome 浏览器视频画面镜像翻转

### ISSUE THREAD

**Issue by zouxiaodong** [langhuihui/H5RtmpClient#198]
chrome播放视频 画画镜像翻转
firefox：
![image](https://user-images.githubusercontent.com/46236818/173310451-69308790-9aff-4c84-8972-6b7aa3870552.png)

chrome：
![image](https://user-images.githubusercontent.com/46236818/173310029-4153aa69-dc19-4940-8af6-188e2107a5bd.png)

**Comment by bosscheng** [comment]
@zouxiaodong 如果是是h264试下硬解码 useMSE:true  或者 useWCS:true

**Comment by zouxiaodong** [comment]
试了useMSE:true正常了，谢谢 @bosscheng
