### ISSUE TITLE
如何得到录制的视频的信息，然后再存入手机相册

### ISSUE THREAD

**Issue by wangdacui2** [langhuihui/H5RtmpClient#201]
试了一下像截图那样赋值给变量获得base64编码方式，录制的视频赋值给一个变量时一个空对象

**Comment by bosscheng** [comment]
不是很理解你的需求。

**Comment by wangdacui2** [comment]
> 能正常录制，录制结束之后，视频没有被自动保存到手机相册，有没有什么办法可以让我录制的视频保存到手机相册。

**Comment by bosscheng** [comment]
代码贴下呢

**Comment by wangdacui2** [comment]
let videoBinary = null; // 录制的视频二进制
				// Vue页面传送过来是否录制视频（isLuXiang）为True时 并且 当前转态是正在播放中和非录制状态下，进行录制视频
				if (data.isLuXiang) {
					if (playing && !recording) {
						console.log("播放中==>", playing);
						console.log("录像中==>", recording);
						videoBinary = jessibuca.startRecord("video" + time, "mp4");
					}
				} else if (!data.isLuXiang && recording) {
					// 否则如果，当前正在录制中，Vue页面传递过来的isLuXiang为false时，暂停录制视频，且将录制的视频存到本地相册
					console.log("播放中==>", playing);
					console.log("录像中==>", recording);
					jessibuca.stopRecordAndSave();
				};
				
				console.log( videoBinary );  // null

**Comment by bosscheng** [comment]
神奇了，调用 stopRecordAndSave() 就会保存文件了、你用的是什么手机？

**Comment by wangdacui2** [comment]
HUAWEI M6 的平板

**Comment by bosscheng** [comment]
你接一个vconsole 看下有没有报错。

**Comment by wangdacui2** [comment]
没有报错，录制结束以后弹出下载框，点击下载，但是手机相册就是没有我录制的视频，就很纳闷，

**Comment by wangdacui2** [comment]
没有报错，录制结束以后弹出下载框，点击下载，但是手机相册就是没有我录制的视频，就很纳闷，

**Comment by bosscheng** [comment]
换个设备看下呢。

**Comment by bosscheng** [comment]
@wangdacui2 你试下调用下截图接口，http://jessibuca.monibuca.com/api.html#screenshot-filename-format-quality-type 看下会不会保存。

**Comment by wangdacui2** [comment]
截图的接口也是跟录制视频一样的，他不保存到手机相册，后面我用 base64 然后去进行一系列的操作，才能保存到手机相册，但是录制视频的他赋值给变量，变量是一个空的对象

**Comment by bosscheng** [comment]
那我知道了。是下载的写法在这个设备下面存在兼容性的问题。

**Comment by wangdacui2** [comment]
ok，我去换个设备测试下，如果只是这个设备存在兼容性，那其他设备应该可以正常保存到手机相册，谢谢了。
