### ISSUE TITLE
3*3窗口播放H.265直播流时页面崩掉

### ISSUE THREAD

**Issue by JacksonTu** [langhuihui/H5RtmpClient#205]
3*3窗口播放H.265直播流时页面崩掉

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/document.html#%E5%88%9B%E5%BB%BA%E5%A4%9A%E4%B8%AA%E4%BB%A5%E4%B8%8A%E6%92%AD%E6%94%BE%E5%AE%9E%E4%BE%8B%E4%BC%9A%E9%9D%9E%E5%B8%B8%E5%8D%A1%E9%A1%BF%EF%BC%8C%E8%BF%98%E4%BC%9A%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E9%BB%91%E5%B1%8F
