### ISSUE TITLE
PCMA格式音频播放只有电流声

### ISSUE THREAD

**Issue by zed-gitub** [langhuihui/H5RtmpClient#206]
从国标协议（GB28181）监控处取到的复合流
流媒体是websocket-flv格式的：
ws://192.168.1.1:6080/rtp/***.flv
视频播放正常，音频播放只有电流声
![image](https://user-images.githubusercontent.com/29136201/175255648-2ba8e47f-10d5-4bb6-9941-5055305e9fbb.png)

**Comment by bosscheng** [comment]
看下解析出来的音频格式是啥？
