### ISSUE TITLE
ColorOS V12.1 手机端播放频闪

### ISSUE THREAD

**Issue by lanwilliam** [langhuihui/H5RtmpClient#207]
升级手机系统后出现的。当前系统版本信息
![image](https://user-images.githubusercontent.com/8511385/175843610-e65fb0a3-b1b2-48c4-82d8-22efa5bd57b2.png)
同时一加10T存在相同问题。
播放过程中不断屏闪，白色屏闪。

**Comment by bosscheng** [comment]
使用的是哪种解码方式？useMSE? useWCS？ 还是wasm？
