### ISSUE TITLE
vue使用报错Uncaught TypeError: Cannot set property navigator of #<WorkerGlobalScope> which has only a getter

### ISSUE THREAD

**Issue by xia0j** [langhuihui/H5RtmpClient#208]
Uncaught TypeError: Cannot set property navigator of #<WorkerGlobalScope> which has only a getter

**Comment by xia0j** [comment]
使用的最新版本的jseeibuca.js文件

**Comment by bosscheng** [comment]
如何初始化jessibuca的，贴下代码呢
