### ISSUE TITLE
一次性加载四个视频cpu占满卡死了 ，就想着用最新版本 。但是用了最新的版本插件， 视频一直loading在加载，也没报错~  用之前的版本就可以直接加载

### ISSUE THREAD

**Issue by xia0j** [langhuihui/H5RtmpClient#211]
this.jessibuca = new window.Jessibuca(Object.assign(
          {
            container: this.$refs.container,
            videoBuffer: 0.2, // 最大缓冲时长，单位秒
            isResize: true,
            isFlv: true,
            decoder: '/decoder.js',
            // text: "WVP-PRO",
            // background: "bg.jpg",
            loadingText: '加载中...',
            // hasAudio: typeof (this.hasAudio) == 'undefined' ? true : this.hasAudio,
            debug: false,
            supportDblclickFullscreen: false, // 是否支持屏幕的双击事件，触发全屏，取消全屏事件。
            // showBandwidth: this.kBps, // 显示网速
            operateBtns: {
              fullscreen: false,
              screenshot: false,
              // play: true,
              audio: false
            },
            hotKey : false ,
            hasAudio  : false ,
            useWCS: true ,
            record: 'record',
            vod: this.vod,
            forceNoOffscreen: true,
            isNotMute: false
          },

play: function(url , i) {
        this.currentNum = i
        if (this.jessibuca) {
          this.destroy()
        }
        this.jessibuca.on('play', () => {
          this.playing = true
          this.loaded = true
          this.quieting = this.jessibuca.quieting
        })

        if (this.jessibuca.hasLoaded()) {
          this.jessibuca.play(url)
        } else {

          this.jessibuca.on('load', () => {
            this.jessibuca.play(url)
            this.jessibuca.setScaleMode(0)
          })
        }
      },

**Comment by Eric3495** [comment]
最新的 性能有问题， 我这边也遇到了， 等大佬查一下怎么解决

**Comment by bosscheng** [comment]
是什么样的一个情况，能和我简单描述下嘛，不然我不知道如何定位问题。

**Comment by bosscheng** [comment]
@xia0j @Eric3495 看下 http://jessibuca.monibuca.com/player-pro.html 最新出炉的，性能提升了不少
