### ISSUE TITLE
最新版本包，ws 播放 回放的情况 很不稳定，加载一下然后就 destroy

### ISSUE THREAD

**Issue by nieliSunboy** [langhuihui/H5RtmpClient#215]
![image](https://user-images.githubusercontent.com/33014904/177091623-fda56136-d645-4cd0-9eb5-af73a684e925.png)

打印日志--：
play------------- ws://112.51.248.205:8081/jessica/34020000001110000030/34020000001320000001/1656864000-1656950399 ws://112.51.248.205:8081/jessica/34020000001110000030/34020000001320000001/1656864000-1656950399
jessibuca.js:1 Jessibuca: [player events] loading true
jessibuca.js:1 Jessibuca: [common dumex] init Interval
jessibuca.js:1 Jessibuca: [M7sDemux] init
jessibuca.js:1 Jessibuca: [player events] mute false
jessibucaRecordPlay.vue?401a:112 on mute false
jessibuca.js:1 Jessibuca: [player events] volumechange 0.5
jessibuca.js:1 Jessibuca: [websocketLoader] socket open
jessibuca.js:1 Jessibuca: [websocketLoader] socket close
index.vue?6ced:227 treeList:  Array(3)
index.vue?6ced:227 treeList:  Array(3)
jessibuca.js:1 Jessibuca: [websocketLoader] destroy
jessibuca.js:1 Jessibuca: [M7sDemux] destroy
jessibuca.js:1 Jessibuca: [decoderWorker] destroy
jessibuca.js:1 Jessibuca: [player events] loading false
jessibuca.js:1 Jessibuca: [player events] timeout loadingTimeout

**Comment by bosscheng** [comment]
看着像服务器端问题，socket直接不通，socket  open-> close
