### ISSUE TITLE
vue3+vite 项目下 decoder.js 路径解析出错

### ISSUE THREAD

**Issue by lxy030988** [langhuihui/H5RtmpClient#216]
![image](https://user-images.githubusercontent.com/29250746/177092797-0a705236-00e1-482b-8261-88067fb5d172.png)

**Comment by bosscheng** [comment]
看下http://jessibuca.monibuca.com/demo.html#vue

**Comment by lxy030988** [comment]
你这个demo不是vite启的    我没找到啥好的方式  直接改了源码里的路径

**Comment by qy163** [comment]
请问下这个问题怎么解决的, docker.js 不是默认去取的根目录下的吗? 为什么每一个路由页面使用插件的时候,这个docker.js 的请求路径都会自动带 路由页的名称,也没看到文档什么有什么可以配置的地方啊

**Comment by qy163** [comment]
![image](https://user-images.githubusercontent.com/26112027/182023241-b89dc931-2a96-4c19-ad1e-82d6bbfa3681.png)

**Comment by qy163** [comment]
![image](https://user-images.githubusercontent.com/26112027/182023279-3624a31b-3a6b-4e05-a014-84e654d9a343.png)

**Comment by bosscheng** [comment]
@qy163 http://jessibuca.monibuca.com/api.html#decoder
