### ISSUE TITLE
硬件解码绿屏无法观看

### ISSUE THREAD

**Issue by hu2014** [langhuihui/H5RtmpClient#217]
![image](https://user-images.githubusercontent.com/36222808/177121144-01420ab5-4563-4f88-9187-91444dc574ef.png)

**Comment by hu2014** [comment]
主码流播放发生，子码流不会出现这种情况。软解也不会出现这种情况

**Comment by hu2014** [comment]
![image](https://user-images.githubusercontent.com/36222808/177148764-fd1f15af-315e-49a6-9835-9c0db48b5b49.png)
貌似是因为切换码流后，报错了

**Comment by bosscheng** [comment]
码流切换了之后，要重新初始化webcodecs的。不然确实会有问题的。

**Comment by hu2014** [comment]
但是不使用硬件解码就不会出现绿屏问题，也不会播放卡顿。麻烦看一下，硬件解码还是很必须的

**Comment by bosscheng** [comment]
好的，有测试地址吗。我测试看下

**Comment by hu2014** [comment]
我看看能不能给你弄个demo


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wancheng1990 ***@***.***&gt;
发送时间: 2022年7月5日 16:14
收件人: langhuihui/jessibuca ***@***.***&gt;
抄送: Bitter ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[langhuihui/jessibuca] 硬件解码绿屏无法观看 (Issue #217)





 
好的，有测试地址吗。我测试看下

**Comment by hu2014** [comment]
哎，不好弄，都是内部的视频。那能说说怎么初始化webcodecs吗，我试试其它办法

**Comment by bosscheng** [comment]
这个问题我在修复中了，修复好了和你讲。

**Comment by hu2014** [comment]
啊~我在这儿等着你回来，等那桃花开

**Comment by hu2014** [comment]
大哥，这个问题还没修好吗？ ^ - ^

**Comment by bosscheng** [comment]
有点难搞，再等等

**Comment by bosscheng** [comment]
@hu2014 方便给我个测试地址我回归测试看下。

**Comment by hu2014** [comment]
你是要视频流地址吗？

**Comment by bosscheng** [comment]
@hu2014 http://jessibuca.monibuca.com/player-pro.html 在这个上面测试看下呢，没有问题，我就同步到开源版上去
