### ISSUE TITLE
又发生视频倒放了

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#218]
![$GXMZPHW2{A3(AQ9`Z$0)SO](https://user-images.githubusercontent.com/23475171/177740449-8a912a34-f7b4-48de-903d-982768f1c1df.png)
左上角是 视频的截图
右下角是 视频 
视频的截图却是正的

**Comment by bosscheng** [comment]
尴尬了。这个咋检测呢。如果是h264的就用硬解码。
