### ISSUE TITLE
qiankun子应用 使用Jessibuca decoder.js:引入报错

### ISSUE THREAD

**Issue by 972981682** [langhuihui/H5RtmpClient#219]
不是qiankun环境，是好的
          videoBuffer: 0.2, // 最大缓冲时长，单位秒
          isResize: true,
          decoder: "static/js/jessibuca/decoder.js",
          useMSE: false,
          showBandwidth: false,
          isFlv: true,

**Comment by bosscheng** [comment]
报啥错，截图看下

**Comment by 972981682** [comment]
![image](https://user-images.githubusercontent.com/35680717/177900817-114d3fa7-a52e-4c8b-afe1-f9cab2888105.png)
![image](https://user-images.githubusercontent.com/35680717/177900879-fed332f4-b0e8-4bb8-889e-d287fd600389.png)

**Comment by bosscheng** [comment]
你看下decoder.wasm文件有没有正确返回。

**Comment by 972981682** [comment]
decoder.wasm文件有没有正确返回？从哪里能看到

**Comment by 972981682** [comment]
目前没看到

**Comment by bosscheng** [comment]
network 栏目下吗

**Comment by 972981682** [comment]
![image](https://user-images.githubusercontent.com/35680717/177913155-f4304743-71cb-40b5-9743-36fc30c3ca7a.png)
没看到

**Comment by bosscheng** [comment]
没看到decoder.js 的请求嘛、

**Comment by 972981682** [comment]
没看到decoder.js 的请求嘛、。在qiankun环境中，子应用显示 decoder.js:引入报错 。你们这个decoder.js，在源码哪里引入的。感觉路径问题？单独启qiankun子应用是，没有问题

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/demo.html#vue  你看下vue 如何引入的。你可以理解成，当成静态js去请求就行了。

**Comment by 972981682** [comment]
我就是用http://jessibuca.monibuca.com/demo.html#vue 引入的。微前端环境不行，非微前端环境好的。

**Comment by bosscheng** [comment]
简单，你把jessibuca 的dist 下面的资源随便放一个静态服务器上面，然后用绝对地址去引用。

**Comment by 972981682** [comment]
我现在把 jessibuca 下面的3个文件，放在服务器上。然后远程引用jessibuca.js 试试

**Comment by bosscheng** [comment]
是的。当第三方资源请求。

**Comment by 972981682** [comment]
![image](https://user-images.githubusercontent.com/35680717/177951805-64a0450d-b834-4014-975d-da5d812627a6.png)
![image](https://user-images.githubusercontent.com/35680717/177951922-43894c45-b13c-48f5-816c-57def2fc5da4.png)
![image](https://user-images.githubusercontent.com/35680717/177952068-81987c82-f263-4772-a81e-bb8fb4085d45.png)
这样弄得还是报错

**Comment by bosscheng** [comment]
错误信息截取全点。
