### ISSUE TITLE
v3.1.5版本，暂停（停止）时，有些浏览器声音无法停止，有杂音一直在响

### ISSUE THREAD

**Issue by ivenstone** [langhuihui/H5RtmpClient#220]
v3.1.5版本，直播播放视频（HEVC+AAC），暂停（停止）时，声音无法停止，有杂音一直在响。部分浏览器出现这个问题。 Chromium 86.0.4240.198 和 360安全浏览器13.1.5360.0  两款浏览器可以复现这个问题。 Firefox 102.0.1  正常。

**Comment by bosscheng** [comment]
@ivenstone 已经修复了，取最新的dist 目录下
