### ISSUE TITLE
useWCS+离屏渲染的CPU比较高问题

### ISSUE THREAD

**Issue by Eric3495** [langhuihui/H5RtmpClient#223]
![image](https://user-images.githubusercontent.com/12705825/178393343-1b1f5bb2-c05d-4a85-a96c-8b903804955a.png)

视频： 1080P H264 4096bps
测试发现CPU占用20%+， 总CPU飙到90%， 分析了一下发现里面两个比较高， 一个包含GPU应该是渲染的， 另外一个占用高的不知道是啥进程占用的。 

我开启MSE硬解码，发现视频容易绿屏和黑屏，也没打印啥错误。

**Comment by bosscheng** [comment]
试试看 useWCS 不要用离屏渲染看看呢

**Comment by Eric3495** [comment]
![image](https://user-images.githubusercontent.com/12705825/178399993-8e6cb75c-de17-4bdc-aed2-4f7b398e2761.png)

useWCS: true,
useOffscreen: false,
forceNoOffscreen: true,
openWebglAlignment: true

看起来相对好一些。最高的 那个进程是交互 数据的吗，有没有办法优化一下

**Comment by bosscheng** [comment]
useWCS: true,
wcsUseVideoRender:true 
这样就行了。这样直接通过video标签渲染，都不需要通过webgl 了。

**Comment by Eric3495** [comment]
目前我标签是canvas的，也能支持吗？ 还是必须改为video标签才行。

我播放器改为video标签， 视频显示不了

**Comment by Eric3495** [comment]
目前我标签是div的，也能支持吗？ 还是必须改为video标签才行。

我播放器改为video标签， 视频显示不了

**Comment by bosscheng** [comment]
不需要改任何操作，直接改配置就行了。信我。

**Comment by Eric3495** [comment]
![image](https://user-images.githubusercontent.com/12705825/178417256-5c2a9b8b-2b00-417f-a3c1-02d2d480e5a0.png)
![image](https://user-images.githubusercontent.com/12705825/178417468-845b1209-8d0b-4e4a-ac65-f274a77a76b9.png)

好像还是挺高的，

**Comment by bosscheng** [comment]
cpu 看着还行，主要就是内存，为啥700m不到，居然就80内存吃没了。你这啥配置的电脑。

**Comment by Eric3495** [comment]
设备名称	DESKTOP-NS9NHGN
处理器	Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz   2.90 GHz
机带 RAM	8.00 GB (7.82 GB 可用)
设备 ID	BECEEC4D-0A58-4474-BF79-3D8E4FA1F221
产品 ID	00342-35551-06482-AAOEM
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

**Comment by bosscheng** [comment]
你把其他东西都关了试试看呢，就留一个浏览器，然后就开一个窗口。看看效果。
