### ISSUE TITLE
某些摄像头流无法播放

### ISSUE THREAD

**Issue by ForMyHeart** [langhuihui/H5RtmpClient#227]
![image](https://user-images.githubusercontent.com/15241965/179642475-3e26989e-bc9f-425a-b0f5-f38ca58aa6bd.png)

播放器配置useMSE为true时出现，但去掉该配置后播放单路视频浏览器占用内存可达到3500M,不满足多屏播放需求，希望作者能解惑，配置useMSE后就不支持播放H265编码了吗？

**Comment by bosscheng** [comment]
目前浏览器还不支持H265的硬解码，只能软解。我看这报错，应该是老版本的，你可以升级到最新版本看下，内存应该不会占用这么大了。

目前也就360浏览器支持H265的硬解码，或者在edge里面购买独立的H265解码。

可以了解下：https://jessibuca.com/pro.html#windows%E7%B3%BB%E7%BB%9F%E4%B8%8B-360%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8F%AF%E6%92%AD%E6%94%BE%E4%BD%BF%E7%94%A8mse%E5%8A%A0%E9%80%9F%E8%A7%A3%E7%A0%81h265%E3%80%82

**Comment by ForMyHeart** [comment]
> 目前浏览器还不支持H265的硬解码，只能软解。我看这报错，应该是老版本的，你可以升级到最新版本看下，内存应该不会占用这么大了。
> 
> 目前也就360浏览器支持H265的硬解码，或者在edge里面购买独立的H265解码。
> 
> 可以了解下：https://jessibuca.com/pro.html#windows%E7%B3%BB%E7%BB%9F%E4%B8%8B-360%E6%B5%8F%E8%A7%88%E5%99%A8%E5%8F%AF%E6%92%AD%E6%94%BE%E4%BD%BF%E7%94%A8mse%E5%8A%A0%E9%80%9F%E8%A7%A3%E7%A0%81h265%E3%80%82

大佬 同样的流 我用你http://jessibuca.monibuca.com/mobile-fullscreen.html提供的demo播放  浏览器内存只有600m左右，但我用git仓库中dist里面最新的代码  同流播放峰值还能达到2400m  是我配置问题吗？很费解

**Comment by ForMyHeart** [comment]
问题已解决  forceNoOffscreen设置为false后内存过大

**Comment by bosscheng** [comment]
Offscreen 会占用这么大的内存嘛

**Comment by ForMyHeart** [comment]
目前看 就是该参数导致同流内存增加。浏览器总内存从稳定600m增加到了峰值2500m

**Comment by bosscheng** [comment]
只能说太坑了。。。。
看来这个实验性的特性还是有问题的。
