### ISSUE TITLE
开启Media Source时，会有黑屏的情况。

### ISSUE THREAD

**Issue by n86717274** [langhuihui/H5RtmpClient#228]
http_flv流，个别流，不开启Media Source正常播放，会弹警告，开启Media Source不报错播放、性能、网速回调都正常，就是播放器黑屏，无任何报错和警告。
不开启Media Source播放10几秒后会弹如下警告：
![image](https://user-images.githubusercontent.com/45391853/179693334-e1704b87-3ce8-4fb6-a772-e71c83537ff4.png)

**Comment by bosscheng** [comment]
看着像流数据本身有问题。
