### ISSUE TITLE
当开启useMSE:true的时候播放H264视频，无法获取timeUpdate视频播放持续时间，H265的可以获取到

### ISSUE THREAD

**Issue by cxf931218** [langhuihui/H5RtmpClient#230]
在播放H264的时候，用的是video标签渲染的，timeUpdate不执行，js不报错，但是在播放H265的时候，timeUpdate一直在执行，js会先报一个错误，执行play方法报错，因为找不到video标签，用的是canvas渲染的
![4jzct56deet6cav30uu5h7din_0](https://user-images.githubusercontent.com/35063221/179893558-32200b73-1b58-4540-9aff-02971d84c7a3.jpg)
![cccqno5qie7h3riurt6v47ip_0](https://user-images.githubusercontent.com/35063221/179893575-297f9bf7-688a-4d17-be72-68d23473a6d4.jpg)
![thzxnw17mje66fnt18waruem_0](https://user-images.githubusercontent.com/35063221/179893588-a2d90ca6-50f7-4658-a242-878345fe18f5.jpg)

**Comment by bosscheng** [comment]
截个图看下报错信息呢

**Comment by cxf931218** [comment]
> 截个图看下报错信息呢

已截图

**Comment by bosscheng** [comment]
哦 你说的是这个方法回调啊。机会没啥人用，我就没有过多处理，我回头补下。
如果是秒级别的话，就监听stats事件，一秒一次的回调，里面有ts 
http://jessibuca.monibuca.com/api.html#stats
