### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by lauix** [langhuihui/H5RtmpClient#231]
`git clone https://github.com/langhuihui/jessibuca.git`
`cd jessibuca/ && npm i`
![image](https://user-images.githubusercontent.com/6456007/180184066-a0b45858-fb36-44f9-9f86-6aa99476ef0b.png)
`npm i --legacy-peer-deps`
![image](https://user-images.githubusercontent.com/6456007/180184154-083389cd-542a-4746-bd83-a886d1623650.png)

**Comment by bosscheng** [comment]
node 版本估计太高了，试下14.x版本。
