### ISSUE TITLE
同一个播放源地址，通过api在播放中切换视频分辨率大小后,videoInfo回调函数没有数据返回最新得视频流信息

### ISSUE THREAD

**Issue by hu2014** [langhuihui/H5RtmpClient#232]
如题

**Comment by bosscheng** [comment]
什么模式下面的？wasm？mse？webcodecs?

**Comment by hu2014** [comment]
wasm

**Comment by bosscheng** [comment]
试下最新版本看下。

**Comment by hu2014** [comment]
切换分辨率后，还是没有反应，这个监听了貌似只有在拿到视频流解析的时候会触发。我这种播放地址没有改变，但是视频流信息变化了的情况，貌似监听不了
![image](https://user-images.githubusercontent.com/36222808/182278283-1a8f53ef-6085-4ca5-baf3-f8e5e4da489e.png)

**Comment by bosscheng** [comment]
我看你还有个问题，加我微信 bosswancheng

**Comment by bosscheng** [comment]
@hu2014 http://jessibuca.monibuca.com/player-pro.html测试看下

**Comment by hu2014** [comment]
就是wasm


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wancheng1990 ***@***.***&gt;
发送时间: 2022年7月29日 10:10
收件人: langhuihui/jessibuca ***@***.***&gt;
抄送: Bitter ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[langhuihui/jessibuca] 同一个播放源地址，通过api在播放中切换视频分辨率大小后,videoInfo回调函数没有数据返回最新得视频流信息 (Issue #232)





 
什么模式下面的？wasm？mse？webcodecs?
