### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'createShader')

### ISSUE THREAD

**Issue by Mxjjj** [langhuihui/H5RtmpClient#233]
![image](https://user-images.githubusercontent.com/88066157/181474798-93dfc1a3-a803-4615-bd8c-9fbc2a2ba395.png)
![image](https://user-images.githubusercontent.com/88066157/181475032-9888feda-be96-46f8-86fd-1ee05f884830.png)
用的chrome浏览器 操作是重复多次的拉H265编码的流之后就出现这个报错 现在只要拉流都会出现这个报错

**Comment by bosscheng** [comment]
如何调用的 贴下代码呢

**Comment by Mxjjj** [comment]
> 如何调用的 贴下代码呢
![image](https://user-images.githubusercontent.com/88066157/181720581-b0c6067e-be0a-4dba-bccc-f85f8fa68bf6.png)

你是说create的代码吗

**Comment by bosscheng** [comment]
如果能给我下出问题的流，好让我定位下问题。

**Comment by Mxjjj** [comment]
> 如果能给我下出问题的流，好让我定位下问题。

用的都是内网 没办法提供呃...

**Comment by bosscheng** [comment]
囧
