### ISSUE TITLE
onvif 的流 表示 会绿屏 很卡,

### ISSUE THREAD

**Issue by syf2634179** [langhuihui/H5RtmpClient#234]
@bosscheng  大佬 如题

**Comment by bosscheng** [comment]
给我个流地址看下呢。

**Comment by syf2634179** [comment]
大佬看下哈 附件里是onvif的,还有个main&nbsp; 10M qq说太大不让发,可以加个QQ 或者微信吗 我再发文件




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] onvif 的流 表示 会绿屏 很卡, (Issue #234)





 
给我个流地址看下呢。

**Comment by bosscheng** [comment]
加我微信把 bosswancheng 记得备注下github。

**Comment by bosscheng** [comment]
最终确认是和http://jessibuca.monibuca.com/document.html#%E8%A7%86%E9%A2%91%E6%B8%B2%E6%9F%93%E5%8F%91%E7%BB%BF%EF%BC%88%E8%BD%AF%E8%A7%A3%E7%A0%81%EF%BC%89 
有关系。
