### ISSUE TITLE
请问，播放器 我在同一个页面创建多个播放器播放，一部分会播放一段时间 触发 pause 停止播放

### ISSUE THREAD

**Issue by nieliSunboy** [langhuihui/H5RtmpClient#235]
请问，播放器 我在同一个页面创建多个播放器播放，一部分会播放一段时间 触发 pause 停止播放

**Comment by bosscheng** [comment]
看下是不是触发了delayTimeout 时间了，就是长时间没有数据返回，超时了。

**Comment by nieliSunboy** [comment]
要是这个问题，怎么样才可以避免呢？

**Comment by nieliSunboy** [comment]
确实都是先 delayTimeout 之后 就停止播放，timeout这个数值设定到60

**Comment by nieliSunboy** [comment]
还有， 感觉视频播放的 不流畅，断断续续卡页面，有时候直接从05秒 跳到10秒 的样子。

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/document.html#%E5%88%9B%E5%BB%BA%E5%A4%9A%E4%B8%AA%E4%BB%A5%E4%B8%8A%E6%92%AD%E6%94%BE%E5%AE%9E%E4%BE%8B%E4%BC%9A%E9%9D%9E%E5%B8%B8%E5%8D%A1%E9%A1%BF%EF%BC%8C%E8%BF%98%E4%BC%9A%E5%AF%BC%E8%87%B4%E9%A1%B5%E9%9D%A2%E9%BB%91%E5%B1%8F

看下这个

**Comment by bosscheng** [comment]
@nieliSunboy http://jessibuca.monibuca.com/player-pro.html

**Comment by bosscheng** [comment]
这个在多实例上面 内存和cpu 这块做了很大的优化。可以试试
