### ISSUE TITLE
同时播放多路视频 几分钟后随机崩溃一个画面显示白屏

### ISSUE THREAD

**Issue by ForMyHeart93** [langhuihui/H5RtmpClient#239]
同时播放多路视频 几分钟后随机崩溃一个画面显示白屏，报错如下，希望大佬有空帮看下
![b77afc3edbdead8499a4dc108a616dd](https://user-images.githubusercontent.com/19706721/183055219-c15ff893-f638-457f-a30c-9821a41c99cf.png)

**Comment by bosscheng** [comment]
@ForMyHeart93 试下最新版本看下。
