### ISSUE TITLE
H265流在选择webcodecs 自动切换成wasm播放有bug

### ISSUE THREAD

**Issue by DaikonX** [langhuihui/H5RtmpClient#240]
![image](https://user-images.githubusercontent.com/23475171/183582819-fcbd3ae1-e3b8-453b-9071-73a35f1f5e94.png)
H265的流在 useWCS：true ，wcsUseVideoRender：true 的时候报错。 官网案例 第一次点击播放 弹出报错，需第二次点击才能播放
![image](https://user-images.githubusercontent.com/23475171/183583156-796719a6-a097-43cb-8743-4094e5478293.png)

**Comment by bosscheng** [comment]
webcodecs 是不支持H265的源的，我在自动切换成wasm 模式播放的时候，出问题了。我来修复下。

**Comment by bosscheng** [comment]
@DaikonX 问题修复了。
