### ISSUE TITLE
Can i play mp4 file

### ISSUE THREAD

**Issue by pubpy2015** [langhuihui/H5RtmpClient#242]
Hi,

can i play mp4 file with url like: http://192.168.1.123/video.mp4

**Comment by bosscheng** [comment]
sorry ，jessibuca just for live streaming

**Comment by pubpy2015** [comment]
But in some video streaming system, it can record the stream to mp4 file and can access that file over http: http://192.168.1.123/video.mp4

can you recommend to me a player, can play mp4 file with h265 video codec ?

Thanks.

**Comment by bosscheng** [comment]
you can try [EasyPlayer.js](https://github.com/tsingsee/EasyPlayer.js)
