### ISSUE TITLE
浏览器最小化或tab切换导致内存泄露

### ISSUE THREAD

**Issue by huhz1107** [langhuihui/H5RtmpClient#243]
打开多路H265视频，使用GPU解码，浏览器最小化，GPU内存泄露，网页崩溃。

**Comment by huhz1107** [comment]
Uploading 751d90975028711816b84057e34a4158.mp4…

录屏如下

**Comment by bosscheng** [comment]
@huhz1107 试下最新版本。

**Comment by huhz1107** [comment]
bug 已经解决了。
