### ISSUE TITLE
pro 使用的时候 decoder.js 中报错： decoder.js:1 Uncaught TypeError: Cannot convert "undefined" to int

### ISSUE THREAD

**Issue by nieliSunboy** [langhuihui/H5RtmpClient#244]
![image](https://user-images.githubusercontent.com/33014904/184574156-d0e34dad-1c88-4ce1-94d0-e6f45d729309.png)

**Comment by nieliSunboy** [comment]
![image](https://user-images.githubusercontent.com/33014904/184577045-ffa2c1b2-735d-4d26-8b95-67a9a3825b6c.png)

**Comment by nieliSunboy** [comment]
我重新下来了最新的.wasm 文件，出现了上述的问题。请问怎么处理，可以 用 pro 播放起来？

**Comment by nieliSunboy** [comment]
还有就是 pro 支持了 webrtc 和 Webtransport 解码方式，可是我在例子中使用都无法播放

**Comment by bosscheng** [comment]
你这个是部分文件替换导致的，pro底层的方法有变化的，不能单独的替换部分文件。pro的东西 加微信 bosswancheng，有问题我单独解决。

**Comment by bosscheng** [comment]
@nieliSunboy

**Comment by nieliSunboy** [comment]
申请好友了。
