### ISSUE TITLE
开启MSE,间隔一段时间刷一些错误出来

### ISSUE THREAD

**Issue by Eric3495** [langhuihui/H5RtmpClient#245]
jessibuca.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'pause')
    at jessibuca.js:1:197334
（匿名） @ jessibuca.js:1
Promise.catch（异步）
（匿名） @ jessibuca.js:1
_play @ jessibuca.js:1
（匿名） @ jessibuca.js:1
play @ jessibuca.js:1
FsH5Play @ fsplayer.js?ver=ver1.1:164
FsChangeStream @ fspreview.js?ver=ver1.1:759
Fs_Load @ fspreview.js?ver=ver1.1:204
window.onload @ fspreview.js?ver=ver1.1:63
load（异步）
（匿名） @ fspreview.js?ver=ver1.1:60
jessibuca.js:1 WebSocket connection to 'ws://admin:xmsx1234@192.168.8.103/live/main.flv' failed: Data frame received after close
_createWebSocket @ jessibuca.js:1
fetchStream @ jessibuca.js:1
（匿名） @ jessibuca.js:1
jessibuca.js:1 Uncaught TypeError: Cannot read properties of null (reading 'emit')
    at MediaSource.<anonymous> (jessibuca.js:1:153953)
（匿名） @ jessibuca.js:1
sourceclose（异步）
Ze @ jessibuca.js:1
（匿名） @ jessibuca.js:1
init @ jessibuca.js:1
（匿名） @ jessibuca.js:1
play @ jessibuca.js:1
（匿名） @ jessibuca.js:1
play @ jessibuca.js:1
（匿名） @ jessibuca.js:1
r @ jessibuca.js:1
emit @ jessibuca.js:1
（匿名） @ jessibuca.js:1
Promise.then（异步）
（匿名） @ jessibuca.js:1
setTimeout（异步）
checkHeartTimeout @ jessibuca.js:1
checkHeart @ jessibuca.js:1
handleRender @ jessibuca.js:1
_decodeVideo @ jessibuca.js:1
decodeVideo @ jessibuca.js:1
_doDecoderDecode @ jessibuca.js:1
e @ jessibuca.js:1
setInterval（异步）
initInterval @ jessibuca.js:1
Me @ jessibuca.js:1
Oe @ jessibuca.js:1
Ve @ jessibuca.js:1
（匿名） @ jessibuca.js:1
init @ jessibuca.js:1
（匿名） @ jessibuca.js:1
play @ jessibuca.js:1
（匿名） @ jessibuca.js:1
_play @ jessibuca.js:1
（匿名） @ jessibuca.js:1
play @ jessibuca.js:1
FsH5Play @ fsplayer.js?ver=ver1.1:164
FsChangeStream @ fspreview.js?ver=ver1.1:759
FsChangePluginway @ fspreview.js?ver=ver1.1:861
Fs_Load @ fspreview.js?ver=ver1.1:205
window.onload @ fspreview.js?ver=ver1.1:63
load（异步）
（匿名） @ fspreview.js?ver=ver1.1:60
jessibuca.js:1 Jessibuca: [MediaSource] _startCheckAppendBufferEndTimeout timeout
error @ jessibuca.js:1
（匿名） @ jessibuca.js:1
setTimeout（异步）
_startCheckAppendBufferEndTimeout @ jessibuca.js:1
（匿名） @ jessibuca.js:1
jessibuca.js:1 Uncaught TypeError: Cannot read properties of null (reading 'readyState')
    at get state [as state] (jessibuca.js:1:154657)
    at get isStateOpen [as isStateOpen] (jessibuca.js:1:154698)
    at Ze.abortSourceBuffer (jessibuca.js:1:162050)
    at Ze.stop (jessibuca.js:1:161317)
    at jessibuca.js:1:162619
get state @ jessibuca.js:1
get isStateOpen @ jessibuca.js:1
abortSourceBuffer @ jessibuca.js:1
stop @ jessibuca.js:1
（匿名） @ jessibuca.js:1
setTimeout（异步）
_startCheckAppendBufferEndTimeout @ jessibuca.js:1
（匿名） @ jessibuca.js:1

码流 1080pH264+G711u, 目前MSE确认可以正常播放, 但是会有延时, 实际测试延时2s以上

**Comment by bosscheng** [comment]
@Eric3495 最新版本已经修复
