### ISSUE TITLE
报错Jessibuca: [MediaSource] _startCheckAppendBufferEndTimeout timeout

### ISSUE THREAD

**Issue by LHR703** [langhuihui/H5RtmpClient#246]
报错信息如下图，视频流是处于停止播放状态，使用的版本是2022-8-10 v3.1.11， useMSE为true

![Snipaste_2022-08-15_15-59-01](https://user-images.githubusercontent.com/49012752/184598877-8757853c-cb6d-48ee-a988-40e1ba6dcb0c.png)

**Comment by bosscheng** [comment]
@LHR703 最新版本已经修复
