### ISSUE TITLE
播放ws的flv视频，刚打开视频的时候有时会出现绿屏

### ISSUE THREAD

**Issue by chhdnjut** [langhuihui/H5RtmpClient#249]
![image](https://user-images.githubusercontent.com/46859200/185352946-d82a17da-f18a-4c6d-83df-f3fd119f6e6e.png)

如上图所示，刚开始切到这个界面打开4个播放器的时候，有一定概率出现绿屏，一两秒左右会恢复。decoder.js和jessibuca.js是最新的，点开就绿屏给人的感觉总是不太好，哪怕播放器的加载的圈圈多转一会，也比绿屏的体验要好。希望作者可以修复一下这个问题，十分感谢

**Comment by bosscheng** [comment]
@chhdnjut 修复了 
我没打版本
dist 目录下面自取
