### ISSUE TITLE
IOS 原生浏览器 PC端浏览器偶尔也会出现 播放卡顿

### ISSUE THREAD

**Issue by mooczhou** [langhuihui/H5RtmpClient#25]
使用苹果11中的原生浏览器：
Safari
播放地址：
https://bofang.672582.com/11746255920221565/esl_csgo.flv（我本地的推送流）
播放域名：
http://jessibuca.monibuca.com/player.html
现象：通过代码里面的demo播放的时候出现声音时有时无正常播放的时候也会出现声音失真能明显感觉到卡顿的，而且播放有时会出现声音和画面不同步。PC端播放偶尔也会出现相同的问题,偶尔出现声音不卡顿了也会出现失真的现象，下载了代码的demo在配置后videoBuff参数后画面不卡顿但是声音还是迟钝感非常明显，后来发现如果音量比较大的话才会出现这种状况。有的时候也会出现画面像那种按了慢放的那种感觉一样。
浏览器：
Google Chrome
播放地址：
https://bofang.672582.com/11746255920221565/esl_csgo.flv（我本地的推送流）
播放器配置：
        var h5lc = new Jessibuca({
            container,//ff.js
            decoder: decoder + ".js",
            videoBuffer: 5,
            audioBuffer: 15,
            isWebGL:true,
            isNotMute: true,
            showBandwidth: true,
            operateBtns: {
                fullscreen:true,
                screenshot:true,
                play: true,
                audio: true
            },
        });
附：
windows
通过官方提供的编译的命令通过，make.py编译代码
但是提示报错找不到字节码库的这个文件'~/.emscripten'
很多字节码库早obj文件目录下是存在的是不是每次编译时都需要重新生成？

**Comment by mooczhou** [comment]
大佬 我需要编译一个用于播放H5的flv格式的播放器需要传那些参数wasm的最好了

**Comment by bosscheng** [comment]
视频音频不同步的问题正在解决中。

**Comment by mooczhou** [comment]
辛苦了 大佬 最近也在努力学习大佬代码中，希望能帮上大佬的忙

**Comment by bosscheng** [comment]
@mooczhou 视频音频不同步的问题已经解决了，可以使用最新版本测试看下。
