### ISSUE TITLE
请问怎么修改decoder存放的目录

### ISSUE THREAD

**Issue by ibandeng** [langhuihui/H5RtmpClient#255]
请问怎么修改decoder存放的目录？因为是使用的微前端，不方便放到根目录

**Comment by aaasoft** [comment]
> 请问怎么修改decoder存放的目录？因为是使用的微前端，不方便放到根目录

文档里面有写的，配置decoder参数就可以了。
文档地址：http://jessibuca.monibuca.com/api.html#decoder
