### ISSUE TITLE
底部操作条没有相关配置

### ISSUE THREAD

**Issue by aaasoft** [langhuihui/H5RtmpClient#256]
底部操作条缺少隐藏和设置透明度相关的配置，做4画面和9画面的时候看起来就有很多黑条不好看，建议增加上这些配置功能。

![image](https://user-images.githubusercontent.com/1552027/186829582-dc1255f4-b860-4958-88f0-a6bf1b09f18a.png)

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/api.html#controlautohide 看下这个能否满足你的需求。

**Comment by aaasoft** [comment]
> http://jessibuca.monibuca.com/api.html#controlautohide 看下这个能否满足你的需求。

非常感谢，就是需要这个功能，这个属性看漏了。。。
