### ISSUE TITLE
回放视频没有时间戳

### ISSUE THREAD

**Issue by heizhimacoder** [langhuihui/H5RtmpClient#257]
希望出个api可以获取回放时间戳

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/api.html#timeupdate

**Comment by heizhima001** [comment]
不适用的，这个得用播放开始时间+播放持续时间计算时间戳，回放时间有刻度条进行拖动切换的，不方便计算的。

**Comment by heizhimacoder** [comment]
> http://jessibuca.monibuca.com/api.html#timeupdate

不适用的，这个得用播放开始时间+播放持续时间计算时间戳，回放时间有刻度条进行拖动切换的，不方便计算的。
