### ISSUE TITLE
1078的流使用flvjs是有音频的，使用这个播放器只有视频没有音频

### ISSUE THREAD

**Issue by handsomeZHL** [langhuihui/H5RtmpClient#258]

**Comment by handsomeZHL** [comment]
![jessibuca](https://user-images.githubusercontent.com/46318878/187366864-39abc7c0-70c9-4fd2-b510-911f2d2c9051.png)

**Comment by handsomeZHL** [comment]
![jessibuca](https://user-images.githubusercontent.com/46318878/187368470-67fd15b6-303e-45b0-92d5-e0de1e5079f0.png)

**Comment by handsomeZHL** [comment]
![jessibuca](https://user-images.githubusercontent.com/46318878/187368589-8ef0a918-c263-49da-844b-104e3c496b46.png)

**Comment by bosscheng** [comment]
地址贴下，我看下是什么格式的音频、

**Comment by bosscheng** [comment]
目前音频只支持 aac g911a/u  mp3格式的暂不支持。等后续会支持起来。

**Comment by chuxin-cs** [comment]
> 目前音频只支持 aac g911a/u mp3格式的暂不支持。等后续会支持起来。

@bosscheng 你好 目前mp3的普通版本的支持么

**Comment by bosscheng** [comment]
@chuxin-cs 开源版暂不支持，pro 版本支持的。
