### ISSUE TITLE
canvas绘制界面被压扁，画面宽度只显示一半

### ISSUE THREAD

**Issue by guygubaby** [langhuihui/H5RtmpClient#26]
![Screen Shot 2021-03-15 at 8.29.22 PM.png](https://i.loli.net/2021/03/15/Zlr3WaAvwp7yXTd.png)

**Comment by guygubaby** [comment]
h265 flv wasm 配置下

**Comment by bosscheng** [comment]
看下日志，解析出来的视图的width和height 属性。

**Comment by guygubaby** [comment]
![image](https://user-images.githubusercontent.com/21158055/116022607-134f0280-a67d-11eb-9f98-ac8d38b20d62.png)


看解析出来的宽高是正确的 @bosscheng

**Comment by bosscheng** [comment]
方便提供下测试地址嘛 @guygubaby 光看这个看不出来啥问题来。

**Comment by guygubaby** [comment]
> 方便提供下测试地址嘛 @guygubaby 光看这个看不出来啥问题来。  

可能不行哟，这个播放地址是有时效性的😂
