### ISSUE TITLE
H265的视频，延迟很高（现实中2s，视频才播放1s），videoBuffer都设置10了

### ISSUE THREAD

**Issue by LeedlyCoder** [langhuihui/H5RtmpClient#261]
H265的视频，延迟很高（现实中2s，视频才播放1s），videoBuffer都设置10了
播放时间越长，视频的时间与现实的时间差距就越大
监听帧数时发现在10帧左右跳动，有时候甚至变成0帧
版本：V3.1.14

**Comment by bosscheng** [comment]
看下分辨率，如果是1080的话，开源版支持不了这么大的分辨率，可以试下http://jessibuca.monibuca.com/player-pro.html pro版本的。

**Comment by LeedlyCoder** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
