### ISSUE TITLE
【功能配置】前端界面录像功能按钮默认保存的是webm格式，想要达到通过配置指定webm或MP4格式

### ISSUE THREAD

**Issue by walkTtalk** [langhuihui/H5RtmpClient#266]
需求：前端界面录像功能按钮默认保存的是webm格式，想要达到通过配置指定webm或MP4格式
![2b5bff31908ab2ebed5a40a62cfe5f1](https://user-images.githubusercontent.com/20769982/190942188-3c2c5d40-7918-4b2d-a8bd-53fbd5ca7d9f.jpg)
![4eff40941fb959db2993715b105c86b](https://user-images.githubusercontent.com/20769982/190942190-7e88746d-c6a3-4549-acfa-f7f285a931fd.jpg)

目的：
通过配置可以指定最终下载的是MP4或webm

**Comment by yanwuhuo1** [comment]
怎么配置，录像下来的视频格式不是webm，而是mp4？

**Comment by bosscheng** [comment]
已经条件配置参数了。
