### ISSUE TITLE
operateBtns操作配置问题，录像配置按钮不显示

### ISSUE THREAD

**Issue by NickEric** [langhuihui/H5RtmpClient#267]
使用的是 https://github.com/bosscheng/jessibuca-demo/tree/v3 demo，operateBtns中录像配置设为true，录像按钮不显示

![QQ截图20220922104819](https://user-images.githubusercontent.com/68672695/191647379-baba7128-bf80-4569-af3e-0ed7b3f3a854.jpg)

**Comment by bosscheng** [comment]
http://jessibuca.monibuca.com/api.html#operatebtns  是  record
