### ISSUE TITLE
录像有声音黑屏问题

### ISSUE THREAD

**Issue by NickEric** [langhuihui/H5RtmpClient#268]
最新代码，录像时，黑屏有声音，查找问题后设置音频 hasAudio:false,录像还是黑屏，后来更改解码
设置 useWCS: false,useMSE: false, 才会有图像有声音，但是会报错 4debug.js:11 Jessibuca: [AudioContext] bufferList is large: 49

useWCS,useMSE这两个任何一个设置true就会录像黑屏有声音问题，请问该如何更改

**Comment by bosscheng** [comment]
目前mse 和wcs 确实有问题，在解决中、

**Comment by NickEric** [comment]
> 目前mse 和wcs 确实有问题，在解决中、

好的，了解

**Comment by xChu666** [comment]
> 目前mse 和wcs 确实有问题，在解决中、

你好，目前这个问题解决了吗
