### ISSUE TITLE
js文件报错，无法抛出出异常

### ISSUE THREAD

**Issue by GiasoneSun** [langhuihui/H5RtmpClient#273]
<img width="1061" alt="694bedf661a3505cacad0a528b8daec" src="https://user-images.githubusercontent.com/30550363/195234520-c216d7e3-e8f3-4e90-ac95-795fb49182a9.png">
<img width="340" alt="21e1e143a9068b930069d75c785f94e" src="https://user-images.githubusercontent.com/30550363/195234533-f8fcf9af-74c1-4f81-9599-d21e1235b9fb.png">

**Comment by bosscheng** [comment]
已修复
