### ISSUE TITLE
Chrome和edge浏览器，长时间播放视频后黑屏，报错Cannot read properties of null（reading 'createShader'）

### ISSUE THREAD

**Issue by Se7enQ** [langhuihui/H5RtmpClient#278]

**Comment by bosscheng** [comment]
@Se7enQ 大概多久出现黑屏现状，还有能否贴下你的new Jessibuca({xxx}) 的配置信息。

**Comment by Se7enQ** [comment]
player = new Jessibuca({
    container: document.getElementById(id),
    videoBuffer: 0.2, 
    isResize: false,
    text: "",
    loadingText: "加载中",
    debug: false,
    showBandwidth: false, 
    operateBtns: {
      fullscreen: false,
      screenshot: false,
      play: false,
      audio: false,
    },
    forceNoOffscreen: true,
    isNotMute: false,
  });
有时候刚打开就会出现黑屏，有时候播一段时间出现，播放时长不固定

**Comment by August1023** [comment]
我在本地运行wvp项目也会在Chrome和edge浏览器上播放一会后出现黑屏情况。下面是Console日志：
<img width="960" alt="2cfc4e508b143ad48b87353d1fbcc54" src="https://user-images.githubusercontent.com/45287355/205208155-271073e5-7933-455d-a345-000c7fa0a8f8.png">

**Comment by August1023** [comment]
谷歌浏览器、Edge浏览器会出现黑屏，火狐浏览器不会黑屏但延迟较大。是不是播放器在谷歌和Edge有延时校准，不成功就黑屏，而播放器在火狐上没有延时校准，所以延时越来越大但不会黑屏？

**Comment by bosscheng** [comment]
@August1023 这个黑屏应该就是离屏渲染导致的。
可以看下说明 http://jessibuca.monibuca.com/api.html#forcenooffscreen
还是有确认下是否最新版本。
