### ISSUE TITLE
destroy之后内存无法释放

### ISSUE THREAD

**Issue by zh383603842** [langhuihui/H5RtmpClient#279]
当设置useWCS=true 播放视频后，调用   jessibuca.destroy(); 关闭视频，内存会一直占用 不会正确被释放掉

**Comment by bosscheng** [comment]
@zh383603842 再测试看下呢，应该已经修复了。

**Comment by Dtaocup** [comment]
> @zh383603842 再测试看下呢，应该已经修复了。

jessibuca升级为pro版本之后，destroy好像不起作用

**Comment by bosscheng** [comment]
@Dtaocup pro的destroy 是个promise

**Comment by Dtaocup** [comment]
> @Dtaocup pro的destroy 是个promise
啊，原来是这样，没注意看demo是怎么用的，感谢大佬
