### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by liushaowenliushaowen** [langhuihui/H5RtmpClient#28]
您好，有没有特殊的编译环境要求，编译出错
![96d0b98a3b603623a0a3f1d81adbd92](https://user-images.githubusercontent.com/49803922/111757676-8aeb7e00-88d6-11eb-869f-0851c9185dc3.png)

**Comment by liushaowenliushaowen** [comment]
大神，另外能不给一个h265的案例哈

**Comment by bosscheng** [comment]
试下2.0版本。应该没有问题了。
