### ISSUE TITLE
问题：多路（3路及以上）硬解播放时可能会有画面抖动与频闪问题

### ISSUE THREAD

**Issue by WR-han** [langhuihui/H5RtmpClient#287]
- Version: 3.1.16
- browser: Chrome(107.0.5304.88)/Edge(107.0.1418.35)

复现方法：
  1.使用WCS或MSE硬解码为video标签
  2.播放路数达到3路及以上
  3.有画面尺寸比例超过3/4（接近正方形）的视频流

问题详情：
  1.视频画面抖动
  2.画面频闪且相互切换

临时解决方案：
  1.去除video标签object-fit: fill 拉伸属性
  2.为所有窗格的父容器增加backdrop-filter: blur(0) 毛玻璃样式

**Comment by bosscheng** [comment]
@WR-han tks 已按照你的建议修复，等啥时候chrome修复了这个bug 再去掉这种恶心操作。
