### ISSUE TITLE
谷歌浏览器、Edge浏览器播放一会后黑屏，火狐浏览器不会黑屏，但延时较大

### ISSUE THREAD

**Issue by August1023** [langhuihui/H5RtmpClient#289]
我在使用wvp项目，里面的播放器是jessibuca。当我用谷歌浏览器、Edge浏览器播放视频监控一会后会黑屏，浏览器Console日志：Uncaught DOMException: Failed to execute 'transferToImageBitmap' on 'OffscreenCanvas': ImageBitmap construction failed
<img width="960" alt="2cfc4e508b143ad48b87353d1fbcc54" src="https://user-images.githubusercontent.com/45287355/205208898-30a15f21-e2f7-4488-87e8-89f7c9a4f6aa.png">

**Comment by August1023** [comment]
谷歌浏览器、Edge浏览器会出现黑屏，火狐浏览器不会黑屏但延迟较大。是不是播放器在谷歌和Edge有延时校准，不成功就黑屏，而播放器在火狐上没有延时校准，所以延时越来越大但不会出现黑屏情况？

**Comment by bosscheng** [comment]
@August1023  看下 http://jessibuca.monibuca.com/api.html#forcenooffscreen  这个参数设置。

**Comment by August1023** [comment]
@bosscheng 把这个参数改为true之后，实时监控的延迟会越来越大，这是为什么？
