### ISSUE TITLE
如何使用自己的websocket实例

### ISSUE THREAD

**Issue by yedajiang44** [langhuihui/H5RtmpClient#291]
由于一些其它原因，需要使用自己的websocket实例，并进行数据处理后才能给播放器数据，请问这个需求如何实现？

**Comment by bosscheng** [comment]
可以二次改造下播放器就行了，都是开源的。

**Comment by yedajiang44** [comment]
> 可以二次改造下播放器就行了，都是开源的。

请问下，有无提供相关配置的计划？
