### ISSUE TITLE
safari浏览器打开flv流无法自动播放

### ISSUE THREAD

**Issue by FimaiTech** [langhuihui/H5RtmpClient#293]
![截屏2023-01-05 19 38 52](https://user-images.githubusercontent.com/24247732/210773369-56259c48-74eb-44ed-8b46-74a47582a581.png)
macOS系统使用safari浏览器打开摄像头的flv实时流，无法自动播放，需要手动点击控制栏的播放键才能播放。使用Windows的chrome浏览器则播放正常。

**Comment by bosscheng** [comment]
@FimaiTech 方便贴下null is not an object 那个具体是哪个地方报的错嘛、

**Comment by FimaiTech** [comment]
1、null is not an object 这个错误在chrome和safari两个浏览器之间都会出现，好像没什么影响；

**Comment by FimaiTech** [comment]
1、null is not an object这个错误在chrome和safari两个浏览器都会出现，好像没什么影响；
2、通过日志发现safari浏览器获取到的videoInfo比较慢，获取到之后没执行Play操作；

[chrome正常播放日志.txt](https://github.com/langhuihui/jessibuca/files/10401310/chrome.txt)
[sarafi不能自动播放.txt](https://github.com/langhuihui/jessibuca/files/10401311/sarafi.txt)
![safari浏览器addSourceBuff报错](https://user-images.githubusercontent.com/24247732/212060705-3775c59e-c8f5-4993-a0bd-48439bb9150d.jpg)
![null is not a object](https://user-images.githubusercontent.com/24247732/212060717-33e8444d-b6be-42d6-8522-97a90671c82c.jpg)
![比较](https://user-images.githubusercontent.com/24247732/212060726-dcbd31ff-3fcd-4a12-8a79-c5b8f01edfc7.jpg)

**Comment by bosscheng** [comment]
已经修复
