### ISSUE TITLE
频繁调用播放器的 snapshot 方法可能会造成内存泄漏

### ISSUE THREAD

**Issue by Bourne115** [langhuihui/H5RtmpClient#294]
**运行环境：**
- chrome 浏览器，版本： 109.0.5414.75 （只开了播放器页面）
- 操作系统：windows11企业版

**snapshot 方法的调用代码**
```js
Vue.prototype.$JessibucaPlayer.screenshot(name, 'jpeg', 0.3, 'base64')
```
**内存监控对比：**
- 切换视频流地址时**调用 snapshot 方法**时的任务管理内存占用情况：

![ed734cb6123cd0911aa47e064af099d](https://user-images.githubusercontent.com/35766694/212456876-9797c33e-8c41-496a-8878-94412f3586a8.png)

- 切换视频流地址时**不调用 snapshot 方法**时的任务管理内存占用情况：

![5e7c3a82899a59475858462a2336efe](https://user-images.githubusercontent.com/35766694/212456904-4f5e625a-a497-460c-b72c-f0a83bf7ea7d.png)

**Comment by bosscheng** [comment]
@Bourne115 帮忙看下渲染的元素是啥，是canvas 还是video。

**Comment by bosscheng** [comment]
已经修复
