### ISSUE TITLE
useMSE解码264，会报错codecWidth

### ISSUE THREAD

**Issue by liaojinlanlwjian** [langhuihui/H5RtmpClient#295]
**MSE解码264**,会一直报错，显示codecWidth
Cannot read properties of undefined (readingat it.decodevideo (jessibuca.js:3815:27)'codecwidth")
在源码上查看是**Ye()**没有返回正确的**t**，导致**t.codecWidth**为undefined，从而导致解码失败

**Comment by bosscheng** [comment]
已修复

**Comment by liaojinlanlwjian** [comment]
在哪个版本啊
