### ISSUE TITLE
开启 webcodecs 后，长时间播放视频后播放器错误

### ISSUE THREAD

**Issue by zhangminggeek** [langhuihui/H5RtmpClient#297]
## 描述

在开启 webcodecs 且未开启离屏渲染情况下，同时播放3路直播视频，H.264，ws-flv，播放大约3小时左右后播放器错误，`Uncaught RuntimeError: memory access out of bounds`

## 环境

- 系统环境 macOS
- 浏览器 Chrome 109.0.5414.87

**Comment by bosscheng** [comment]
已经修复，可以再测试看看
