### ISSUE TITLE
使用vue-fullscreen等类似的全屏插件包裹播放器时，改变全屏状态会影响到播放器的全屏按钮

### ISSUE THREAD

**Issue by BubblingFish** [langhuihui/H5RtmpClient#298]
<template>
  <div style="width:100%:height:100%">
    <fullscreen id="bbox" ref="xfullscreen" v-model="xfullscreen">
      <div id="container" ref="container"></div>
    </fullscreen>
    <button @click="play('xxxxxx.flv)">播放</button>
    <button @click="changeFullScreen">全屏</button>
  </div>
</template>
  <script>
  import fullscreen from 'vue-fullscreen'
  import Vue from 'vue'
  Vue.use(fullscreen)
  export default {
    name: "DemoPlayer",
    data() {
      return {
        jessibuca: null,
        xfullscreen:false
      };
    },
    mounted() {
      this.create()
    },
    unmounted() {
    },
    beforeDestroy() {
    },
    methods: {
      create() {
        this.jessibuca = new window.JessibucaPro(
            Object.assign(
                {
                  container: this.$refs.container,
                  decoder: `../../public/Jessibuca/decoder-pro.js`,
                  videoBuffer: 0.2, // 缓存时长
                  isResize: false,
                  controlAutoHide: true,
                  useWCS: true,
                  useMSE: true,
                  text: "",
                  // background: "bg.jpg",
                  loadingText: "疯狂加载中...",
                  hasAudio:false,
                  debug: false, // 是否打开debug
                  supportDblclickFullscreen: true,
                  showBandwidth: true, // 显示网速
                  operateBtns: {
                    fullscreen: true,
                  },
                  isNotMute: true,
                  timeout: 10
                },
            )
        );
      },
      changeFullScreen() {
        this.xfullscreen =true
      },
      play(url) {
        console.log(url)
        this.jessibuca.play(url).then(() => {
            console.log('play success')
        }).catch((e) => {
            console.log('play error', e)
        })
      }
    },
  };
  </script>
  <style>
  #container {
    width: 800px;
    height: 500px;
    background-color: #000;
  }
  </style>

点击全屏按钮，改变fullscreen值，观察发现播放器全屏按钮也会发生改变

**Comment by bosscheng** [comment]
目前播放器也是根据全局的全屏状态来显示按钮状态的。
如果使用到外层的全屏组件，建议不要配置播放器的全屏按钮，因为全屏事件只有一个，外层全屏了，播放器的全屏按钮配置了也没任何意义。
