### ISSUE TITLE
decoder.js和wasm加载问题

### ISSUE THREAD

**Issue by miraclesumail** [langhuihui/H5RtmpClient#299]
每次返回首页，再进去直播流页面都会重新请求decoder.js和decoder.wasm，等待这2个资源请求完了才会加载视频源，会很慢，需要如何解决？decoder.js和wasm应该在第一次进去就加载好了，以后不用再加载吧？

**Comment by bosscheng** [comment]
返回首页，会destroy掉播放器，释放资源。
因为使用的是worker机制，所以重新new Worker()的时候，必然会出现重新加载decoder.js以及wasm文件。
对于decoder.js 以及wasm 浏览器应该会缓存好的。第二次不会慢的。

**Comment by miraclesumail** [comment]
我在本地localhost启动的话不会重新加载，但是在测试环境用域名访问，每次进直播页面都会重新加载decoder.js和wasm,加载时间也要2s多，加载完了再才看到解析视屏流，会比本地进去直播页面看到直播画面慢很久，大概3 4s

**Comment by bosscheng** [comment]
建议看下测试环境下面的Nginx配置，有没有开启gzip ，缓存这类的设置。
