### ISSUE TITLE
视屏播放

### ISSUE THREAD

**Issue by miraclesumail** [langhuihui/H5RtmpClient#300]
当进去房间1播放视屏源地址1如果未成功(一直pending),再返回大厅，进入房间2播放视屏源2也会一直pendin, 再返回到大厅进入房间3播放视屏源3也会一直pending不成功。把当前页面关掉，重新打开新的窗口，进去直播页面才会正常看到直播画面

**Comment by bosscheng** [comment]
看下这个：http://jessibuca.monibuca.com/document.html#%E5%A4%9A%E4%B8%AAiframe%E4%B8%80%E8%B5%B7%E6%92%AD%E6%94%BE%E8%A7%86%E9%A2%91%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9C%89%E4%B8%80%E4%B8%AA%E8%A7%86%E9%A2%91%E5%9C%B0%E5%9D%80%E6%92%AD%E6%94%BE%E4%B8%8D%E4%BA%86%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%85%B6%E4%BB%96%E5%9C%B0%E5%9D%80%E4%B9%9F%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE
