### ISSUE TITLE
视频播放

### ISSUE THREAD

**Issue by miraclesumail** [langhuihui/H5RtmpClient#302]
这个播放器普通版有时间限制吗，播5分钟开始会有掉帧和卡顿，是普通版只支持5min吗

**Comment by bosscheng** [comment]
都是开源的，没有时间限制。
卡顿和掉帧 可以看下：http://jessibuca.monibuca.com/document.html#%E5%85%B3%E4%BA%8E%E8%A7%86%E9%A2%91%E5%8D%A1%E9%A1%BF
