### ISSUE TITLE
Service worker和视频播放

### ISSUE THREAD

**Issue by miraclesumail** [langhuihui/H5RtmpClient#303]
我用cra写的react页面，里面在构建生产时加入了pwa功能，是workbox-webpack-plugin的插件，测试环境是HTTPS,pwa生效了。但是每次碰到如果视频流加载不出来后，之后所有的视频流地址都无法加载，只有把application下的service worker给stop掉，并且unregister掉重新加载就可以，是不是因为cache的原因导致的

**Comment by bosscheng** [comment]
可以看下：https://jessibuca.com/document.html#%E5%A4%9A%E4%B8%AAiframe%E4%B8%80%E8%B5%B7%E6%92%AD%E6%94%BE%E8%A7%86%E9%A2%91%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9C%89%E4%B8%80%E4%B8%AA%E8%A7%86%E9%A2%91%E5%9C%B0%E5%9D%80%E6%92%AD%E6%94%BE%E4%B8%8D%E4%BA%86%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%85%B6%E4%BB%96%E5%9C%B0%E5%9D%80%E4%B9%9F%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE
