### ISSUE TITLE
jessibuca 开源版后台播放黑屏问题

### ISSUE THREAD

**Issue by xiaoQQya** [langhuihui/H5RtmpClient#309]
**问题描述：** 在使用 jessibuca 开源版通过 wasm 软解码或 MSE 硬解码 H264 的过程中，测试 9 分屏浏览器切换到后台播放时，显存会迅速增长，显存占满后导致视频黑屏，但控制台并未报错。

**复现环境：**
浏览器：Microsoft Edge 110.0.1587.69 (正式版本) (64 位)
jessibuca 配置：[config.txt](https://github.com/langhuihui/jessibuca/files/10950335/config.txt)
控制台日志：[jessibuca.log](https://github.com/langhuihui/jessibuca/files/10950336/jessibuca.log)，出现黑屏位置 1500 行
报错时资源占用情况：![资源占用](https://user-images.githubusercontent.com/46475319/224533573-6dd2a024-c90b-4e4f-a414-4ab50e3a2e9d.png)

**Comment by bosscheng** [comment]
问了下chatgpt ：

窗口被最小化、系统进入睡眠模式等用户操作都有可能导致WebGL上下文丢失。


当用户窗口被最小化或系统进入睡眠模式时，浏览器会暂停WebGL上下文的渲染和更新。这可能会导致WebGL上下文超时（timeout）并且丢失。如果WebGL上下文被挂起或暂停时间过长，可以认为WebGL上下文已过期或无效，从而导致CONTEXT_LOST_WEBGL错误。


看来得添加个事件，预防下这种情况了

**Comment by xiaoQQya** [comment]
> 问了下chatgpt ：
> 
> 窗口被最小化、系统进入睡眠模式等用户操作都有可能导致WebGL上下文丢失。
> 
> 当用户窗口被最小化或系统进入睡眠模式时，浏览器会暂停WebGL上下文的渲染和更新。这可能会导致WebGL上下文超时（timeout）并且丢失。如果WebGL上下文被挂起或暂停时间过长，可以认为WebGL上下文已过期或无效，从而导致CONTEXT_LOST_WEBGL错误。
> 
> 看来得添加个事件，预防下这种情况了

预防只是解决显存溢出黑屏报错的问题，视频在后台其实还是暂停渲染，浏览器恢复前台后视频应该也无法继续播放了吧

**Comment by bosscheng** [comment]
@xiaoQQya 可以更新到最新版本看下
