### ISSUE TITLE
当设置为useMSE: true时，调用pause方法无效

### ISSUE THREAD

**Issue by Steven0621** [langhuihui/H5RtmpClient#310]
创建player时，将配置设置为useMSE: true，调用pause时，promise返回成功，但是实际画面没有暂停，还是播放状态。jessibuca版本：v3.1.28，请看一下，是不是bug。

**Comment by Steven0621** [comment]
视频流使用的ws flv

**Comment by bosscheng** [comment]
我看下

**Comment by Steven0621** [comment]
好的，浏览器用的google chrome ，系统用的deepin v20.8

**Comment by Steven0621** [comment]
另外，补充一个问题：
当点击工具栏上的静音按钮时，不触发mute事件，运行环境和上面一样。
![20230317115416](https://user-images.githubusercontent.com/6915294/225808958-3c69b4c8-3b06-40bf-94ea-d3636a1d1df7.png)

**Comment by bosscheng** [comment]
问下，window 下面有这个问题嘛

**Comment by Steven0621** [comment]
> 问下，window 下面有这个问题嘛

windows 10下也存在同样的问题。

**Comment by Bourne115** [comment]
官网上的这个demo能复现：http://jessibuca.monibuca.com/MSE-demo.html

**Comment by bosscheng** [comment]
已修复
