### ISSUE TITLE
最新版播放器启用useMSE: true，调用close方法，画面静止在最后一帧画面，没有清屏。

### ISSUE THREAD

**Issue by Steven0621** [langhuihui/H5RtmpClient#311]
使用了今天发布的版本，播放器启用useMSE: true，调用close方法，画面静止在最后一帧画面，没有清屏。
软件版本：jessibuca 2023-03-28 v3.1.29
![_20230328160740](https://user-images.githubusercontent.com/6915294/228171696-760a7294-af63-46f6-8f87-7e58c268db82.png)

**Comment by bosscheng** [comment]
目前开源版的 video标签渲染的，不支持清屏操作。

canvas 支持的。

**Comment by bosscheng** [comment]
可以看下api 文档：https://jessibuca.com/api.html#clearview
