### ISSUE TITLE
在 web 端使用 jessibuca 播放器播放 flv 格式的视频时，会频繁报一个异常。

### ISSUE THREAD

**Issue by Bourne115** [langhuihui/H5RtmpClient#313]
InvalidStateError Failed to execute 'addSourceBuffer' on 'MediaSource': The MediaSource's readyState is not 'open'.

![image](https://user-images.githubusercontent.com/35766694/228997310-bcf4b44d-a115-452b-8a11-d46ca5667ddc.png)

**Comment by bosscheng** [comment]
我看下

**Comment by bosscheng** [comment]
@Bourne115 已经修复
