### ISSUE TITLE
WCS启用时遇到视频流缺失关键帧时会失败并回到wsam

### ISSUE THREAD

**Issue by ShuiFan0** [langhuihui/H5RtmpClient#314]
WCS启用时遇到视频流缺失关键帧时会失败并回到wsam

**Comment by bosscheng** [comment]
看下参数：https://jessibuca.com/api.html#autowasm

**Comment by ShuiFan0** [comment]
> 看下参数：https://jessibuca.com/api.html#autowasm

跟这个无关，如果我将它设为false时，视频将无法播放。
这时候，如果我开启视频流延迟3秒加载视频，那边它都是正常播放的。
我使用的是ZLMediaKit按需拉取视频。

Failed to execute 'decode' on ‘VideoDecoder': A key frame is required after configure() or flush().
