### ISSUE TITLE
播放器wss-flv模式下播放m7s视频流播放暂停，m7s不能立刻感知到订阅者离开

### ISSUE THREAD

**Issue by HaoqiLi025** [langhuihui/H5RtmpClient#316]
通过官网提供的开源版本https://jessibuca.com/player.html和付费版本https://jessibuca.com/player-pro.html，测试播放m7s中的视频流，测试发现开源的jessibuca在点击网页暂停按钮后m7s不能立刻感知到最后一个订阅者离开（要等一段时间m7s才会打印"action": "last leave"），而收费测试版本的jessibuca在点击网页暂停按钮后就能感知到最后一个订阅者离开。
开源版播放器暂停播放console打印截图
![image](https://user-images.githubusercontent.com/29673415/230307374-84871628-b4a1-48d2-9303-9ab88562e4c9.png)
付费测试版播放器暂停播放console打印截图
![image](https://user-images.githubusercontent.com/29673415/230307440-105c7bbe-f30e-4f2d-8379-f4ec40c8d126.png)

**Comment by bosscheng** [comment]
已修复，请更新到最新版本，关注下destroy() 方法，返回Promise
