### ISSUE TITLE
WCS模式下打开ws-flv流，如果碰到一个错误将无限报错

### ISSUE THREAD

**Issue by ShuiFan0** [langhuihui/H5RtmpClient#317]
Jessibuca: [Webcodecs] VideoDecoder DOMException: Failed to execute 'decode' on 'VideoDecoder': Cannot call 'decode' on a closed codec.

我只试过ws-flv流，一般不报错的时候没事，如果报了这个错误，就会不停的报这个错误。

**Comment by bosscheng** [comment]
已修复
