### ISSUE TITLE
播放器ws-flv模式停止/烧毁并不会立即中断 ws 连线

### ISSUE THREAD

**Issue by choi2k** [langhuihui/H5RtmpClient#319]
http://jessibuca.monibuca.com/player.html
使用官网测试

![image](https://user-images.githubusercontent.com/2627734/233359124-93a84a87-413f-4fad-a028-4b3155873097.png)
停止后维持在 pending 状态, 这时候看 m7s 那边还是有流量

![image](https://user-images.githubusercontent.com/2627734/233359502-cdd52052-922b-4b47-a565-d88a3152d762.png)

大概一分钟后才会正式停止

https://jessibuca.com/player-pro.html

player pro 会立即停止

#316

**Comment by choi2k** [comment]
#316 应该有关系

**Comment by UMaAlioth** [comment]
确实，请问有解决吗？

**Comment by choi2k** [comment]
> 确实，请问有解决吗？

大概要等作者有空看了

**Comment by bosscheng** [comment]
已经在看了。怀疑和服务器端没有断开也有关系。

**Comment by bosscheng** [comment]
已修复，请更新到最新版本，关注下destroy() 方法，返回Promise
