### ISSUE TITLE
录像回放结束，没有触发任何事件，能不能增加一个停止播放的事件？

### ISSUE THREAD

**Issue by Steven0621** [langhuihui/H5RtmpClient#321]
当录像回放播放完后，没有触发任何事件，而且也不会黑屏，无法判断录像是否播放完了，能不能增加一个播放停止的stop事件？

**Comment by bosscheng** [comment]
播放器也是被动的接受服务器端流数据进行渲染的，并不知道流什么时候结束，只能通过超时的机制知道没流推。

业务上面可以通过心跳或者知道结束的时间戳，通过监听stats 来判断。
