### ISSUE TITLE
iOS播放flv格式直播，有画面没有声音

### ISSUE THREAD

**Issue by csonL** [langhuihui/H5RtmpClient#322]
iOS播放flv格式直播，有画面没有声音，应该是走的wasm+canvas的模式，所以没有音频？
使用demo也同样有画面没声音

**Comment by bosscheng** [comment]
ios默认是静音播放的，需要手动开启声音。
底部控制栏可以打开声音。

**Comment by csonL** [comment]
> ios默认是静音播放的，需要手动开启声音。 底部控制栏可以打开声音。

并不是，底部启动打开音量之后也是没有声音，开源版的demo不行，pro版的demo是正常有声音的。
iOS 16.2的系统

**Comment by bosscheng** [comment]
已经修复了。
