### ISSUE TITLE
最新jessibuca版本自动播放flv流，会没有声音的问题，用户手动触发取消静音jessibuca.cancelMute(),如果配置了 useMSE 不会有声音

### ISSUE THREAD

**Issue by Bourne115** [langhuihui/H5RtmpClient#324]
官网的这个自动播放的 demo 可以复现： https://github.com/bosscheng/jessibuca-auto-demo/blob/main/index.html
给播放器加 useMSE 解码就能复现，使用最新版本。

**Comment by bosscheng** [comment]
最新版本已经修复了

**Comment by Bourne115** [comment]
> 

你好，我看最新版本修复的是 ios端，播放flv流，会没有声音的问题，但我说的这个 issue 还是存在的。就是在pc端浏览器自动播放时，让用户手动触发声音时，使用硬解码就没有声音，不使用硬解码就有声音。

**Comment by Bourne115** [comment]
官网的这个自动播放的 demo 可以复现： https://github.com/bosscheng/jessibuca-auto-demo/blob/main/index.html
给播放器加 useMSE 解码就能复现，使用最新版本。
