### ISSUE TITLE
怎样实现倍速播放

### ISSUE THREAD

**Issue by dconnan** [langhuihui/H5RtmpClient#325]
想使用倍速播放录像流，怎样实现

**Comment by bosscheng** [comment]
开源版不支持倍率播放，可以试下pro版本

文档地址：
https://jessibuca.com/pro.html#%E6%94%AF%E6%8C%81%E9%9F%B3%E8%A7%86%E9%A2%91%E6%B5%81%EF%BC%88tf%E5%8D%A1%E6%B5%81%EF%BC%89%E7%9A%84%E5%80%8D%E6%95%B0%E6%92%AD%E6%94%BE

体验地址：
https://jessibuca.com/pro-demo.html#tf%E5%8D%A1%E6%B5%81%EF%BC%88%E5%BD%95%E5%83%8F%E6%B5%81%EF%BC%89
