### ISSUE TITLE
摄像头推流到m7s服务器，服务频繁死掉

### ISSUE THREAD

**Issue by yuxuanxinchen** [langhuihui/H5RtmpClient#327]
摄像头推流辅流到m7s服务器，通过flv进行播放，每次大概有1分钟左右，m7是服务死到了
下载的window的
![image](https://user-images.githubusercontent.com/15991321/237056613-6e16c374-7b99-41ae-b7f5-772f5fc563a6.png)
摄像头的配置如下：
![image](https://user-images.githubusercontent.com/15991321/237056727-4676b216-d4ce-4f3d-a841-dc0669f2eb71.png)

报错信息如下（部分报错代码）：
goroutine 543 [chan receive]:
runtime.gopark(0x1540afa?, 0xc000cc5680?, 0x60?, 0xe3?, 0xe8?)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/proc.go:363 +0xd6 fp=0xc002727ec8 sp=0xc002727ea8 pc=0x103ddd6
runtime.chanrecv(0xc87eb970e0, 0xc002727fc0, 0x1)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/chan.go:583 +0x49b fp=0xc002727f58 sp=0xc002727ec8 pc=0x1006fbb
runtime.chanrecv2(0x14?, 0xc7030ea040?)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/chan.go:447 +0x18 fp=0xc002727f80 sp=0xc002727f58 pc=0x1006af8
github.com/ghettovoice/gosip.(*server).requestWithContext.func2.3()
	/home/runner/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20221121090201-9a2ed2233b6d/server.go:382 +0x5e fp=0xc002727fe0 sp=0xc002727f80 pc=0x163649e
runtime.goexit()
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc002727fe8 sp=0xc002727fe0 pc=0x106d321
created by github.com/ghettovoice/gosip.(*server).requestWithContext.func2
	/home/runner/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20221121090201-9a2ed2233b6d/server.go:381 +0x634

goroutine 1756 [chan receive]:
runtime.gopark(0x1f74d2542c8?, 0xc0018c8960?, 0x9f?, 0xe0?, 0xc74dddd868?)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/proc.go:363 +0xd6 fp=0xc74dddd800 sp=0xc74dddd7e0 pc=0x103ddd6
runtime.chanrecv(0xc881f10420, 0xc74dddd8c8, 0x1)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/chan.go:583 +0x49b fp=0xc74dddd890 sp=0xc74dddd800 pc=0x1006fbb
runtime.chanrecv1(0x100bd1d?, 0x1?)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/chan.go:442 +0x18 fp=0xc74dddd8b8 sp=0xc74dddd890 pc=0x1006ab8
m7s.live/engine/v4/util.(*Promise[...]).Await(0xc005f5b958?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/safe_chan.go:70 +0x28 fp=0xc74dddd8e8 sp=0xc74dddd8b8 pc=0x1546648
m7s.live/engine/v4.(*IO).receive(0xc000cec6c0, {0xc00611e270?, 0xe8?}, {0x1f6cc774088?, 0xc000cec6c0})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/io.go:262 +0x109c fp=0xc74dddded0 sp=0xc74dddd8e8 pc=0x152ae1c
m7s.live/engine/v4.(*Subscriber).Subscribe(0xc000cec6c0, {0xc00611e270, 0x29}, {0x20db620?, 0xc000cec6c0})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/subscriber.go:124 +0x5a fp=0xc74ddddf08 sp=0xc74dddded0 pc=0x1540afa
m7s.live/engine/v4.(*Plugin).Subscribe(0xc0000dc120, {0xc00611e270, 0x29}, {0x20db620, 0xc000cec6c0})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/plugin.go:268 +0x149 fp=0xc74ddddf60 sp=0xc74ddddf08 pc=0x1532c49
m7s.live/plugin/monitor/v4.(*MonitorSuber).Start(0xc000cec6c0, {0xc00611e270?, 0x0?})
	/home/runner/go/pkg/mod/m7s.live/plugin/monitor/v4@v4.0.0/main.go:47 +0x3b fp=0xc74ddddfb8 sp=0xc74ddddf60 pc=0x191739b
m7s.live/plugin/monitor/v4.(*MonitorConfig).OnEvent.func1()
	/home/runner/go/pkg/mod/m7s.live/plugin/monitor/v4@v4.0.0/main.go:121 +0x2e fp=0xc74ddddfe0 sp=0xc74ddddfb8 pc=0x19192ee
runtime.goexit()
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc74ddddfe8 sp=0xc74ddddfe0 pc=0x106d321
created by m7s.live/plugin/monitor/v4.(*MonitorConfig).OnEvent
	/home/runner/go/pkg/mod/m7s.live/plugin/monitor/v4@v4.0.0/main.go:121 +0xb34

goroutine 1700 [select]:
runtime.gopark(0xc00148bf20?, 0x2?, 0x11?, 0x0?, 0xc00148bef4?)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/proc.go:363 +0xd6 fp=0xc00148bd70 sp=0xc00148bd50 pc=0x103ddd6
runtime.selectgo(0xc00148bf20, 0xc00148bef0, 0xc00148bf10?, 0x0, 0x15e1e26?, 0x1)
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/select.go:328 +0x7dc fp=0xc00148beb0 sp=0xc00148bd70 pc=0x104d8dc
github.com/ghettovoice/gosip/transaction.(*layer).serveTransaction(0xc000c67a00, {0x1f6ce7a5738?, 0xc00712a7e0})
	/home/runner/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20221121090201-9a2ed2233b6d/transaction/layer.go:221 +0x238 fp=0xc00148bfb8 sp=0xc00148beb0 pc=0x15eb6b8
github.com/ghettovoice/gosip/transaction.(*layer).listenMessages.func3()
	/home/runner/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20221121090201-9a2ed2233b6d/transaction/layer.go:195 +0x2e fp=0xc00148bfe0 sp=0xc00148bfb8 pc=0x15eb2ce
runtime.goexit()
	/opt/hostedtoolcache/go/1.19.8/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00148bfe8 sp=0xc00148bfe0 pc=0x106d321
created by github.com/ghettovoice/gosip/transaction.(*layer).listenMessages
	/home/runner/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20221121090201-9a2ed2233b6d/transaction/layer.go:195 +0x2d5

--------------------------------
read chunk size 2097152
read chunk size 2097152
read chunk size 2097152
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x13d2b1b]

goroutine 451 [running]:
m7s.live/engine/v4/util.(*ListItem[...]).InsertAfter(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:36
m7s.live/engine/v4/util.(*List[...]).Push(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:86
m7s.live/engine/v4/util.(*ListItem[...]).Recycle(0x2aae6e0?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:53 +0xdb
m7s.live/engine/v4/util.(*List[...]).Recycle(0xc002fb0928?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:149 +0xaa
m7s.live/engine/v4/util.(*BLL).Recycle(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/pool.go:230
m7s.live/engine/v4/common.(*AVFrame).Reset(0xc002fb08d0)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/common/frame.go:93 +0x4b
m7s.live/engine/v4/track.(*Media).Flush(0xc001a6a600)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/base.go:299 +0x9df
m7s.live/engine/v4/track.(*Video).Flush(0xc001a6a600)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/video.go:263 +0x107
m7s.live/engine/v4/track.(*Video).WriteAnnexB(0xc001a6a600, 0xb80b2000?, 0xc0?, {0xc0b80b2000?, 0xc0024844e0?, 0xc08dd71b18?})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/video.go:116 +0xe5
m7s.live/engine/v4.(*PSPublisher).ReceiveVideo(0xc0001609d8?, {0x24, {0xc0b80b2000, 0x7d2, 0x800}, 0x254aefa0, 0x254aefa0})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/publisher-ps.go:168 +0x447
m7s.live/engine/v4/codec/mpegps.(*DecPSPackage).Read(0xc0001609d8, 0xc4c280?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/mpegps/demuxer_v3.go:137 +0x237
m7s.live/engine/v4/codec/mpegps.(*DecPSPackage).Feed(0xc0001609d8, {0xc002747b8c, 0x256, 0x0?})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/mpegps/demuxer_v3.go:57 +0x94
m7s.live/engine/v4.(*PSPublisher).PushPS(0xc000160900, 0xc08dd71f38)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/publisher-ps.go:47 +0x1d7
m7s.live/plugin/gb28181/v4.(*GB28181Config).processTcpMediaConn(0x2aaf5a0, {0x20d9080?, 0xc0005a0098})
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.2.12/server.go:194 +0x532
created by m7s.live/plugin/gb28181/v4.(*GB28181Config).listenMediaTCP
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.2.12/server.go:219 +0x4d3

--------------------------------
read chunk size 2097152
read chunk size 2097152
panic: runtime error: index out of range [0] with length 0

goroutine 47 [running]:
m7s.live/engine/v4/codec.(*AVCDecoderConfigurationRecord).Unmarshal(0xc000c8f940, {0xc00114ef35, 0x7c, 0x7c})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/h264.go:212 +0x646
m7s.live/engine/v4/track.(*H264).WriteAVCC(0xc00002c600, 0xbabf78?, 0xc00181de48)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/h264.go:92 +0x268
m7s.live/plugin/rtmp/v4.(*RTMPReceiver).ReceiveVideo(0x19e5300?, 0xc000c8fb48?)
	/home/runner/go/pkg/mod/m7s.live/plugin/rtmp/v4@v4.1.9/media.go:169 +0x3c
m7s.live/plugin/rtmp/v4.(*RTMPConfig).ServeTCP(0x2a89860, 0xc00014c068)
	/home/runner/go/pkg/mod/m7s.live/plugin/rtmp/v4@v4.1.9/server.go:166 +0x1611
created by m7s.live/engine/v4/config.(*TCP).listen
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/config/tcp.go:39 +0xf8

--------------------------------
read chunk size 2097152
read chunk size 2097152
panic: runtime error: slice bounds out of range [376:0]

goroutine 242 [running]:
m7s.live/engine/v4/codec/mpegps.(*IOBuffer).Write(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/mpegps/buffer.go:92
m7s.live/engine/v4/codec/mpegps.(*DecPSPackage).Feed(0xc4c4cd5998, {0xc000c9f08c, 0x17a, 0x0?})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/mpegps/demuxer_v3.go:60 +0x311
m7s.live/engine/v4.(*PSPublisher).PushPS(0xc4c4cd58c0, 0xc4f9e83f38)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/publisher-ps.go:47 +0x1d7
m7s.live/plugin/gb28181/v4.(*GB28181Config).processTcpMediaConn(0x2aaf5a0, {0x20d9080?, 0xc000fda088})
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.2.12/server.go:194 +0x532
created by m7s.live/plugin/gb28181/v4.(*GB28181Config).listenMediaTCP
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.2.12/server.go:219 +0x4d3

--------------------------------
read chunk size 2097152
read chunk size 2097152
read chunk size 2097152
panic: item already in list

goroutine 341 [running]:
m7s.live/engine/v4/util.(*ListItem[...]).InsertAfter(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:31
m7s.live/engine/v4/util.(*List[...]).Push(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:86
m7s.live/engine/v4/util.(*ListItem[...]).Recycle(0x2aae6e0?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:53 +0x12a
m7s.live/engine/v4/util.(*List[...]).Recycle(0xc0027f71e8?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/list.go:149 +0xaa
m7s.live/engine/v4/util.(*BLL).Recycle(...)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/util/pool.go:230
m7s.live/engine/v4/common.(*AVFrame).Reset(0xc0027f7190)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/common/frame.go:93 +0x4b
m7s.live/engine/v4/track.(*Media).Flush(0xc000f14f00)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/base.go:299 +0x9df
m7s.live/engine/v4/track.(*Video).Flush(0xc000f14f00)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/video.go:263 +0x107
m7s.live/engine/v4/track.(*Video).WriteAnnexB(0xc000f14f00, 0x2665080?, 0xc0?, {0xc002665080?, 0x1eaefa13338?, 0xc0028a7b18?})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/track/video.go:116 +0xe5
m7s.live/engine/v4.(*PSPublisher).ReceiveVideo(0xc000e85758?, {0x24, {0xc002665080, 0x2a2, 0x2c0}, 0x28b3bb2c, 0x28b3bb2c})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/publisher-ps.go:168 +0x447
m7s.live/engine/v4/codec/mpegps.(*DecPSPackage).Read(0xc000e85758, 0xc5c780?)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/mpegps/demuxer_v3.go:137 +0x237
m7s.live/engine/v4/codec/mpegps.(*DecPSPackage).Feed(0xc000e85758, {0xc002313b8c, 0x9c, 0x0?})
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/codec/mpegps/demuxer_v3.go:57 +0x94
m7s.live/engine/v4.(*PSPublisher).PushPS(0xc000e85680, 0xc0028a7f38)
	/home/runner/go/pkg/mod/m7s.live/engine/v4@v4.12.5/publisher-ps.go:47 +0x1d7
m7s.live/plugin/gb28181/v4.(*GB28181Config).processTcpMediaConn(0x2aaf5a0, {0x20d9080?, 0xc000e8c5b8})
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.2.12/server.go:194 +0x532
created by m7s.live/plugin/gb28181/v4.(*GB28181Config).listenMediaTCP
	/home/runner/go/pkg/mod/m7s.live/plugin/gb28181/v4@v4.2.12/server.go:219 +0x4d3

--------------------------------
read chunk size 2097152

**Comment by langhuihui** [comment]
你配置了chunksize ？

**Comment by yuxuanxinchen** [comment]
我是window下载了m7s后，默认双击运行的，没有修改里边的任何配置。chunksize 还不知道在哪儿配置

**Comment by bosscheng** [comment]
这个不是播放器的问题，先关闭掉了
