### ISSUE TITLE
回放时使用了拖拽

### ISSUE THREAD

**Issue by jparameter** [langhuihui/H5RtmpClient#328]
描述：
我的视频流是从wvp平台请求出来的回放流
在html中做了一版，回放出画面了，调用wvp平台的进度方法也能正常重新加载出画面
在vue中将 下图中的文件放在文件夹中在页面调用
![image](https://github.com/langhuihui/jessibuca/assets/43598654/0a443632-45e5-4964-b632-caebc4417a75)
![image](https://github.com/langhuihui/jessibuca/assets/43598654/6e617166-4d90-4764-8935-56a3d3e05335)
画面出来了，但是在调用拖拽后画面就停止了，流量还在正常走，视频状态也都有
这是拖拽前：
![托前](https://github.com/langhuihui/jessibuca/assets/43598654/1473ae88-e688-422f-9847-4b1a05ac0cff)
这是拖拽后
![托后](https://github.com/langhuihui/jessibuca/assets/43598654/9b6ae28c-818d-469e-95dd-cf2579428c1a)
只有画面是卡住的

**Comment by bosscheng** [comment]
这个问题应该已经修复过了，更新到最新版本看下呢
