### ISSUE TITLE
我在官网测试的播放器播放声音对劲

### ISSUE THREAD

**Issue by guolei368** [langhuihui/H5RtmpClient#33]
声音不对劲，然后我用QQ浏览器好像无法播放，官网测试播放器是最新版本效果嘛？

**Comment by bosscheng** [comment]
> 声音不对劲，然后我用QQ浏览器好像无法播放，官网测试播放器是最新版本效果嘛？

@guolei368 贴下测试地址呢？

**Comment by guolei368** [comment]
在官网http://jessibuca.monibuca.com/player.html  播放的 https://tx2play1.douyucdn.cn/live/252802reTJoPmUir.flv

**Comment by guolei368** [comment]
前面的测试播放地址失效了，这是新的，播放没画面，生意也不对劲：https://tc-tct.douyucdn2.cn/dyliveflv3a/9220456r3q3hs1Ku.flv?wsAuth=e587bb0f1cf0c3deb7695d3834100127&token=web-h5-0-9220456-354aa795ca09fea4d511a42a62ccdc7b020f56633233a8bb&logo=0&expire=0&did=10000000000000000000000000001501&pt=2&st=3&origin=tct&mix=0&isp=

**Comment by guolei368** [comment]
前面的测试播放地址失效了，这是新的，播放没有画面，声音也不对劲：https://tc-tct.douyucdn2.cn/dyliveflv3a/9220456r3q3hs1Ku.flv?wsAuth=e587bb0f1cf0c3deb7695d3834150010d3834150010- -354aa795ca09fea4d511a42a62ccdc7b020f56633233a8bb&logo=0&expire=0&did=10000000000000000000000000001501&pt=2&ist=2&st

**Comment by bosscheng** [comment]
> 前面的测试播放地址失效了，这是新的，播放没有画面，声音也不对劲：https://tc-tct.douyucdn2.cn/dyliveflv3a/9220456r3q3hs1Ku.flv?wsAuth=e587bb0f1cf0c3deb7695d3834150010d3834150010- -354aa795ca09fea4d511a42a62ccdc7b020f56633233a8bb&logo=0&expire=0&did=10000000000000000000000000001501&pt=2&ist=2&st

@guolei368 这个地址，请求了2s不到，就没有流数据返回了。不是流有啥问题啊。

**Comment by guolei368** [comment]
用这个流吧，这个流没问题，但是声音明显的不对劲！https://d1--cn-gotcha04.bilivideo.com/live-bvc/916184/live_372775317_46465575.flv?cdn=cn-gotcha04&expires=1623065639&len=0&oi=1855467723&pt=web&qn=10000&trid=10008db52fcec9eb492e98f603915c61ee42&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=4e271c79fc59073bac7cf42b06c2f862&ptype=0&src=9&sl=3&sk=417e709c171a500&order=4

**Comment by bosscheng** [comment]
> 用这个流吧，这个流没问题，但是声音明显的不对劲！https://d1--cn-gotcha04.bilivideo.com/live-bvc/916184/live_372775317_46465575.flv?cdn=cn-gotcha04&expires=1623065639&len=0&oi=1855467723&pt=web&qn=10000&trid=10008db52fcec9eb492e98f603915c61ee42&sigparams=cdn,expires,len,oi,pt,qn,trid&sign=4e271c79fc59073bac7cf42b06c2f862&ptype=0&src=9&sl=3&sk=417e709c171a500&order=4

报403 没权限访问。
