### ISSUE TITLE
請問有支持fmp4格式直播协议嗎?

### ISSUE THREAD

**Issue by jassonc** [langhuihui/H5RtmpClient#330]
http://jessibuca.monibuca.com/的介紹說明是有 支持fmp4格式直播协议的, 但是我一直找不到相關的demo或設置. 
請問有支持fmp4格式直播协议嗎?
![image](https://github.com/langhuihui/jessibuca/assets/19317269/293d6a14-1219-4295-ae77-cf202786156a)

**Comment by bosscheng** [comment]
你有fml4的测试地址嘛，

**Comment by jassonc** [comment]
> 你有fml4的测试地址嘛，

https://tsvm.ddns.net/api/v1/media-servers/326d6885-31db-4c82-ac8f-f1f3954018b9/devices/355417110016760/live
您試試看

**Comment by jassonc** [comment]
> > 你有fml4的测试地址嘛，
> 
> https://tsvm.ddns.net/api/v1/media-servers/326d6885-31db-4c82-ac8f-f1f3954018b9/devices/355417110016760/live 您試試看

这是hevc fmp4的串流源

**Comment by bosscheng** [comment]
@jassonc 地址貌似挂了，没有数据返回

**Comment by bosscheng** [comment]
pro 已经支持，可以体验看看https://jessibuca.com/player-pro.html
