### ISSUE TITLE
播放器全屏设置旋转角度无效

### ISSUE THREAD

**Issue by yuxuanxinchen** [langhuihui/H5RtmpClient#333]
![image](https://github.com/langhuihui/jessibuca/assets/15991321/a611e9cc-0af1-41df-8993-b4fcd67ec2d3)
设置旋转角度只能往一个方向选择，测试目前只能顺时针选择90度，180度和270度没有反应。播放器用的是开源版本最新版。

**Comment by bosscheng** [comment]
@yuxuanxinchen 我测试了下180,270都是可以的，如方便，提供一个demo出来。

**Comment by bosscheng** [comment]
更新到最新版本测试看看，我测试了没问题。
