### ISSUE TITLE
IOS16.4以上版本会出现out of bounds

### ISSUE THREAD

**Issue by mmjiy** [langhuihui/H5RtmpClient#336]
IOS16.4以上版本会报错：Out of bounds call indirect (evaluating !invoker(fn, thisWired, arg0Wired, arg1Wired))
估计是因为IOS16.4修复内存泄露导致的，请问有没有办法可以解决？

**Comment by bosscheng** [comment]
@mmjiy 看下能不能拿到完整的日志，我来看下

**Comment by loupde** [comment]
RuntimeError: Out of bounds memory access (evaluating 'Yr(4+o+1)')
/jessibuca/decoder.js:1:65047
timeout

**Comment by loupde** [comment]
> @mmjiy 看下能不能拿到完整的日志，我来看下



> @mmjiy 看下能不能拿到完整的日志，我来看下

RuntimeError: Out of bounds memory access (evaluating 'Yr(4+o+1)')
/jessibuca/decoder.js:1:65047
timeout
