### ISSUE TITLE
点击暂停后，再重新播放，会重新拉取直播流，请问该怎么处理才可以实现不重新拉取直播流，从暂停的地方继续播放

### ISSUE THREAD

**Issue by zhangping1** [langhuihui/H5RtmpClient#339]
点击暂停后，再重新播放，会重新拉取直播流

请问该怎么处理才可以实现不重新拉取直播流，从暂停的地方继续播放？

**Comment by bosscheng** [comment]
目前开源版不支持暂停不断开直播流的逻辑。

你这种逻辑应该是录像流的暂停（需要通知服务器端暂停推流），播放器端暂停渲染，但是连接还是一直报错的。

这种逻辑pro（http://jessibuca.monibuca.com/pro/playback-demo.html）的录像流是支持的。 可以体验看下
