### ISSUE TITLE
请测试这个流看看声音

### ISSUE THREAD

**Issue by guolei368** [langhuihui/H5RtmpClient#34]
请测试这个流看看声音问题：http://dyscdnali1.douyucdn.cn/live/3439096ry0WJOkug.flv

**Comment by bosscheng** [comment]
> 请测试这个流看看声音问题：http://dyscdnali1.douyucdn.cn/live/3439096ry0WJOkug.flv

@guolei368 简单测试了下，没怎么发现啥问题吗，你那边是啥问题？

**Comment by guolei368** [comment]
我这边是声音有问题，感觉每个字的话都没说完那种，说卡吧又能听懂，说能听懂吧又像每个字都卡一点，我用的chrome浏览器



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月15日(星期二) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [langhuihui/jessibuca] 请测试这个流看看声音 (#34)





  
请测试这个流看看声音问题：http://dyscdnali1.douyucdn.cn/live/3439096ry0WJOkug.flv
  
@guolei368 简单测试了下，没怎么发现啥问题吗，你那边是啥问题？

**Comment by bosscheng** [comment]
> 我这边是声音有问题，感觉每个字的话都没说完那种，说卡吧又能听懂，说能听懂吧又像每个字都卡一点，我用的chrome浏览器
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月15日(星期二) 中午1:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [langhuihui/jessibuca] 请测试这个流看看声音 (#34) 请测试这个流看看声音问题：http://dyscdnali1.douyucdn.cn/live/3439096ry0WJOkug.flv @guolei368 简单测试了下，没怎么发现啥问题吗，你那边是啥问题？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

能找个更加明显的例子嘛，这样我好定位出问题来，这个例子不太好定位问题。麻烦啦！

**Comment by bosscheng** [comment]
> 我这边是声音有问题，感觉每个字的话都没说完那种，说卡吧又能听懂，说能听懂吧又像每个字都卡一点，我用的chrome浏览器
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月15日(星期二) 中午1:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [langhuihui/jessibuca] 请测试这个流看看声音 (#34) 请测试这个流看看声音问题：http://dyscdnali1.douyucdn.cn/live/3439096ry0WJOkug.flv @guolei368 简单测试了下，没怎么发现啥问题吗，你那边是啥问题？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@guolei368

**Comment by guolei368** [comment]
我录了一下，你看看，这个可以听出来，https://www.zhongdiankaifa.com/ceshi.mkv

**Comment by bosscheng** [comment]
> 我录了一下，你看看，这个可以听出来，https://www.zhongdiankaifa.com/ceshi.mkv

@guolei368 跨域报错了，麻烦设置下头部‘Access-Control-Allow-Origin’信息。
