### ISSUE TITLE
同时开多个player，若前面的播放器打不开流，后面的播放器会被阻塞

### ISSUE THREAD

**Issue by heyingjie** [langhuihui/H5RtmpClient#340]
比如同时开9个播放器，播放不同的流地址，有些流地址因为源的问题是打不开的，这时会导致后续的播放器被阻塞

**Comment by bosscheng** [comment]
可以看下 http://jessibuca.monibuca.com/document.html#%E5%A4%9A%E4%B8%AAiframe%E4%B8%80%E8%B5%B7%E6%92%AD%E6%94%BE%E8%A7%86%E9%A2%91%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%9C%89%E4%B8%80%E4%B8%AA%E8%A7%86%E9%A2%91%E5%9C%B0%E5%9D%80%E6%92%AD%E6%94%BE%E4%B8%8D%E4%BA%86%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%85%B6%E4%BB%96%E5%9C%B0%E5%9D%80%E4%B9%9F%E6%97%A0%E6%B3%95%E6%92%AD%E6%94%BE

这个解决方案
