### ISSUE TITLE
9分屏播放，内存暴涨

### ISSUE THREAD

**Issue by landOfsun** [langhuihui/H5RtmpClient#342]
请问下当我9分屏显示直播流的时候，过一会出现了内存暴涨和后面播着播着就断了的情况，这种有遇到过吗？怎么处理呢？

**Comment by bosscheng** [comment]
可以看下：http://jessibuca.monibuca.com/document.html#%E9%A1%B5%E9%9D%A2%E5%87%BA%E7%8E%B0%E5%B4%A9%E6%BA%83
