### ISSUE TITLE
这个在线flv，开源版正常播放，pro版有问题

### ISSUE THREAD

**Issue by ioolllzzzz** [langhuihui/H5RtmpClient#343]
测试地址：https://flvplayer.js.org/assets/video/weathering-with-you.flv

使用官网在线demo测试

> 开源版正常播放，且播放结束后也会正常重新播放

> pro版播放有两种情况

1. 勾选`设置Flv格式`，则会直接报错
    ![image](https://github.com/langhuihui/jessibuca/assets/23166590/73a7d5a3-2fbd-45f4-aedd-816e8e886731)
2. 不勾选时，偶尔能播放出来，但过一会就会卡住，多数情况同上面
    ![image](https://github.com/langhuihui/jessibuca/assets/23166590/500369a4-3463-4573-be58-d3bfc7b40ea3)

**Comment by bosscheng** [comment]
这个是个点播文件，可以拿个流测试看下。pro 对于延迟这么做了特殊优化，一直会触发丢帧逻辑。
