### ISSUE TITLE
播放的时候，会出现这个问题

### ISSUE THREAD

**Issue by wangyuan0108** [langhuihui/H5RtmpClient#344]
<img width="369" alt="image" src="https://github.com/langhuihui/jessibuca/assets/22407253/ff508f8b-845b-4c6d-b532-5aa449c388b2">

**Comment by bosscheng** [comment]
播放器样式被其他样式覆盖了,检查下是否有全局样式覆盖了播放器的样式（播放器内部会有video,canvas标签）。

如果是vue的话，检查下container是否设置了双向绑定，导致class丢失。
