### ISSUE TITLE
最新版本的jessibuca播放器开启硬解码后播放暂停

### ISSUE THREAD

**Issue by douwenqing** [langhuihui/H5RtmpClient#345]
最新版本的jessibuca，useMSE选项设置为true后，无法正常播放。
![ac9b0b647d2298e0de639d00b184c55](https://github.com/langhuihui/jessibuca/assets/37391812/c4ea50f7-1e0b-4326-a9a5-f169ac53b10e)
![635cca1e7d59e4f68a2d8a9d8d82c31](https://github.com/langhuihui/jessibuca/assets/37391812/9c243342-f2cb-473e-afb7-f009dcf3ca09)
[新版本jessibuca控制台日志.log](https://github.com/langhuihui/jessibuca/files/12180808/jessibuca.log)
[旧版本jessibuca控制台日志.log](https://github.com/langhuihui/jessibuca/files/12180810/jessibuca.log)

**Comment by bosscheng** [comment]
@douwenqing 已修复

**Comment by douwenqing** [comment]
收到，谢谢大佬。
