### ISSUE TITLE
全屏模式播放卡顿 

### ISSUE THREAD

**Issue by xianghu1314** [langhuihui/H5RtmpClient#346]
全屏模式播放卡顿，大家有重现吗？

**Comment by bosscheng** [comment]
@xianghu1314 测试了没有发现卡顿的情况嘛，看能不能给个视频还有日志看下。

**Comment by zhangyahan** [comment]
我现在也有全屏模式下卡顿的问题，小窗口播放就没有问题，但是双击全屏后视频就会卡顿。

日志是指前端 debug 模式下的日志打印吗

**Comment by bosscheng** [comment]
是的

**Comment by zhangyahan** [comment]
您好，我打开了一个 issue，并贴上了日志打印输入。 #361 ，还需要另外的信息吗？
