### ISSUE TITLE
请问 palyer.pause() 或 player.close() 后 websocket 连接不会发起断开吗？

### ISSUE THREAD

**Issue by pandaljf** [langhuihui/H5RtmpClient#349]
我看控制台，暂停或关闭方法执行后并不会关闭 ws 连接，是否有办法去断开连接，不然重启 play() 播放后又会创建一个新的连接

**Comment by pandaljf** [comment]
我希望能访问到播放器当前的 ws 实例，去操作 close，因为我验证过，直接创建 ws 后发起 close，会立马结束当前的连接状态，而不是还需要处在 Pending 一段时间。

**Comment by bosscheng** [comment]
播放器在pause() 和close()的时候，已经调用了ws.close() 方法了，貌似被浏览器无视掉了。
