### ISSUE TITLE
录制结束的recordEnd事件回调绑定了没有触发

### ISSUE THREAD

**Issue by JohnBaozi** [langhuihui/H5RtmpClient#350]
录制结束的recordEnd事件回调绑定了没有触发，点击组件内置的录制结束按钮，或者api触发stopAndSaveRecord接口，都没有该事件触发

**Comment by bosscheng** [comment]
更新到最新，然后对比看下public/demo.html 文件里面写法。我测试了下没问题。

**Comment by JohnBaozi** [comment]
，你发的邮件已经收到，我会尽快回复。

**Comment by JohnBaozi** [comment]
> 更新到最新，然后对比看下public/demo.html 文件里面写法。我测试了下没问题。

好的谢谢你，我试一下
