### ISSUE TITLE
ios下，浏览器切到后台，一段时间后再唤醒，无法播放视频

### ISSUE THREAD

**Issue by BrightXW** [langhuihui/H5RtmpClient#354]
ios下浏览器或微信开启网页，切到后台或者锁屏一段时间后，再切回来，就会黑屏，而且刷新页面或者重启开启新页面都没用，只有结束掉进程后再开启后，就又能正常播放视频了
播放的是flv的视频流

异常有捕获到两种

useWCS为true的时候，new Jessibuca可以执行成功，一直再转圈
![image](https://github.com/langhuihui/jessibuca/assets/20368898/064ccd2d-e694-4ac3-9c5c-5a6ba6bf9cc2)

useWCS为false的时候，new Jessibuca就会报异常，一下是trycatch打印出来的错误
column: 15068
line: 1
message: "Argument 1 ('shader') to WebGLRenderingContext.shaderSource must be an instance of WebGLShader"
sourceURL: "http://192.168.1.141:3000/flv/jessibuca.js"
stack: "shaderSource@[native code]↵@http://192.168.1.141:3000/flv/jessibuca.js:1:15068↵_initContextGl@http://192.168.1.141:3000/flv/jessibuca.js:1:17207↵_initCanvasRender@http://192.168.1.141:3000/flv/jessibuca.js:1:17676↵Fe@http://192.168.1.141:3000/flv/jessibuca.js:1:13444↵Ve@http://192.168.1.141:3000/flv/jessibuca.js:1:24768↵ct@http://192.168.1.141:3000/flv/jessibuca.js:1:184157↵_initPlayer@http://192.168.1.141:3000/flv/jessibuca.js:1:196611↵lt@http://192.168.1.141:3000/flv/jessibuca.js:1:196339↵@http://192.168.1.141:3000/building/datav/src/layouts/video/index.tsx:31:60"
__proto__: Object

**Comment by bosscheng** [comment]
看着像ios 把资源回收了，导致解码器直接不工作了，包括webgl都初始化失败了。

**Comment by BrightXW** [comment]
有什么方式能解决吗？或者至少刷新后怎么处理才能正常播放？

**Comment by bosscheng** [comment]
@BrightXW 配置下先降级到wasm解码看看

**Comment by dimsumc** [comment]
https://blog.csdn.net/s18813688772/article/details/134203931?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&utm_relevant_index=4

好像是 ios17 的 bug

**Comment by dimsumc** [comment]
> @BrightXW 配置下先降级到wasm解码看看

想问一下这个可以怎么设定？

**Comment by BrightXW** [comment]
> [https://blog.csdn.net/s18813688772/article/details/134203931?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog- 133034438.235%5Ev39%5Epc_relevant_default_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&utm _relevant_index=4](https://blog.csdn.net/s18813688772/article/details/134203931?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&utm_relevant_index=4)
> 
> 好像是ios17的bug

好像确实是ios17问题，刚刚试了下，没有问题了，用17.1.2的ios测试的

**Comment by dimsumc** [comment]
> > [https://blog.csdn.net/s18813688772/article/details/134203931?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog- 133034438.235%5Ev39%5Epc_relevant_default_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&utm _relevant_index=4](https://blog.csdn.net/s18813688772/article/details/134203931?spm=1001.2101.3001.6650.3&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-3-134203931-blog-133034438.235%5Ev39%5Epc_relevant_default_base&utm_relevant_index=4)
> > 好像是ios17的bug
> 
> 好像确实是ios17问题，刚刚试了下，没有问题了，用17.1.2的ios测试的

后来有试过降级处理么？
