### ISSUE TITLE
在Vue中，创建多个Canvas来播放，反复切换页面发现使用内存逐渐变高

### ISSUE THREAD

**Issue by Teslaofeizao** [langhuihui/H5RtmpClient#355]
我这使用vue使用cavans来播放，反复切换页面之后浏览器逐渐变得卡顿，然后发现监控使用的内存变得越来越多，切换页面时也使用了destroy来销毁了，但内存还是一样的增长，请问这样如何解决

**Comment by bosscheng** [comment]
销毁部分的代码如何写的。贴出来看下呢

**Comment by bosscheng** [comment]
@Teslaofeizao

**Comment by Teslaofeizao** [comment]
> 销毁部分的代码如何写的。贴出来看下呢

![J@}@T}_ )5X0 U3J$ZNU`_T](https://github.com/langhuihui/jessibuca/assets/80935674/73c5ccf5-70e5-4483-ae78-64227316fa69)

**Comment by bosscheng** [comment]
pro的destroy 是promise，我估计还没有来记得销毁掉。

改成 

```js
async close(){
    await jessibuca.destroy()
}
```

这样就可以了。
