### ISSUE TITLE
simd 优化问题？

### ISSUE THREAD

**Issue by takeern** [langhuihui/H5RtmpClient#357]
看到文档上描述 1080p hevc 提升在 1～3倍，想请教下 simd 的实现只是开启了 emcc simd 编译吗？有对ffmpeg 做汇编优化吗？

**Comment by bosscheng** [comment]
有做优化的。

**Comment by takeern** [comment]
可以分享下优化逻辑吗？

**Comment by bosscheng** [comment]
不好意思，这个是pro 支持的，你可以考虑下购买pro，代码都会有的。这样就可以学习到了。

**Comment by Chrischenny** [comment]
> 不好意思，这个是pro 支持的，你可以考虑下购买pro，代码都会有的。这样就可以学习到了。

你好 进群方式有吗 想了解一下pro版购买方式

**Comment by bosscheng** [comment]
加我wx就行了：bosswancheng 备注 购买JB Pro

**Comment by bosscheng** [comment]
@Chrischenny
