### ISSUE TITLE
最新版本的jessibuca硬解码失败

### ISSUE THREAD

**Issue by liaojinlanlwjian** [langhuihui/H5RtmpClient#358]
配置是：
useMSE：true，
useWCS:  true

**Comment by liaojinlanlwjian** [comment]
useMSE和useWCS同时为true的时候优先使用useMSE，直播就会卡顿一下 然后就没有然后，控制台无输出
注释掉useMSE时，只使用useWCS，直播会播放一帧，然后卡住，控制台输出：[Webcodecs] VideoDecoder handleError DOMException: Decoder error

**Comment by liaojinlanlwjian** [comment]
用软解码就没问题，用硬解码的话就会出现这种问题（解码器错误）

**Comment by bosscheng** [comment]
有没有流地址，发给我测试看下。

**Comment by bosscheng** [comment]
@liaojinlanlwjian

**Comment by liaojinlanlwjian** [comment]
问题是我用jessibuca的demo又可以播放

**Comment by bosscheng** [comment]
你看下你的代码是不是最新的。
