### ISSUE TITLE
 不支持硬解码的电脑播放 h.265格式的失败

### ISSUE THREAD

**Issue by wangdi11111111** [langhuihui/H5RtmpClient#359]
支持硬解码的电脑也是能播放h265的，就是不支持硬解码的电脑播不出来
报错  mediaSourceH265NotSupport

![image](https://github.com/langhuihui/jessibuca/assets/30786370/810847f9-03d5-4303-a890-d2b0192b2768)
![image](https://github.com/langhuihui/jessibuca/assets/30786370/9cd3f54a-542b-446e-a5f2-174383d3c86d)

[jessibuca控制台日志-3.txt](https://github.com/langhuihui/jessibuca/files/13808993/jessibuca.-3.txt)

**Comment by bosscheng** [comment]
已修复
