### ISSUE TITLE
播放H265视频流时延迟太高

### ISSUE THREAD

**Issue by quxiaohui-debug** [langhuihui/H5RtmpClient#364]
我本地推了一路H265编码格式的视频流到ZLMediaKit服务，然后通过本项目demo播放器拉流播放，缓冲时间默认设置为0.2秒，但实际观察时，发现视频延迟远远不止0.2秒；如果我把缓冲时间调整为0秒，则不会有视频延迟，但播放时存在卡顿现象。对比验证了H264编码格式的视频流，则不会存在该问题。

**Comment by quxiaohui-debug** [comment]
使用的wasm解码器软解

**Comment by quxiaohui-debug** [comment]
play error TypeError: jessibuca.isMute is not a function
    at app.e002f267.js:53:198897
decoder.js:30 Jessibuca: [worker]: [hevc @ 0x61f730] Warning: not compiled with thread support, using thread emulation
Module.printErr @ decoder.js:30
put_char @ decoder.js:1289
write @ decoder.js:1214
write @ decoder.js:2919
doWritev @ decoder.js:3838
_fd_write @ decoder.js:6672
$func2273 @ decoder.wasm:1
$func2312 @ decoder.wasm:1
$func2082 @ decoder.wasm:1
$func2080 @ decoder.wasm:1
$func2084 @ decoder.wasm:1
$func2083 @ decoder.wasm:1
$func1984 @ decoder.wasm:1
$func62 @ decoder.wasm:1
$func76 @ decoder.wasm:1
$func73 @ decoder.wasm:1
VideoDecoder$decode @ VM14:10
_doDecode @ decoder.js:8053
loop @ decoder.js:8088
setInterval (async)
init @ decoder.js:8112
self.onmessage @ decoder.js:8174
decoder.js:30 Jessibuca: [worker]: [aac @ 0x61e710] Warning: not compiled with thread support, using thread emulation
Module.printErr @ decoder.js:30
put_char @ decoder.js:1289
write @ decoder.js:1214
write @ decoder.js:2919
doWritev @ decoder.js:3838
_fd_write @ decoder.js:6672
$func2273 @ decoder.wasm:1
$func2312 @ decoder.wasm:1
$func2082 @ decoder.wasm:1
$func2080 @ decoder.wasm:1
$func2084 @ decoder.wasm:1
$func2083 @ decoder.wasm:1
$func1984 @ decoder.wasm:1
$func62 @ decoder.wasm:1
$func58 @ decoder.wasm:1
$func73 @ decoder.wasm:1
AudioDecoder$decode @ VM12:10
_doDecode @ decoder.js:8053
loop @ decoder.js:8088
setInterval (async)
init @ decoder.js:8112
self.onmessage @ decoder.js:8174
debug.js:5 Jessibuca: [decoderWorker] onmessage: videoCode 12
debug.js:5 Jessibuca: [decoderWorker] onmessage: audioCode 10
debug.js:5 Jessibuca: [decoderWorker] onmessage: initAudio channels:2,sampleRate:44100
debug.js:5 Jessibuca: [player events] audioInfo {encType: 'AAC', channels: 2, sampleRate: 44100, encTypeCode: 10}
app.e002f267.js:53 audioInfo {encType: 'AAC', channels: 2, sampleRate: 44100, encTypeCode: 10}
debug.js:5 Jessibuca: [decoderWorker] onmessage: initVideo width:1280,height:720
debug.js:5 Jessibuca: [player events] videoInfo {width: 1280, height: 720, encType: 'H265(HEVC)', encTypeCode: 12}
app.e002f267.js:53 videoInfo {width: 1280, height: 720, encType: 'H265(HEVC)', encTypeCode: 12}
debug.js:5 Jessibuca: [canvasVideo] resize
debug.js:5 Jessibuca: [player events] start undefined
app.e002f267.js:53 frame start
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [player events] playing true
debug.js:5 Jessibuca: [player events] volumechange 0.5
debug.js:5 Jessibuca: [player events] play undefined
app.e002f267.js:53 on play
debug.js:5 Jessibuca: [player events] playToRenderTimes {playInitStart: 1708768369487, playStart: 1708768369488, streamStart: 1708768369490, streamResponse: 1708768369498, demuxStart: 1708768369505, …}
app.e002f267.js:53 {playInitStart: 1708768369487, playStart: 1708768369488, streamStart: 1708768369490, streamResponse: 1708768369498, demuxStart: 1708768369505, …}
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 21
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 22
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 23
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 22
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 23
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 24
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 25
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
2debug.js:11 Jessibuca: [AudioContext] bufferList is large: 26
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 27
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 28
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 29
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86
debug.js:11 Jessibuca: [AudioContext] bufferList is large: 30
Debug.warn @ debug.js:11
play @ audioContextLoader.js:282
decoderWorker.onmessage @ index.js:86

**Comment by quxiaohui-debug** [comment]
控制台有两个警告信息 ，1：Jessibuca: [worker]: [hevc @ 0x61f730] Warning: not compiled with thread support, using thread emulation

**Comment by quxiaohui-debug** [comment]
2：debug.js:11 Jessibuca: [AudioContext] bufferList is large: 21

**Comment by quxiaohui-debug** [comment]
感觉是因为ZLMediaKit的GOP机制，导致刚开始播放时，播放器解码不过来了。

**Comment by bosscheng** [comment]
看下多少分辨率的流，如果是达到1080p的开源版是支持不了的，会存在解码堆积延迟的问题的。

**Comment by quxiaohui-debug** [comment]
不是1080P的，而且只是起播时会卡顿 ，但是播放一段时间之后稳定了

**Comment by bosscheng** [comment]
看下videoBuffer 设置了多大
