### ISSUE TITLE
uni-app版本demo是否支持运行到Android环境？

### ISSUE THREAD

**Issue by luoshi123321** [langhuihui/H5RtmpClient#365]
目前测试运行Android环境报错：(found at pages/index/index.vue:1)
15:58:46.073 TypeError: Cannot read property 'on' of null
15:58:46.261 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'on' of null"

**Comment by bosscheng** [comment]
https://ext.dcloud.net.cn/plugin?name=sy-new-jessibuca  试下这个。

**Comment by luoshi123321** [comment]
报错：应用【sy-new-jessibuca示例】已启动
17:03:14.855 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'Jessibuca' of undefined"

found in

---> <SyNewJessibuca> at uni_modules/sy-new-jessibuca/components/sy-new-jessibuca/sy-new-jessibuca.vue:1
　　　　at pages/index/index.vue:1
17:03:14.885 TypeError: Cannot read property 'Jessibuca' of undefined  
都是基于webview运行的，在android上跑初始话就失败了。
