### ISSUE TITLE
浏览器内核支持问题

### ISSUE THREAD

**Issue by NullWan** [langhuihui/H5RtmpClient#366]
Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.8 Chrome/87.0.4280.144 Safari/537.36
这是我的浏览器内核信息，我想问一下这个版本可以支持jessibuca.js正常运行吗

**Comment by bosscheng** [comment]
建议升级到92版本以后，这个87的稍微低了些。
