### ISSUE TITLE
播放2K直播流内存泄露，直至浏览器崩溃

### ISSUE THREAD

**Issue by 929408183** [langhuihui/H5RtmpClient#37]
<h1>H265 编码 2K分辨率</h1>

![image](https://user-images.githubusercontent.com/37289057/122724851-ef87f180-d2a6-11eb-815d-8eebd827fc12.png)

![image](https://user-images.githubusercontent.com/37289057/122724868-f44ca580-d2a6-11eb-8f00-07c5f7f5d7e4.png)

16G内存扛得住几十秒

**Comment by bosscheng** [comment]
> # H265 编码 2K分辨率
> ![image](https://user-images.githubusercontent.com/37289057/122724851-ef87f180-d2a6-11eb-815d-8eebd827fc12.png)
> 
> ![image](https://user-images.githubusercontent.com/37289057/122724868-f44ca580-d2a6-11eb-8f00-07c5f7f5d7e4.png)
> 
> 16G内存扛得住几十秒

@929408183 试着增大缓冲看看呢。
