### ISSUE TITLE
运行报错RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): section (code 1, "Type")

### ISSUE THREAD

**Issue by 12Park** [langhuihui/H5RtmpClient#370]
![image](https://github.com/langhuihui/jessibuca/assets/17000066/8b6d4ea8-eb96-4f9b-8dda-62fbe3d30e06)
下载的最新源码，
运行时报错
![image](https://github.com/langhuihui/jessibuca/assets/17000066/0520a6ec-1e66-4a86-9cde-5a15a5fb5846)
Aborted(CompileError: WebAssembly.instantiate(): section (code 1, "Type") extends past end of the module (length 17784815, remaining bytes 1238022) @+8)

**Comment by bosscheng** [comment]
@12Park  可以看下：http://jessibuca.monibuca.com/document.html#runtimeerror%EF%BC%9A-aborted-compileerror-webassembly-instantiate-expected-magic-word-00-61-73-6d-found-3c-21-44-4f-0
