### ISSUE TITLE
请问是否支持英伟达显卡进行硬解码，该如何设置呢？

### ISSUE THREAD

**Issue by shancaidazf** [langhuihui/H5RtmpClient#371]
请问是否支持英伟达显卡进行硬解码，该如何设置呢？

**Comment by bosscheng** [comment]
支持的，浏览器开启解码硬加速配置就行了。在使用mse解码的时候，会用到显卡进行硬解码的

**Comment by shancaidazf** [comment]
是的，支持英伟达硬解码。但是有个问题，我一个页面开启20个任务，使用英伟达硬解码，为什么cpu还是占用90%-100%呢

**Comment by bosscheng** [comment]
你看下解码器使用的是不是软解码，还是硬解码，通常软解码才会使用到cpu。
