### ISSUE TITLE
视频编码格式支持相关问题 TypeError: Failed to execute configure’on 'VideoDecoder'; Failed to parse codec string

### ISSUE THREAD

**Issue by eatkid** [langhuihui/H5RtmpClient#373]
你好，我目前使用播放器来播放推流，在外网测试环境使用测试流无问题，在内网生产环境会报错，下面是详细的报错信息，请问应该如何排查相关问题？

使用 chrome 浏览器会报错
TypeError: Failed to execute configure’on 'VideoDecoder'; Failed to parse codec string
![WechatIMG37](https://github.com/langhuihui/jessibuca/assets/24886050/02c28bb4-b32c-48c5-a00f-d452283f5935)

考虑到浏览器支持的问题，更换浏览器依然无法播放，使用火狐浏览器 firefox尝试播放，提示 codec not support: 2
![WechatIMG38](https://github.com/langhuihui/jessibuca/assets/24886050/058ae05e-3f02-4ecd-a103-3aca0d29040e)

内网的具体环境如下：

客户端使用 WINDOWS7 chrome 版本 103 Firefox 版本99.0

流是监控的 RTSP 流，通过后端转码成 flv 后推流

**Comment by bosscheng** [comment]
已修复
