### ISSUE TITLE
希望增加一个显示 / 隐藏工具栏的api

### ISSUE THREAD

**Issue by Ryan-CW-Code** [langhuihui/H5RtmpClient#379]
如题，我们手机上使用没有全屏的时候显示工具栏，全屏后使用我们的工具栏。
但是没有直接控制的api，我们只能把没有全屏的Jessibuca对象销毁重新配置工具栏所有属性为false，这样子就导致切换的时候画面延时大，卡顿感强烈

**Comment by Ryan-CW-Code** [comment]
@bosscheng 大佬帮忙看看这个😀

**Comment by bosscheng** [comment]
我有思考过这个，如果添加了这个api，会有一个问题，就是隐藏的时候，显示的窗口底部下面会有一块区域是空的，需要把原本的渲染窗口重新拉长。体验上面怪怪的。

**Comment by bosscheng** [comment]
然后显示的时候，又需要把渲染窗口挤上去。

**Comment by Ryan-CW-Code** [comment]
> 然后显示的时候，又需要把渲染窗口挤上去。

播放器应该不用考虑这个问题，隐藏工具栏的副作用应该给用户来解决

**Comment by bosscheng** [comment]
这是播放器内部的逻辑

**Comment by Ryan-CW-Code** [comment]
> 这是播放器内部的逻辑

视频播放区域的大小一般用户都会进行控制
按播放器内部逻辑来的话隐藏工具栏时，画面可以根据用户配置的拉伸模式进行更改。

**Comment by bosscheng** [comment]
@Ryan-CW-Code 新版本 已经支持了
