### ISSUE TITLE
linux系统下火狐和Edge浏览器报错：SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by Se7enQ** [langhuihui/H5RtmpClient#38]
![8D7633CD-0089-4ee3-B365-3BD3C0C232D2](https://user-images.githubusercontent.com/22390966/123212584-92cf4580-d4f7-11eb-884c-c440545c76dc.png)
![2F05F833-66D4-4d43-9C80-EEEAF6DB0230](https://user-images.githubusercontent.com/22390966/123212600-96fb6300-d4f7-11eb-920c-c50c224a0cda.png)

上面是浏览器版本

**Comment by bosscheng** [comment]
@Se7enQ 问题已经修复了。
