### ISSUE TITLE
webFullscreen在iOS版微信内失效。

### ISSUE THREAD

**Issue by dadait** [langhuihui/H5RtmpClient#381]
webFullscreen在iOS版微信内失效，设置了useWebFullScreen:ture，但是在调用setFullscreen(true)，无任何效果。

使用了官方的DEMO [https://jessibuca.com/mobile-fullscreen.html](https://jessibuca.com/mobile-fullscreen.html )测试，也是没有全屏效果。

**Comment by bosscheng** [comment]
![ios-wechat](https://github.com/langhuihui/jessibuca/assets/2195154/d4f5fd7e-79e5-40ed-a00a-9b6c962fd8fc)
我c测试了下，没问题嘛

**Comment by dadait** [comment]
@bosscheng 抱歉，之前描述有误，iPhone 微信中没问题，只是在iPad微信中调用setFullscreen无响应。

已经找到并解决问题了，修改了下isMobile方法中的正则表达式，在其中加入了`ipad`。

```javascript
function isMobile() {
    return /iphone|ipod|android.*mobile|windows.*phone|blackberry.*mobile|ipad/i.test(window.navigator.userAgent.toLowerCase());
}
```

**Comment by bosscheng** [comment]
@dadait 新版本已经修复了
