### ISSUE TITLE
H265视频无法播放，使用官方测试demo

### ISSUE THREAD

**Issue by StephonDNG** [langhuihui/H5RtmpClient#387]
我这边使用
http://jessibuca.monibuca.com/mobile-fullscreen.html 测试播放一个H265视频链接，一直转圈无法播放，没有报错信息

**Comment by bosscheng** [comment]
@DongJigong f12，看下控制台日志，发给我

**Comment by DongJigong** [comment]
Jessibuca: [Player] init
debug.js:5 Jessibuca: [CanvasVideo] init
audioContextLoader.js:14 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
AudioContextLoader @ audioContextLoader.js:14
audioContextLoader.js:30 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
AudioContextLoader @ audioContextLoader.js:30
audioContextLoader.js:263 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
audioEnabled @ audioContextLoader.js:263
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [Recorder] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Control] init
debug.js:5 Jessibuca: [Player options] {"videoBuffer":200,"videoBufferDelay":1000,"isResize":false,"isFullResize":false,"isFlv":false,"debug":true,"hotKey":false,"loadingTimeout":10,"heartTimeout":5,"timeout":10,"loadingTimeoutReplay":true,"heartTimeoutReplay":true,"loadingTimeoutReplayTimes":3,"heartTimeoutReplayTimes":3,"supportDblclickFullscreen":false,"showBandwidth":true,"keepScreenOn":false,"isNotMute":false,"hasAudio":true,"hasVideo":true,"operateBtns":{"fullscreen":true,"screenshot":true,"play":true,"audio":true},"controlAutoHide":false,"hasControl":true,"loadingText":"加载中","background":"","decoder":"decoder.js","url":"","rotate":0,"forceNoOffscreen":true,"hiddenAutoPause":false,"protocol":1,"demuxType":"flv","useWCS":false,"wcsUseVideoRender":true,"useMSE":false,"useOffscreen":false,"autoWasm":true,"wasmDecodeErrorReplay":true,"openWebglAlignment":false,"wasmDecodeAudioSyncVideo":false,"recordType":"webm","useWebFullScreen":false,"text":""}
debug.js:5 Jessibuca: [jessibuca] _initPlayer {"videoBuffer":200,"videoBufferDelay":1000,"isResize":false,"isFullResize":false,"isFlv":false,"debug":true,"hotKey":false,"loadingTimeout":10,"heartTimeout":5,"timeout":10,"loadingTimeoutReplay":true,"heartTimeoutReplay":true,"loadingTimeoutReplayTimes":3,"heartTimeoutReplayTimes":3,"supportDblclickFullscreen":false,"showBandwidth":true,"keepScreenOn":false,"isNotMute":false,"hasAudio":true,"hasVideo":true,"operateBtns":{"fullscreen":true,"screenshot":true,"play":true,"audio":true},"controlAutoHide":false,"hasControl":true,"loadingText":"加载中","background":"","decoder":"decoder.js","url":"","rotate":0,"forceNoOffscreen":true,"hiddenAutoPause":false,"protocol":1,"demuxType":"flv","useWCS":false,"wcsUseVideoRender":true,"useMSE":false,"useOffscreen":false,"autoWasm":true,"wasmDecodeErrorReplay":true,"openWebglAlignment":false,"wasmDecodeAudioSyncVideo":false,"recordType":"webm","useWebFullScreen":false,"text":""}
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player events] load undefined
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
decoder.js:8045 Jessibuca: [worker] init
mobile-fullscreen.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
mobile-fullscreen.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
mobile-fullscreen.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [FetchStream] fetchStream https://v.car900.com/adasaddrNew/adas/2024-07/20240712/294/14/470992/02_01_a104_00_1811549300971671552.mp4 {}
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://v.car900.com/adasaddrNew/adas/2024-07/20240712/294/14/470992/02_01_a104_00_1811549300971671552.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://v.car900.com/adasaddrNew/adas/2024-07/20240712/294/14/470992/02_01_a104_00_1811549300971671552.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://v.car900.com/adasaddrNew/adas/2024-07/20240712/294/14/470992/02_01_a104_00_1811549300971671552.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://v.car900.com/adasaddrNew/adas/2024-07/20240712/294/14/470992/02_01_a104_00_1811549300971671552.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://v.car900.com/adasaddrNew/adas/2024-07/20240712/294/14/470992/02_01_a104_00_1811549300971671552.mp4 {}
worker.js:230 Jessibuca: [worker] init

**Comment by StephonDNG** [comment]
Jessibuca: [Player] init
debug.js:5 Jessibuca: [CanvasVideo] init
audioContextLoader.js:14 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
AudioContextLoader @ audioContextLoader.js:14
audioContextLoader.js:30 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
AudioContextLoader @ audioContextLoader.js:30
audioContextLoader.js:263 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
audioEnabled @ audioContextLoader.js:263
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [Recorder] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Control] init
debug.js:5 Jessibuca: [Player options] {"videoBuffer":200,"videoBufferDelay":1000,"isResize":false,"isFullResize":false,"isFlv":false,"debug":true,"hotKey":false,"loadingTimeout":10,"heartTimeout":5,"timeout":10,"loadingTimeoutReplay":true,"heartTimeoutReplay":true,"loadingTimeoutReplayTimes":3,"heartTimeoutReplayTimes":3,"supportDblclickFullscreen":false,"showBandwidth":true,"keepScreenOn":false,"isNotMute":false,"hasAudio":true,"hasVideo":true,"operateBtns":{"fullscreen":true,"screenshot":true,"play":true,"audio":true},"controlAutoHide":false,"hasControl":true,"loadingText":"加载中","background":"","decoder":"decoder.js","url":"","rotate":0,"forceNoOffscreen":true,"hiddenAutoPause":false,"protocol":1,"demuxType":"flv","useWCS":false,"wcsUseVideoRender":true,"useMSE":false,"useOffscreen":false,"autoWasm":true,"wasmDecodeErrorReplay":true,"openWebglAlignment":false,"wasmDecodeAudioSyncVideo":false,"recordType":"webm","useWebFullScreen":false,"text":""}
debug.js:5 Jessibuca: [jessibuca] _initPlayer {"videoBuffer":200,"videoBufferDelay":1000,"isResize":false,"isFullResize":false,"isFlv":false,"debug":true,"hotKey":false,"loadingTimeout":10,"heartTimeout":5,"timeout":10,"loadingTimeoutReplay":true,"heartTimeoutReplay":true,"loadingTimeoutReplayTimes":3,"heartTimeoutReplayTimes":3,"supportDblclickFullscreen":false,"showBandwidth":true,"keepScreenOn":false,"isNotMute":false,"hasAudio":true,"hasVideo":true,"operateBtns":{"fullscreen":true,"screenshot":true,"play":true,"audio":true},"controlAutoHide":false,"hasControl":true,"loadingText":"加载中","background":"","decoder":"decoder.js","url":"","rotate":0,"forceNoOffscreen":true,"hiddenAutoPause":false,"protocol":1,"demuxType":"flv","useWCS":false,"wcsUseVideoRender":true,"useMSE":false,"useOffscreen":false,"autoWasm":true,"wasmDecodeErrorReplay":true,"openWebglAlignment":false,"wasmDecodeAudioSyncVideo":false,"recordType":"webm","useWebFullScreen":false,"text":""}
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player events] load undefined
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
decoder.js:8045 Jessibuca: [worker] init
mobile-fullscreen.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
mobile-fullscreen.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
mobile-fullscreen.html:1 Unchecked runtime.lastError: The message port closed before a response was received.
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [FetchStream] fetchStream https://ttt.mp4 {}
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://ttt.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://ttt.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://ttt.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://ttt.mp4 {}
decoder.js:8045 Jessibuca: [worker] init
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [player events] stats {"buf":0,"fps":0,"abps":0,"vbps":0,"ts":0}
debug.js:5 Jessibuca: [player events] performance 0
debug.js:5 Jessibuca: [FetchStream] destroy
debug.js:5 Jessibuca: [CommonDemux] destroy
debug.js:5 Jessibuca: [FlvDemux] destroy
debug.js:5 Jessibuca: [decoderWorker] destroy
decoder.js:8115 Jessibuca: [worker]: close
debug.js:5 Jessibuca: [player events] loading false
debug.js:5 Jessibuca: [AudioContext] destroy
debug.js:5 Jessibuca: [player events] timeout loadingTimeout
debug.js:5 Jessibuca: [player events] loadingTimeout undefined
debug.js:5 Jessibuca: [Jessibuca] loading timeout replay time is 0
debug.js:5 Jessibuca: [player events] loading true
debug.js:5 Jessibuca: [FetchStream] init
debug.js:5 Jessibuca: [AudioContext] init
debug.js:5 Jessibuca: [common dumex] init Interval
debug.js:5 Jessibuca: [FlvDemux] init
debug.js:5 Jessibuca: [decoderWorker] init
debug.js:5 Jessibuca: [Player] waiting decoderWorker init
debug.js:5 Jessibuca: [decoderWorker] onmessage: init
debug.js:5 Jessibuca: [player] has loaded
debug.js:5 Jessibuca: [player events] decoderWorkerInit undefined
debug.js:5 Jessibuca: [Player] decoderWorker init success
debug.js:5 Jessibuca: [FetchStream] fetchStream https://ttt.mp4 {}
worker.js:230 Jessibuca: [worker] init

**Comment by bosscheng** [comment]
@DongJigong 开源版不支持MP4协议，可以试下pro https://jessibuca.com/player-pro.html 测试看看
