### ISSUE TITLE
最新发布版的多窗口例子：multi-demo.html，里面的“销毁（ALL）”功能报错

### ISSUE THREAD

**Issue by disalong** [langhuihui/H5RtmpClient#388]
官网的例子不报错，但是最新的发布版本报错
![微信截图_20240719114040](https://github.com/user-attachments/assets/ae536da6-01ba-49ab-a637-186e1572212a)

**Comment by bosscheng** [comment]
@disalong 
https://jessibuca.com/pro.zip  更新下就行了

**Comment by disalong** [comment]
> @disalong https://jessibuca.com/pro.zip 更新下就行了

感谢！
