### ISSUE TITLE
更新新版本后decoder.wasm 一直显示在待处理

### ISSUE THREAD

**Issue by remiliyaScarlet** [langhuihui/H5RtmpClient#389]
![image](https://github.com/user-attachments/assets/38f6875e-2a4c-4c41-897f-222fc7b37730)

**Comment by bosscheng** [comment]
@remiliyaScarlet  我测试了官网是没问题的。

**Comment by remiliyaScarlet** [comment]
> @remiliyaScarlet 我测试了官网是没问题的。

![image](https://github.com/user-attachments/assets/9c8de975-9f97-47e9-a915-02988d3851ce)
我测试官网的也没播放出来

**Comment by remiliyaScarlet** [comment]
> @remiliyaScarlet 我测试了官网是没问题的。

![image](https://github.com/user-attachments/assets/acd1a78d-6720-4f27-b94a-989059e98a53)
用回7-26的版本就没问题
