### ISSUE TITLE
无法播放用zlmediakit搭建的webrtc流

### ISSUE THREAD

**Issue by zhujianLeo** [langhuihui/H5RtmpClient#390]
我通过zlmediakit 搭建了一个流媒体服务器 尝试通过
http://jessibuca.monibuca.com/pro/demo-webrtc.html 这个demo去播放webrtc流 
但是无法播放
![Uploading Snipaste_2024-08-14_11-40-37.jpg…]()

**Comment by bosscheng** [comment]
@zhujianLeo  http://jessibuca.com/pro/demo-webrtc.html 用这个地址，webrtc 需要https 环境的。
