### ISSUE TITLE
jessibuca 偶现白屏

### ISSUE THREAD

**Issue by GalinaGao123** [langhuihui/H5RtmpClient#394]
![image](https://github.com/user-attachments/assets/aef7b388-908e-4b63-a152-5b5417a708c7)
偶尔会复现这种情况，浏览器控制台报错  Cannot read properties of null (reading 'createShader')

**Comment by bosscheng** [comment]
webgl 丢失了

**Comment by bosscheng** [comment]
@GalinaGao123 给我个完整的日志信息，我看下把这种异常抛出来。好让业务层知道。

**Comment by GalinaGao123** [comment]
![jessibuca报错信息](https://github.com/user-attachments/assets/998a9f98-ab2c-4633-8684-327c8828974c)
这是最近一次复现的时候。控制台报的错

**Comment by bosscheng** [comment]
webgl 丢失上下文了。

**Comment by GalinaGao123** [comment]
上面是最新版的保错。这个是旧版的报错
![image](https://github.com/user-attachments/assets/91a57f9a-59fd-4862-a044-12dc5388096a)

请问这种有没有啥解决办法呢

**Comment by bosscheng** [comment]
@GalinaGao123 可以更新到最新版本看下，目前播放器会监听这种异常，并抛出，不会这样白屏下去。

**Comment by GalinaGao123** [comment]
版本更新到3.2.12 还是一直白屏呢。麻烦大佬帮忙看下。
![image](https://github.com/user-attachments/assets/aa33b36d-ff04-4790-b9e0-16e607ba33d3)

**Comment by HuangShun** [comment]
> 版本更新到3.2.12 还是一直白屏呢。麻烦大佬帮忙看下。 ![image](https://private-user-images.githubusercontent.com/16570238/371833340-aa33b36d-ff04-4790-b9e0-16e607ba33d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTkzMjUsIm5iZiI6MTczMjY5OTAyNSwicGF0aCI6Ii8xNjU3MDIzOC8zNzE4MzMzNDAtYWEzM2IzNmQtZmYwNC00NzkwLWI5ZTAtMTZlNjA3YmEzM2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA5MTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNGFkNGQzNTk5YzhiYWY4YjQ1MDY5YWFmODBmZGNjMjVkZDM0YWQ4ZDdlODQyYTljMjk1MWExYWU3ODAxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FEgm2U_sZOrUBGRt2OVELBUKFfEac3M-AU2p_d4aJ1w)

我这也报了这个错误，出现的概率很高

**Comment by bosscheng** [comment]
更新到： https://github.com/langhuihui/jessibuca/releases/tag/v3.3.15 试试看

**Comment by HuangShun** [comment]
> 更新到： https://github.com/langhuihui/jessibuca/releases/tag/v3.3.15 试试看

我现在就是用的这个版本

**Comment by GalinaGao123** [comment]
刚刚有出现了这个问题。init webgl 失败.  我现在是在error里面重新初始化的。大概20次失败了，终于加载出来了
