### ISSUE TITLE
Jessibuca ReactJs version Available?

### ISSUE THREAD

**Issue by Rahul-ambiplatforms** [langhuihui/H5RtmpClient#397]

**Comment by bosscheng** [comment]
@Rahul-ambiplatforms  https://github.com/bosscheng/jessibuca-react-demo/tree/v3

**Comment by Rahul-ambiplatforms** [comment]
> @Rahul-ambiplatforms  https://github.com/bosscheng/jessibuca-react-demo/tree/v3
> 
> 
> 
> 

And jessibuca-pro is available for reactjs?

**Comment by bosscheng** [comment]
@Rahul-ambiplatforms  https://github.com/bosscheng/jessibuca-react-demo/tree/pro

look it
