### ISSUE TITLE
3.3.12 播放http-flv流，pause后再play会一直载入中，官网demo3.2.12正常

### ISSUE THREAD

**Issue by jaelys** [langhuihui/H5RtmpClient#400]
开源版 3.3.12 播放http-flv流，pause后再play会一直载入中，官网demo 3.2.12正常，PC 移动端都会发生

```
Jb: [Player] init and version is "3.3.12"
Jb: [Player] use MSE
Jessibuca version: "3.3.12"
..........................................
timeUpdate,old,new,timestamp 6551 6618 67
Jb: [Video] waiting
Jb: [Video] canplay
Jb: [AudioContext] bufferList is large: 51
decoderWorker.onmessage 
timeUpdate,old,new,timestamp 6618 6879 261
Jb: [AudioContext] bufferList is large: 51
decoderWorker.onmessage 
timeUpdate,old,new,timestamp 6879 7145 266
Jb: [AudioContext] bufferList is large: 51
decoderWorker.onmessage
Jb: [FetchStream] destroy
Jb: [CommonDemux] destroy
Jb: [FlvDemux] destroy
Jb: [decoderWorker] destroy
Jb: [worker]: close
Jb: [MediaSource] destroy
Jb: [player events] playing false
Jb: [player events] volumechange 0
Jb: [player events] pause undefined
on pause
Jb: [AudioContext] destroy
19 timeUpdate,old,new,timestamp 7145 7305 160
Jb: [player events] loading true
Jb: [FetchStream] init
Jb: [AudioContext] init
Jb: [common dumex] init Interval
Jb: [FlvDemux] init
Jb: [MediaSource] init
Jb: [decoderWorker] init
Jb: [Player] waiting decoderWorker init
Jb: [player events] mute false
on mute false
on mute2 false
Jb: [player events] volumechange 1
Jb: [player events] volume 1
Jb: [player events] mseSourceClose undefined
timeUpdate,old,new,timestamp 7305 11282 3977
Jb: [player events] mseSourceOpen undefined
Jb: [decoderWorker] onmessage: init
Jb: [player] has loaded
Jb: [player events] decoderWorkerInit undefined
Jb: [worker] init
```

停止在这没有信息了，UI加载中一直转圈

**Comment by kewab** [comment]
解决了吗？我这也遇到此类问题了，暂停再播放就会出现 `jessibuca.js:1 Uncaught (in promise) init() failed and player is destroyed or closed` ,官网的在线DEMO是正常的，但是我本地运行官方提供的DEMO就会出现如下错误。

<img width="1594" alt="CleanShot 2024-10-17 at 09 17 43@2x" src="https://github.com/user-attachments/assets/2a03ad74-805b-499b-8cad-20ed659a8053">

**Comment by bosscheng** [comment]
@kewab 整个最简单的demo 给我，我复现看下

**Comment by kewab** [comment]
> @kewab 整个最简单的demo 给我，我复现看下

这个问题找到了，应该是DEMO里的配置少配置了一行`decoder:'/jessibuca/decoder.js'`，加上这一行之后就没有这个错误了。
但是感觉暂停后重新播放好像有时候不是从暂停的位置开始播放的，不知道为什么

**Comment by jaelys** [comment]
> > @kewab 整个最简单的demo 给我，我复现看下
> 
> 这个问题找到了，应该是DEMO里的配置少配置了一行`decoder:'/jessibuca/decoder.js'`，加上这一行之后就没有这个错误了。 但是感觉暂停后重新播放好像有时候不是从暂停的位置开始播放的，不知道为什么

我是有设置 decoder: "/js/decoder.js" 的，还是一样的问题，官网vue ts的范例，更新到版本3.3.12，
pause再play会卡加载中转圈，但再次点击play按钮，画面会渲染出来，但转圈一直存在无法消失

**Comment by kewab** [comment]
> > > @kewab 整个最简单的demo 给我，我复现看下
> 
> > 
> 
> > 这个问题找到了，应该是DEMO里的配置少配置了一行`decoder:'/jessibuca/decoder.js'`，加上这一行之后就没有这个错误了。 但是感觉暂停后重新播放好像有时候不是从暂停的位置开始播放的，不知道为什么
> 
> 
> 
> 我是有设置 decoder: "/js/decoder.js" 的，还是一样的问题，官网vue ts的范例，更新到版本3.3.12

解决了吗？其实我也遇到了，我直接把这个暂停操作给隐藏了

**Comment by jaelys** [comment]
> > > > @kewab 整个最简单的demo 给我，我复现看下
 
> > 我是有设置 decoder: "/js/decoder.js" 的，还是一样的问题，官网vue ts的范例，更新到版本3.3.12
> 
> 解决了吗？其实我也遇到了，我直接把这个暂停操作给隐藏了

我替换官网在线DEMO的版本3.2.12，就正常了

**Comment by kewab** [comment]
> > > > > @kewab 整个最简单的demo 给我，我复现看下
> 
> > > 我是有设置 decoder: "/js/decoder.js" 的，还是一样的问题，官网vue ts的范例，更新到版本3.3.12
> > 
> > 
> > 解决了吗？其实我也遇到了，我直接把这个暂停操作给隐藏了
> 
> 我替换官网在线DEMO的版本3.2.12，就正常了

你这算是降级了吧，我现在使用的是3.3.12，官方发布最新版本我看是3.3.13。是特意降级到3.2.12的吗？

**Comment by bosscheng** [comment]
可以试下最新版本，如果还有问题，可以群里反馈给我。

**Comment by bosscheng** [comment]
@jaelys @kewab 更新到最新版本就行了
