### ISSUE TITLE
在有缩放的div中，播放器的宽高不正确

### ISSUE THREAD

**Issue by GGBond99999** [langhuihui/H5RtmpClient#401]
getBoundingClientRect获取缩放后的宽高，clientHeight获取的是缩放前的
官方demo中 .root上加一行transform: scale(1.14323, 1.15417);
`
  Object.defineProperty(player, 'rect', {
        get: () => {

            const clientRect = player.$container.getBoundingClientRect()

            clientRect.width = player.$container.clientWidth

            clientRect.height =player.$container.clientHeight

            return clientRect;

        },
    });

`

**Comment by bosscheng** [comment]
更新到最新版本看看，最新版本已经处理过这个情况了。
