### ISSUE TITLE
播放http-flv和ws-raw流，播几秒钟后就报错，然后视频就停了

### ISSUE THREAD

**Issue by Marco-ding** [langhuihui/H5RtmpClient#403]
用开源最新版3.3.12播放http-flv和ws-raw流，播几秒钟后就报错，然后视频就停了，报警告如下：jessibuca.js:1 Jb: [jessibuca] pause ->  play and play error init() failed and player is destroyed or closed

![5016f38b-ff92-4c9e-b1a6-4795b24a7cee](https://github.com/user-attachments/assets/0cbf20e8-9761-4bda-b21b-36249a22645c)

但是同一个推流链接放到官网上播放，不会有上述报错，就会卡顿，然后会重新加载

https://github.com/user-attachments/assets/6a3de6eb-4049-44f0-802b-12ed8391a8c7
日志如下：
![222](https://github.com/user-attachments/assets/26a99382-36ff-414e-bbef-ce5f14877d28)

**Comment by Marco-ding** [comment]
放在官网pro播放器里，就很正常，不卡，也不会报错停掉

**Comment by bosscheng** [comment]
好的 我来看下

**Comment by bosscheng** [comment]
@Marco-ding 已经修复了，可以更新到最新版本看下了。
