### ISSUE TITLE
播放暂停后重新播放，视频的loading 状态一直在

### ISSUE THREAD

**Issue by liuchenzyi** [langhuihui/H5RtmpClient#404]
暂停后点击播放一直处于loading 状态，视频画面在正常播放，play 事件也没有触发
资版本为为2024年11月2日在官网下载的最新源码

**Comment by bosscheng** [comment]
已修复

**Comment by marvin1023** [comment]
2024-11-18 官网下载的 dist 里面的还是 loading 状态一直在

**Comment by bosscheng** [comment]
@marvin1023 加我wx，把完整的日志发给我看下
