### ISSUE TITLE
请问为什么最多支持同屏16个播放器呢？

### ISSUE THREAD

**Issue by litchia** [langhuihui/H5RtmpClient#405]

**Comment by bosscheng** [comment]
@litchia  https://jessibuca.com/document.html#%E5%85%B3%E4%BA%8E%E6%8A%A5%E2%80%9Ctoo-many-active-webgl-contexts-oldest-context-will-be-lost%E2%80%9D-%E9%94%99%E8%AF%AF
可以看下
