### ISSUE TITLE
视频流自动重试无法响应类型为streamEnd的报错

### ISSUE THREAD

**Issue by singlemonkey** [langhuihui/H5RtmpClient#406]
const option = {
  autoWasm: true,
  wasmDecodeAudioSyncVideo: true,
  wasmDecodeErrorReplay: true,
  hasAudio: false,
  useMSE: true,
  useWCS: false,
  controlAutoHide: false,
  isResize: false,
  loadingText: "请稍等, 视频加载中......",
  timeout: 10,
  loadingTimeout: 20,
  loadingTimeoutReplay: true,
  loadingTimeoutReplayTimes: -1,
  heartTimeout: 20,
  heartTimeoutReplay: true,
  heartTimeoutReplayTimes: -1
}

播放器配置如上，设置了超时时间和无限重试，但是在直接拔掉摄像头之后，从zlmediakit推出来的流会直接断掉，同时播放器接收到streamEnd报错，但视频播放在视频流重新注册完成后，并不会自动执行。

**Comment by bosscheng** [comment]
播放器只会在地址通的情况下进行重试，这种直接断开了，是异常streamEnd，如果这种业务逻辑下，需要重试，需要业务层自己去监听 streamEnd 这个事件，然后自己重试就行了。记得最好设置个延迟时间去重试，不然如果这个流地址一直是不通的，会不停的死循环重试的，会导致浏览器异常卡死。
