### ISSUE TITLE
jessibuca播放ws FLV视频流，报错 jessibuca.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'postMessage')

### ISSUE THREAD

**Issue by zuoxiaoyi** [langhuihui/H5RtmpClient#407]
![微信图片_20241225151649](https://github.com/user-attachments/assets/6acbf052-384e-4e3c-845a-d0838cf43418)
拉取到直播流之后，播放大概2-5分钟具体时间范围内，这段时间范围内流播放到一定时间就会报错
 jessibuca.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'postMessage')
 
 具体代码的配置项为：
 
![image](https://github.com/user-attachments/assets/7650a10d-26b1-44a2-add9-3b97e1902134)

![image](https://github.com/user-attachments/assets/d3e0af55-90ab-4f2e-b181-8f9194a7403a)
源码报错处，已告知作者，盼解决！这里感谢作者

**Comment by bosscheng** [comment]
已修复
