### ISSUE TITLE
url 在pc端能播放，安卓webview无法播放视频。

### ISSUE THREAD

**Issue by zhengxu632** [langhuihui/H5RtmpClient#408]
播
![DINGTALK_IM_2647925348 JPG](https://github.com/user-attachments/assets/b1b758a2-1bd7-43ec-894b-c3194cfe64a2)

放地址ws://192.168.1.239:8044/rtp/34020000002000000001_34020100001320000235.live.flv
下载的离线demo，pc端浏览器中播放能成功，在安卓webview下无法播放是什么原因引起的：播放的debug日志如图所示

**Comment by bosscheng** [comment]
@zhengxu632 官网加群，群里私聊我，我看下啥情况
