### ISSUE TITLE
index.js:3 WebSocket connection to 'ws://localhost/live/test.flv' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by yangfangfang1204** [langhuihui/H5RtmpClient#47]
第一步：npm i；
第二步： npm run dev；
第三步：打开chrome 输入 http://localhost:3000/
第四步：点击打开播放器；
第五步：{ws-raw 即ws://localhost/live/test (该协议只能对接monibuca服务器)
ws-flv 即ws://localhost/live/test.flv
http-flv 即http://localhost/live/test.flv}三个url任选一个输入，点击播放。

三种方式，console中都有报错：index.js:3 WebSocket connection to 'ws://localhost:8080/jessica/live/rtc' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

哪个步骤出问题了吗？还是需要配置什么？

**Comment by bosscheng** [comment]
@yangfangfang1204 ws://localhost:8080/jessica/live/rtc得保证服务得通，ERR_CONNECTION_REFUSED 服务根本不可达。
