### ISSUE TITLE
rtmp推流中更改分辨率后绿屏

### ISSUE THREAD

**Issue by yinxchun** [langhuihui/H5RtmpClient#50]
rtmp正常推流，更改分辨率（高-》低）后，画面会一直绿屏，刷新页面重新打开播放器也是绿屏。vlc及西瓜播放器此时都播放正常。低改高不会，切换摄像头也不会。录制的视频用vlc播放正常。
请问这个问题该如何解决？
网上找资料，有说是因为关键帧和sps、pps的信息，播放器解析失败的问题。

**Comment by langhuihui** [comment]
标准的RTMP协议是不支持修改分辨率的，这需要特殊处理一下，就是要处理再次发送AVC的序列帧的问题。直播流可以处理，但是录制流可能会有影响，Flv的头部会存储序列帧，中间放序列帧的情况可能会引起一些问题。

**Comment by yinxchun** [comment]
嗯，反复测试发现是分辨率的问题，设为标准分辨率就没有绿屏的问题了。
彻底解决还是得更改配置后重新推流。

**Comment by yinxchun** [comment]
处理再次发送AVC的序列帧的问题，这个在哪儿处理？
