### ISSUE TITLE
不支持只有aac音频或者只有h264视频的源

### ISSUE THREAD

**Issue by tyisme614** [langhuihui/H5RtmpClient#56]
之前另一位同学的 issue 被 close了，这里遇到了同样的问题，纯 aac音频无法播放，请教。

**Comment by bosscheng** [comment]
@tyisme614 提供可以测试的demo，或者播放地址给我。我调试看下，上一个同学就是不理我，我才把issue 关掉的。

**Comment by tyisme614** [comment]
@bosscheng 

方便给一个邮箱吗？
我把demo软件发过去，可以用我的平台测试

**Comment by bosscheng** [comment]
@tyisme614 25022549@qq.com

**Comment by tyisme614** [comment]
@bosscheng 邮件已发，我自己写了一个纯音频传输 rtmp数据的app，然后可以推送数据到我的测试平台上，用vlc播放是没问题的，但是播放器无法播放

**Comment by yinxchun** [comment]
同样发现声音播放比画面延时太多，有差不多一分钟

**Comment by bosscheng** [comment]
@yinxchun 有测试链接嘛。我去看下。

**Comment by tyisme614** [comment]
@bosscheng 请问有什么进展吗？

**Comment by tyisme614** [comment]
该问题已经解决，close issue。

**Comment by tyisme614** [comment]
@bosscheng 修改的代码，已提交PR，支持纯音频播放。
