### ISSUE TITLE
调用operateBtns中的截图，生成的图片文件名称有问题

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#57]
调用operateBtns中的截图生成的图片文件名称前端带有undefined，例如undefined1629948287723.png。
![1629948949(1)](https://user-images.githubusercontent.com/39176130/130896449-f1695c4f-89cb-496a-b0c8-70d063910808.png)

**Comment by bosscheng** [comment]
@yu1183688986 tks 已经修复。
