### ISSUE TITLE
播放视频后调用clearView()、close()、jessibuca.destroy()都无法将画布清空，背景还是显示视频的最后画面图像；

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#58]
播放视频后调用clearView()、close()、jessibuca.destroy()都无法将画布清空，背景还是显示视频的最后画面图像；

**Comment by bosscheng** [comment]
@yu1183688986 把离屏渲染 forceNoOffscreen 设置为true 了就可以了。
