### ISSUE TITLE
Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by XusCloud** [langhuihui/H5RtmpClient#59]
流在拉，但是没有图像，报错信息Uncaught RuntimeError: memory access out of bounds
想问下是什么原因导致的？

**Comment by bosscheng** [comment]
@XusCloud 方便提供一个测试连接嘛。定位下问题。

**Comment by bosscheng** [comment]
@XusCloud 更新到最新版本试下，应该已经修复了。
