### ISSUE TITLE
播放视频的音频有电流声请问怎么解决

### ISSUE THREAD

**Issue by bondzasd** [langhuihui/H5RtmpClient#6]
播放视频的音频有电流声请问怎么解决

**Comment by UEhQZXI** [comment]
你在IOS浏览器能播放吗?

**Comment by langhuihui** [comment]
可以



---原始邮件---
发件人: "Max Lu"<notifications@github.com&gt;
发送时间: 2020年9月7日(周一) 下午5:13
收件人: "langhuihui/jessibuca"<jessibuca@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [langhuihui/jessibuca] 播放视频的音频有电流声请问怎么解决 (#6)




 
你在IOS浏览器能播放吗?

**Comment by UEhQZXI** [comment]
> 可以
> […](#)
> ---原始邮件---发件人：“ Max Lu” <notifications@github.com> 发送时间：2020年9月7日（周一）下午5:13收件人：“ langhuihui / jessibuca” <jessibuca@noreply.github.com> ;; 抄送：“ Subscribed” <subscribed@noreply.github.com> ;; 主题：Re：[langhuihui / jessibuca]播放视频的音频有电流声请问怎么解决（[＃6](https://github.com/langhuihui/jessibuca/issues/6)）你在IOS浏览器能播放吗？—您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

作者您好! 我的项目是用WS来传输音频流, 电脑上可以直接播放, 但是在IOS的浏览器上就播放不了, 也没有报错, 就是没声音, 不知道什么原因

**Comment by EvanceWong** [comment]
楼上的解决了么，我也遇到了这个问题

**Comment by UEhQZXI** [comment]
> 楼上的解决了么，我也遇到了这个问题

没有, 你解决了吗?

**Comment by bosscheng** [comment]
电流声是因为audio context连接播放造成的。目前浏览器不支持live stream的audio context，因此会有此类问题。
