### ISSUE TITLE
调用resize()方法浏览器会卡住直至崩溃。

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#60]
我的配置
`var jessibucaConfig = {
        container: document.getElementById("myVideodiv"),
	videoBuffer : 0.5, // 最大缓冲时长，单位秒
	isResize : false,
	decoder : "xxxx/jessibuca/index.js",
	timeout : 60,
	loadingText : "加载中",
	hasAudio : true, //typeof (this.hasAudio) =="undefined"? true: this.hasAudio,
	debug : false,
	supportDblclickFullscreen : true, // 是否支持屏幕的双击事件，触发全屏，取消全屏事件。
	//showBandwidth: true,//显示网速
	operateBtns : {
		fullscreen : true,
		screenshot : true,
		play : true,
		audio : true,
	},
	record : "record",
	vod : true,
	forceNoOffscreen : true,
	isNotMute : false,
};`
当我修改了container的宽高大小时候再调用resize()方法调正视频画面大小会导致浏览器卡住直至崩溃。

**Comment by bosscheng** [comment]
@yu1183688986 方便提供一个测试demo嘛，我这边测试了下，没发现resize问题。

**Comment by yu1183688986** [comment]
> @yu1183688986 方便提供一个测试demo嘛，我这边测试了下，没发现resize问题。

打扰了 我自己的问题，我重新试了一下可以了。
