### ISSUE TITLE
浏览器崩溃

### ISSUE THREAD

**Issue by Smallkserver** [langhuihui/H5RtmpClient#61]
1080P视频，H265格式，播放一段时间或者刚开始加载偶发 整个浏览器崩溃

**Comment by bosscheng** [comment]
@Smallkserver 方便提供一个测试地址或者测试的视频看下嘛。

**Comment by bosscheng** [comment]
@Smallkserver 更新到最新版本试下。问题应该已经修复了。

**Comment by Smallkserver** [comment]
非常感谢作者如此迅速的帮忙解决问题，另外想请教一下，对于hls和webrtc （HEVC编码）后期是否能支持，技术开发上是否可行？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "langhuihui/jessibuca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月27日(星期五) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [langhuihui/jessibuca] 浏览器崩溃 (#61)





 
@Smallkserver 更新到最新版本试下。问题应该已经修复了。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
