### ISSUE TITLE
关于截图相关 API 的一些问题

### ISSUE THREAD

**Issue by suiyun39** [langhuihui/H5RtmpClient#63]
当前版本无论是截图按钮还是 screenshot 方法, 都只能实现截图后下载文件的默认行为. 外部无法控制截图之后的行为. 比如截图之后拿到 base64 进行后续操作.
现在我 fork 了一份, 打算加上这些支持. 目标如下:
- 添加一个配置项来配置截图按钮的默认行为. 可以从外部禁止文件下载.
- 添加一个截图事件, 当点击截图按钮或者执行 screenshot 方式时, 将截图的 base64 传入 callback 中
- 给 screenshot 方法添加特殊参数, 让其返回 base64

问题如下:
- 截图按钮的配置项应该设计到外部, 还是 operateBtns.screenshot 上. (同时支持 Boolean 和 Object 来保持兼容)
- screenshot 方法设计为第一个参数传入 `null` 时返回 base64 是否合理.
- 如果上一条不合理, 是否可以添加新的方法, 例如 screenshotForBase64

**Comment by langhuihui** [comment]
欢迎PR

**Comment by bosscheng** [comment]
@NoDocCat  我来加下把，支持base64 和 File 格式。

**Comment by bosscheng** [comment]
@NoDocCat 通过添加一个参数的形式解决了问题。 也不影响现有逻辑，可以去看下api文档。

**Comment by bendan52116** [comment]
怎么解决的？
