### ISSUE TITLE
在构造播放器的同时播放会产生问题

### ISSUE THREAD

**Issue by ht111111** [langhuihui/H5RtmpClient#65]
![image](https://user-images.githubusercontent.com/75420803/132337874-3e4208a3-978c-472d-9413-d5a6ade186b6.png)

![image](https://user-images.githubusercontent.com/75420803/132337966-1ed06fc0-130f-4a25-8bf8-66b1033d7d73.png)

在播放的时候   会一直加载  不会出现画面

**Comment by bosscheng** [comment]
@ht111111 看下 https://github.com/bosscheng/jessibuca-demo 这个。play不能直接掉用，要监听onload 之后才能调用。

**Comment by ht111111** [comment]
在同时播放四路视频的时候 进入全屏有时候会出现播放器不充满的现象，当调整浏览器视口播放器就会立刻充满，请问是什么原因吗 （一个视口被分为四块，每一块都不充满，只会显示canvas的高度1280 当摁下f12后 播放器会自动充满他所在的1/4块）

**Comment by ht111111** [comment]
解决了 我在fullscreen里面加了调整视图函数，
![image](https://user-images.githubusercontent.com/75420803/132782307-c198070e-4cf3-4eca-8892-14bdd438d453.png)
希望采纳

**Comment by ht111111** [comment]
解决了 我在fullscreen里面加了调整视图函数，
![image](https://user-images.githubusercontent.com/75420803/132782307-c198070e-4cf3-4eca-8892-14bdd438d453.png)
希望采纳

**Comment by bosscheng** [comment]
@ht111111 已采纳，谢谢。
