### ISSUE TITLE
播放1080P直播流浏览器崩溃

### ISSUE THREAD

**Issue by lzl20** [langhuihui/H5RtmpClient#66]
![1631170712(1)](https://user-images.githubusercontent.com/40020425/132638033-33b83800-ac23-4c27-be03-9890614af364.jpg)

**Comment by lzl20** [comment]
![1631172276(1)](https://user-images.githubusercontent.com/40020425/132641501-c884ba41-5234-4566-bcdc-7489f003cc19.jpg)视频播放时会报这些警告

**Comment by bosscheng** [comment]
@lzl20 有测试地址吗，定位下问题。

**Comment by lzl20** [comment]
@bosscheng 没有。项目是用内网，我把forceNoOffscreen设置成true后会稳定点

**Comment by bosscheng** [comment]
@lzl20 好的，有问题再交流。
