### ISSUE TITLE
报错this.getDelay is not a function

### ISSUE THREAD

**Issue by rcrwhyg** [langhuihui/H5RtmpClient#68]
![image](https://user-images.githubusercontent.com/56500577/133590987-1d54e724-22f2-48a4-89e0-9955b6c9fbf9.png)

**Comment by bosscheng** [comment]
@rcrwhyg 是怎么出现的？能提供一个操作方式或者一个demo？

**Comment by bosscheng** [comment]
@rcrwhyg 试下最新版本。
