### ISSUE TITLE
大华IPC H265播放报错

### ISSUE THREAD

**Issue by tobe718** [langhuihui/H5RtmpClient#7]
测试了一个大华的IPC，H265编码
开始能正常播放，后面就报如下错误
![image](https://user-images.githubusercontent.com/16471634/93177424-5b13c000-f765-11ea-80bf-93ab34683419.png)

这个有什么方法来排查吗？

**Comment by langhuihui** [comment]
从报错看是音频问题，你可以先关闭音频流试试

**Comment by bosscheng** [comment]
试下2.0版本把
