### ISSUE TITLE
地址后面能否不要.flv

### ISSUE THREAD

**Issue by penghd** [langhuihui/H5RtmpClient#70]
视频监控直播时，需要经过转码服务器，最后的播放地址是：
ws://转码服务器:xxx/xxx=?url=rtsp://xxxxxx，jessibuca播放要加.flv，否则播放不出
而有的rtsp地址是有&=的，这时候在后面加&0.flv，有的设备就报错。
反正也是flv播放器，能否不加后缀，flv.js就不需要。

补充，jessibuca用http去调是没问题的，ws就不行

**Comment by bosscheng** [comment]
@penghd ws 协议 也是类似 ws-flv 即ws://localhost/live/test.flv  协议。
我来添加一个参数，可以不通过文件后缀来判断。

**Comment by bosscheng** [comment]
@penghd 已经添加参数 isFlv 。

**Comment by penghd** [comment]
谢谢大佬。
