### ISSUE TITLE
视频内存溢出

### ISSUE THREAD

**Issue by JacksonTu** [langhuihui/H5RtmpClient#72]
使用ws-flv协议流，播放一段时间后，报视频内存溢出，整个页面崩溃

**Comment by bosscheng** [comment]
@JacksonTu 提供一个测试源看下呢。

**Comment by JacksonTu** [comment]
您好！这是我们一个项目上正式的视频流，您看一下
ws://183.6.110.83:18080/rtp/00A09C1B.flv
http://183.6.110.83:18080/rtp/00A09C1B.flv



***@***.***
 
发件人： wancheng1990
发送时间： 2021-09-22 17:12
收件人： langhuihui/jessibuca
抄送： JacksonTu; Mention
主题： Re: [langhuihui/jessibuca] 视频内存溢出 (#72)
@JacksonTu 提供一个测试源看下呢。

**Comment by bosscheng** [comment]
@JacksonTu 我在http://jessibuca.monibuca.com/player.html 试了下你的播放地址，暂时没有发现内存溢出现象，你这边有没有必先流程、

**Comment by JacksonTu** [comment]
内存溢出描述如下：
视频：ws://192.168.4.247:18080/rtp/00A037C1.flv
ws://192.168.4.247:18080/rtp/00A04F24.flv
 
视频播着播着就内存溢出了

**Comment by bosscheng** [comment]
@JacksonTu 测试了新的地址，发现都播放不起来。ws没有数据流过来。

**Comment by JacksonTu** [comment]
新地址是我内网地址，你肯定播不出来，还是上封邮件地址，可以加微信私聊么



***@***.***
 
发件人： wancheng1990
发送时间： 2021-09-23 15:33
收件人： langhuihui/jessibuca
抄送： JacksonTu; Mention
主题： Re: [langhuihui/jessibuca] 视频内存溢出 (#72)
@JacksonTu 测试了新的地址，发现都播放不起来。ws没有数据流过来。
―

**Comment by bosscheng** [comment]
@JacksonTu 微信号：bosswancheng
