### ISSUE TITLE
视频全屏问题

### ISSUE THREAD

**Issue by JacksonTu** [langhuihui/H5RtmpClient#73]
视频的操作按钮是自定义的，点击全屏的时候，再点击暂停，然后我销毁视频，再创建视频，然后全屏按钮失效，不能退出全屏，只能按f11和Esc退出全屏。

**Comment by bosscheng** [comment]
@JacksonTu 因为全屏绑定的dom元素被销毁掉了，所以才会导致全屏按钮失效。你可以暂时规避下全屏下面销毁再创建的流程、要解决这个问题，只能先退出全屏才行。如果交给jessibuca来做的话，销毁的时候判断下是否全屏，先退出全屏再销毁。不知道这样能否满足需求。

**Comment by JacksonTu** [comment]
感谢！我试试



***@***.***
 
发件人： wancheng1990
发送时间： 2021-09-22 17:15
收件人： langhuihui/jessibuca
抄送： JacksonTu; Mention
主题： Re: [langhuihui/jessibuca] 视频全屏问题 (#73)
@JacksonTu 因为全屏绑定的dom元素被销毁掉了，所以才会导致全屏按钮失效。你可以暂时规避下全屏下面销毁再创建的流程、要解决这个问题，只能先退出全屏才行。如果交给jessibuca来做的话，销毁的时候判断下是否全屏，先退出全屏再销毁。不知道这样能否满足需求。
―
