### ISSUE TITLE
播放时画面不卡,但是声音非常卡顿

### ISSUE THREAD

**Issue by zhaoli703098596** [langhuihui/H5RtmpClient#74]

**Comment by bosscheng** [comment]
@zhaoli703098596 给个测试地址看下呢

**Comment by zhaoli703098596** [comment]
> @zhaoli703098596给个测试地址看下呢

https://static-f9fc49dd-ead1-4ecc-b1d1-80b69f01ee28.bspapp.com/video/#/   华为 MHA-TL00 安卓9  EMUI 9.1

**Comment by bosscheng** [comment]
@zhaoli703098596 我用的mi10 测试的没有这样的发现声音卡顿的问题。手头没有这样的手机型号。不知道如何解决

**Comment by walkTtalk** [comment]
@bosscheng Mi note 型号 MI MAX， minui系统MIUI10.2稳定版。画面不卡，声音一直卡顿。好像年代久远的的手机声音都有问题，可以兼容吗。

**Comment by walkTtalk** [comment]
稍微近几年的手机画面和声音是正常的。

**Comment by bosscheng** [comment]
@walkTtalk 主要没有手机去复现问题

**Comment by walkTtalk** [comment]
@bosscheng 随便找一款老版本的小米应该可以复现

**Comment by bosscheng** [comment]
@walkTtalk 这种都不生产的手机身边找不到 [哭的表情]
