### ISSUE TITLE
当视频流播放不出来时，播放器会一直显示加载中的loadding状态

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#75]
![image](https://user-images.githubusercontent.com/39176130/136647320-3bfd88de-987c-4173-be65-13240020a732.png)
这种状态调用close()和clearView()都无法将画面的加载中清除掉并还原为这种初始状态
![image](https://user-images.githubusercontent.com/39176130/136647368-ef094bf6-086c-45d4-8df1-d88672737a18.png)

**Comment by bosscheng** [comment]
@yu1183688986 我来看下。

**Comment by yu1183688986** [comment]
> @yu1183688986 我来看下。

当你播放的视频流地址如果存在跨域情况，你就可以看到测试出这个现象

**Comment by bosscheng** [comment]
@yu1183688986 条件允许能不能给我个跨域地址。我找了半天没找到。哭ing

**Comment by yu1183688986** [comment]
> @yu1183688986 条件允许能不能给我个跨域地址。我找了半天没找到。哭ing

这个地址就可以
![1634522107(1)](https://user-images.githubusercontent.com/39176130/137657484-318cf0b7-3163-48aa-87c4-c77bebdc7943.jpg)
http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8

**Comment by bosscheng** [comment]
@yu1183688986 问题修复了。
