### ISSUE TITLE
RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by Enoooch** [langhuihui/H5RtmpClient#76]
![image](https://user-images.githubusercontent.com/39915133/137672445-cdbe1d08-bad6-431a-9bda-ebafccd508f8.png)

**Comment by bosscheng** [comment]
@Enoooch 条件允许，提供一个必先的测试源，我调试看下。

**Comment by bosscheng** [comment]
问题以解决。

**Comment by zhangminggeek** [comment]
> 问题以解决。

是什么问题呀，怎么解决的
