### ISSUE TITLE
视频播放久了会断开，重新播放插件会报错index.js:3 Uncaught TypeError: this.getDelay is not a function

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#78]
![image](https://user-images.githubusercontent.com/39176130/138053153-bbc588ad-3d90-4f9f-8de7-32f5e2babc03.png)
视频播放久了会自己断开，然后重新播放播放插件没有反应，浏览器报错如上图，刷新页面后可以正常播放。

**Comment by bosscheng** [comment]
@yu1183688986 试下最新版本看看呢。
