### ISSUE TITLE
 点击pause方法，会触发内存泄漏报错

### ISSUE THREAD

**Issue by lzl20** [langhuihui/H5RtmpClient#79]
最新的demo, 点击pause方法，会触发内存泄漏报错，
![1634787103(1)](https://user-images.githubusercontent.com/40020425/138207594-5ce7c1ee-2e48-4153-9290-5b3a430a8c91.jpg)

**Comment by bosscheng** [comment]
@lzl20 pause 有bug。目前没有好的办法修复。建议使用destroy 代替pause 。
