### ISSUE TITLE
单实例情况，多次切换不同视频流播放报错memory access out of bounds

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#81]
![image](https://user-images.githubusercontent.com/39176130/138377953-0cbef167-fb20-4503-8cad-e7252048c174.png)

**Comment by yu1183688986** [comment]
用的是最新版本，多实例分屏播放也出现这个问题了
![image](https://user-images.githubusercontent.com/39176130/138378296-6829c9d8-1863-4fd9-b636-b31c0f8a2129.png)

**Comment by bosscheng** [comment]
@yu1183688986 简单讲下操作步骤呢？

**Comment by yu1183688986** [comment]
> @yu1183688986 简单讲下操作步骤呢？

就是频繁的切换播放视频，每次播放之前都调用了clearView()和close()方法，切换多了 ，切换快了，就会出现视频播放不出来，浏览器控制台报如上错误的情况。我的是内网环境，所以不方便提供远程支持，这是我刚又触发了现象
![image](https://user-images.githubusercontent.com/39176130/138647424-f56b7c70-fe7b-4f97-81f2-daeffe865c9f.png)

**Comment by bosscheng** [comment]
@yu1183688986 你用的是最新版本的嘛? this.getDelay 报错的问题 应该已经修复了、

**Comment by bosscheng** [comment]
@yu1183688986  close() 方法有一个bug。目前没有好的方式去修复掉。建议如果切换播放视频，采用destroy 然后重试new 的方式去实现。 后续v3版本我改架构之后，就可以修复了。

**Comment by yu1183688986** [comment]
> @yu1183688986 close() 方法有一个bug。目前没有好的方式去修复掉。建议如果切换播放视频，采用destroy 然后重试new 的方式去实现。 后续v3版本我改架构之后，就可以修复了。

好的感谢

**Comment by bosscheng** [comment]
@yu1183688986 或者你可以再close 之后，延迟个500ms 再执行play 方法。现在的close 是同步方法，但是是通过postmessage 传递到 worker 里面去执行close 的，所以如果没有延迟的情况，就会出现异常报错。下一个版本我会优化实现的。
