### ISSUE TITLE
cannot play video stream with high resolution

### ISSUE THREAD

**Issue by pubpy2015** [langhuihui/H5RtmpClient#83]
Hi,
cannot play when video resolution is 9MP (4096x2160), when video resolution is 5MP (2448x2048) many frames dropped (VLC work fine), 
What parameters can I adjust ?

**Comment by pubpy2015** [comment]
this is error message:
![image](https://user-images.githubusercontent.com/59004953/138586404-993fa0ba-e34f-4547-8581-7323b34b8edb.png)

**Comment by bosscheng** [comment]
@pubpy2015 can you give me a demo by test

**Comment by pubpy2015** [comment]
I send url in email: 25022549@qq.com

**Comment by bosscheng** [comment]
@pubpy2015  you can use  https://github.com/langhuihui/jessibuca/tree/webcodecs

**Comment by pubpy2015** [comment]
Hi,

Run error:
![ảnh](https://user-images.githubusercontent.com/59004953/138827950-04f564ac-db48-42fe-a885-d38a3d7eeafe.png)

**Comment by pubpy2015** [comment]
Hi,

I still cannot play video stream with https://github.com/langhuihui/jessibuca/tree/webcodecs
(does not play any video stream)

**Comment by pubpy2015** [comment]
Can you fix this problem on v2 branch ?
