### ISSUE TITLE
auto reconnect function

### ISSUE THREAD

**Issue by pubpy2015** [langhuihui/H5RtmpClient#84]
Hi,

How to implement reconnect function ?

**Comment by bosscheng** [comment]
@pubpy2015 your can use jessibuca.on("timeout",function(){console.log('timeout')})

**Comment by pubpy2015** [comment]
Seem timeout event cannot fire when stream disconnected at start time.
It's only fire when connect successed and after that disconnected.
Now i am using a timer to check fps (jessibuca._stats.fps), if fps <= 0 in 15 seconds => reconnect
but seem when timeout jessibuca was destroyed and i cannot get fps by jessibuca._stats.fps

**Comment by pubpy2015** [comment]
Oh, see stats event, it can be using for reconnect. But seem there is an error here:
abps and vbps always empty!
![ảnh](https://user-images.githubusercontent.com/59004953/138804962-9a16c3c7-ad04-469d-9fe0-443dc2c0d7c8.png)

**Comment by bosscheng** [comment]
@pubpy2015 'Seem timeout event cannot fire when stream disconnected at start time.
' this question has be resolve by latest version .

you can set timeout by new Jessibuca({timeout:10})   


you can see http://jessibuca.monibuca.com/api.html
