### ISSUE TITLE
初始化一个实例，浏览器会发两次获取ff.wasm的请求。

### ISSUE THREAD

**Issue by yu1183688986** [langhuihui/H5RtmpClient#87]
![image](https://user-images.githubusercontent.com/39176130/138794374-e06e0efc-95db-41dc-8aba-a9716bd2ae7f.png)

**Comment by bosscheng** [comment]
@yu1183688986 贴下你代码如何写的。我看来下http://jessibuca.monibuca.com/player.html  是没有两次请求ff.wasm

**Comment by bosscheng** [comment]
@yu1183688986 http://jessibuca.monibuca.com/demo.html 这里是各个demo  里面应该也只请求了一次ff.wam

**Comment by DaikonX** [comment]
我也触发了2次  丢到线上就会触发2次 本地开发就1次

**Comment by bosscheng** [comment]
@DaikonX 玄学
