### ISSUE TITLE
Slow when open multi streams

### ISSUE THREAD

**Issue by pubpy2015** [langhuihui/H5RtmpClient#88]
Hi,

I am using 4 players on page to play 4 different streams.
if all streams available, it's work fine but if first stream not available (dropped) => player2, player3, player4 take more time to connect to stream2,3,4. Sometimes player 2,3,4 cannot connect although stream 2,3,4 available.

**Comment by bosscheng** [comment]
@pubpy2015 you can play 

`
for (let i = 1; i < 4; i++) {
            const $player = document.getElementById('webPlayer' + i);
            setTimeout(() => {
                const player = new Jessibuca({
                    //........
                })
            }, i * 200)
        }
`

demo

**Comment by pubpy2015** [comment]
Thanks,

I see you updated v3, is it ready?
