### ISSUE TITLE
IOS 没有声音

### ISSUE THREAD

**Issue by terranZY** [langhuihui/H5RtmpClient#9]
IOS 没有声音，有方案解决吗？

**Comment by bosscheng** [comment]
iPhone，chrome等要求自动播放时，音频必须静音，需要由一个真实的用户交互操作来恢复，不能使用代码。

可以手动触发audioResume() 方法，来恢复声音。

**Comment by Vit-boy** [comment]
手动触发，是否必须是用户交互后的触发？比如我在touchend事件中来播放视频，然后再调用此方法是否可以播放视频中的音频？

**Comment by bosscheng** [comment]
@Vit-boy 是的，这样应该就行了。
