### ISSUE TITLE
请求404不会触发error事件

### ISSUE THREAD

**Issue by tangwei88** [langhuihui/H5RtmpClient#96]

**Comment by bosscheng** [comment]
@tangwei88 会触发的啊，你看下你的版本是不是最新版本。
index.js:3 Jessibuca play http://localhost:8081/jessica/live/rtc
app.fe1c3829.js:1 on log TypeError: Failed to fetch
app.fe1c3829.js:1 error TypeError: Failed to fetch
index.js:3 worker close
index.js:3 Jessibuca play http://localhost:8081/jessica/live/rtc.flv
app.fe1c3829.js:1 on log TypeError: Failed to fetch
app.fe1c3829.js:1 error TypeError: Failed to fetch
index.js:3 worker close
index.js:3 Jessibuca play ws://localhost:8081/jessica/live/rtc.flv
index.js:3 WebSocket connection to 'ws://localhost:8081/jessica/live/rtc.flv' failed: 
play @ index.js:3
self.onmessage @ index.js:3
app.fe1c3829.js:1 on log [object Event]
app.fe1c3829.js:1 error [object Event]
app.fe1c3829.js:1 timeout
index.js:3 worker close
