### ISSUE TITLE
cpu占用优化情况汇报

### ISSUE THREAD

**Issue by ruixiu** [langhuihui/H5RtmpClient#98]
经验证，每打开一个播放器占用大概10%的CPU资源，在一屏展示多个播放器的场景下会导致浏览器卡顿。请问有没有优化的方案？

**Comment by bosscheng** [comment]
@ruixiu 如果是h264,就使用MSE硬解码。软解的话，必然是消耗CPU资源的。只能提升机器硬件性能，或者降低视频分辨率。

**Comment by langhuihui** [comment]
WebCodecs可以减少CPU消耗的

**Comment by ruixiu** [comment]
> @ruixiu 如果是h264,就使用MSE硬解码。软解的话，必然是消耗CPU资源的。只能提升机器硬件性能，或者降低视频分辨率。
使用MSE硬解码问题解决

> WebCodecs可以减少CPU消耗的
使用WebCodecs占用的是GPU

**Comment by ruixiu** [comment]
@bosscheng 经验证发现，不开启MSE硬解码延迟和直接播放rtsp一样，开启MSE硬解码，延迟没有自动追齐

**Comment by bosscheng** [comment]
@ruixiu ok 我来看下。

**Comment by bosscheng** [comment]
@ruixiu 帮忙测试下 webcodecs 有没有延迟的问题，谢谢啦。

**Comment by ruixiu** [comment]
@bosscheng 配置useWCS: true，不配置useMSE，开始播放有时候会有延迟，但是会自动追齐

**Comment by bosscheng** [comment]
@ruixiu 谢啦。我来把问题修复下。大体知道问题出在哪边了。

**Comment by bosscheng** [comment]
@ruixiu 可以试下最新版本 MSE 的追帧情况了。

**Comment by ruixiu** [comment]
@bosscheng 追帧情况正常了。不过又出现了另外的情况（使用chrome浏览器），步骤为：
1.使用官方播放器ws-raw，可以正常播放
2.切换浏览器选项卡再切换回来播放器界面卡住
3.等待一会儿（时间不固定）由花屏慢慢恢复正常

另：不开启硬解码和开启useWCS均无上述情况
